import type {
  PlayGamePackDraft,
  PlayGameStyle,
  PlayGameType,
} from "@/services/play/playGamePackService";
import type { CreatorFocusCode } from "@/features/membership/creatorFocusAccess";

export interface NonMusicPlayBlueprint
  extends Omit<
    PlayGamePackDraft,
    "id" | "genre" | "visibility" | "scheduled_start_at" | "scheduled_end_at"
  > {
  game_type: PlayGameType;
  game_style: PlayGameStyle;
  creator_focus: CreatorFocusCode | null;
}

export const NON_MUSIC_PLAY_BLUEPRINTS: NonMusicPlayBlueprint[] = [
  {
    pack_key: "film-ww-001",
    game_type: "hidden_gems",
    title: "Wait...WHAT?! Movie Edition",
    description: "Some movie stories sound fake. Which ones actually happened?",
    focus_scope: "single_focus",
    creator_focus: "film",
    topic: "Behind the Scenes",
    game_style: "true_or_made_up",
    artwork_url: "/images/play/focus-packs/wait-what-movie-edition.webp",
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "film-dc-002",
    game_type: "hidden_gems",
    title: "Director's Chair",
    description: "Clues, facts, and films. How fast can you identify the filmmaker?",
    focus_scope: "single_focus",
    creator_focus: "film",
    topic: "Directors",
    game_style: "progressive_clue",
    artwork_url: "/images/play/focus-packs/directors-chair.webp",
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "film-vm-003",
    game_type: "vybe_match",
    title: "Behind the Camera Match",
    description: "Match filmmakers with projects and career facts.",
    focus_scope: "single_focus",
    creator_focus: "film",
    topic: "Filmmakers",
    game_style: "match",
    artwork_url: null,
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "film-time-004",
    game_type: "daily_vybe",
    title: "From Silent to Virtual",
    description: "Put major film-technology moments in order.",
    focus_scope: "single_focus",
    creator_focus: "film",
    topic: "Film Technology",
    game_style: "timeline",
    artwork_url: null,
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "act-lives-001",
    game_type: "hidden_gems",
    title: "One Actor. Many Lives.",
    description: "Three roles. One actor. Can you name the performer?",
    focus_scope: "single_focus",
    creator_focus: "acting",
    topic: "Actors / Roles",
    game_style: "three_clue",
    artwork_url: "/images/play/focus-packs/one-actor-many-lives.webp",
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "act-wpi-002",
    game_type: "beat_blitz",
    title: "Who Played It?",
    description: "Ten roles. Sixty seconds. How many actors can you name?",
    focus_scope: "single_focus",
    creator_focus: "acting",
    topic: "Famous Roles",
    game_style: "speed_round",
    artwork_url: "/images/play/focus-packs/who-played-it.webp",
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "act-vm-003",
    game_type: "vybe_match",
    title: "Character Connections",
    description: "Match actors with the characters they played.",
    focus_scope: "single_focus",
    creator_focus: "acting",
    topic: "Characters",
    game_style: "match",
    artwork_url: null,
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "act-choice-004",
    game_type: "daily_vybe",
    title: "You're the Casting Director",
    description: "A future creator-powered supporter choice game using participating VYBE actors.",
    focus_scope: "single_focus",
    creator_focus: "acting",
    topic: "Casting",
    game_style: "supporter_choice",
    artwork_url: null,
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "com-myth-001",
    game_type: "hidden_gems",
    title: "Comedy or Myth?",
    description: "Comedy history is stranger than the jokes. Fact or fiction?",
    focus_scope: "single_focus",
    creator_focus: "comedy",
    topic: "Comedy History",
    game_style: "fact_or_myth",
    artwork_url: "/images/play/focus-packs/comedy-or-myth.webp",
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "com-btl-002",
    game_type: "hidden_gems",
    title: "Before the Laughs",
    description: "Before they were famous, they did something else. Who was it?",
    focus_scope: "single_focus",
    creator_focus: "comedy",
    topic: "Comedy Careers",
    game_style: "progressive_clue",
    artwork_url: "/images/play/focus-packs/before-the-laughs.webp",
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "com-match-003",
    game_type: "vybe_match",
    title: "What Kind of Comedy?",
    description: "Match comedy styles with their descriptions.",
    focus_scope: "single_focus",
    creator_focus: "comedy",
    topic: "Comedy Styles",
    game_style: "match",
    artwork_url: null,
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "pod-mic-001",
    game_type: "beat_blitz",
    title: "Behind the Mic",
    description: "From RSS to podfade — how much do you know about podcasting?",
    focus_scope: "single_focus",
    creator_focus: "podcasting",
    topic: "Podcast Knowledge",
    game_style: "choice",
    artwork_url: "/images/play/focus-packs/behind-the-mic.webp",
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "pod-rw-002",
    game_type: "hidden_gems",
    title: "Real Word or We Made It Up?",
    description: "Which podcast terms are real and which ones did VYBE make up?",
    focus_scope: "single_focus",
    creator_focus: "podcasting",
    topic: "Podcast Terminology",
    game_style: "real_or_made_up",
    artwork_url: null,
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "pod-vm-003",
    game_type: "vybe_match",
    title: "Behind the Mic Match",
    description: "Match podcast terminology and formats with the right descriptions.",
    focus_scope: "single_focus",
    creator_focus: "podcasting",
    topic: "Podcast Formats",
    game_style: "match",
    artwork_url: null,
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "pod-choice-004",
    game_type: "daily_vybe",
    title: "Build the Show",
    description: "Your podcast. Your rules. What kind of show would you create?",
    focus_scope: "single_focus",
    creator_focus: "podcasting",
    topic: "Show Formats",
    game_style: "preference",
    artwork_url: "/images/play/focus-packs/build-the-show.webp",
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "write-weird-001",
    game_type: "hidden_gems",
    title: "Who Wrote Like That?!",
    description: "Famous writers. Unusual habits. Can you guess who did what?",
    focus_scope: "single_focus",
    creator_focus: "writing",
    topic: "Writer Habits",
    game_style: "progressive_clue",
    artwork_url: "/images/play/focus-packs/who-wrote-like-that.webp",
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "write-wrong-002",
    game_type: "hidden_gems",
    title: "When Writing Went Wrong",
    description: "Discover damaged manuscripts, pen names, mishaps, and literary oddities.",
    focus_scope: "single_focus",
    creator_focus: "writing",
    topic: "Literary Oddities",
    game_style: "story_reveal",
    artwork_url: null,
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "write-vm-003",
    game_type: "vybe_match",
    title: "Pen Name Please",
    description: "Match writers with the pen names behind their work.",
    focus_scope: "single_focus",
    creator_focus: "writing",
    topic: "Pen Names",
    game_style: "match",
    artwork_url: null,
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "write-time-004",
    game_type: "daily_vybe",
    title: "How Did We Get the Book?",
    description: "Put major moments in the history of books and publishing in order.",
    focus_scope: "single_focus",
    creator_focus: "writing",
    topic: "Book History",
    game_style: "timeline",
    artwork_url: "/images/play/focus-packs/from-page-to-book.webp",
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "write-part-005",
    game_type: "daily_vybe",
    title: "One Line. Three Words.",
    description: "A future supporter writing challenge requiring moderation and submission controls.",
    focus_scope: "single_focus",
    creator_focus: "writing",
    topic: "Supporter Participation",
    game_style: "open_response",
    artwork_url: null,
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "dance-origin-001",
    game_type: "hidden_gems",
    title: "Where Did It Start?",
    description: "You know the move. Do you know the culture behind it?",
    focus_scope: "single_focus",
    creator_focus: "dance",
    topic: "Dance Geography / Origins",
    game_style: "origin_challenge",
    artwork_url: "/images/play/focus-packs/where-did-it-start.webp",
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "dance-world-002",
    game_type: "vybe_match",
    title: "Dance Around the World",
    description: "Match dance styles with their home cultures.",
    focus_scope: "single_focus",
    creator_focus: "dance",
    topic: "Cultural Dance",
    game_style: "match",
    artwork_url: "/images/play/focus-packs/dance-around-the-world.webp",
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "dance-vm-003",
    game_type: "vybe_match",
    title: "Move → Origin",
    description: "Match each dance style with its origin.",
    focus_scope: "single_focus",
    creator_focus: "dance",
    topic: "Dance Origins",
    game_style: "match",
    artwork_url: null,
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "dance-time-004",
    game_type: "daily_vybe",
    title: "From Then to Now",
    description: "Put dance and pop-culture moments in chronological order.",
    focus_scope: "single_focus",
    creator_focus: "dance",
    topic: "Dance History",
    game_style: "timeline",
    artwork_url: null,
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "ctv-001",
    game_type: "vybe_match",
    title: "Everything Connects",
    description: "Different worlds. One connection. Follow the links across entertainment.",
    focus_scope: "cross_focus",
    creator_focus: null,
    topic: "Entertainment Connections",
    game_style: "connection_chain",
    artwork_url: "/images/play/focus-packs/connect-the-vybe.webp",
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "ctv-six-002",
    game_type: "vybe_match",
    title: "Six Degrees of VYBE",
    description: "Fill the missing relationship in an entertainment connection chain.",
    focus_scope: "cross_focus",
    creator_focus: null,
    topic: "Entertainment Connections",
    game_style: "connection_chain",
    artwork_url: null,
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "ctv-bridge-003",
    game_type: "vybe_match",
    title: "What's the Bridge?",
    description: "Find the missing link connecting creators, projects, and creative disciplines.",
    focus_scope: "cross_focus",
    creator_focus: null,
    topic: "Entertainment Connections",
    game_style: "missing_link",
    artwork_url: null,
    discovery_url: "/explore",
    featured: false,
  },
  {
    pack_key: "ctv-multi-004",
    game_type: "daily_vybe",
    title: "One Person. How Many VYBEs?",
    description: "Select all creative areas associated with a multidisciplinary creator.",
    focus_scope: "cross_focus",
    creator_focus: null,
    topic: "Multidisciplinary Creators",
    game_style: "multi_select",
    artwork_url: null,
    discovery_url: "/explore",
    featured: false,
  },
];
