import { createFileRoute } from "@tanstack/react-router";

export const Route=createFileRoute("/api/video-status")({server:{handlers:{POST:async({request})=>{
 const authorization=request.headers.get("authorization");if(!authorization?.startsWith("Bearer "))return Response.json({error:"Sign in to check video processing."},{status:401});
 const input=(await request.json().catch(()=>({}))) as {videoId?:string};if(!input.videoId)return Response.json({error:"Video ID is required."},{status:400});
 const accountId=process.env.CLOUDFLARE_ACCOUNT_ID;const apiToken=process.env.CLOUDFLARE_STREAM_API_TOKEN;if(!accountId||!apiToken)return Response.json({error:"Cloudflare Stream is not configured.",code:"STREAM_NOT_CONFIGURED"},{status:503});
 const{supabaseAdmin}=await import("@/integrations/supabase/client.server");const db=supabaseAdmin as any;const token=authorization.slice("Bearer ".length);const{data:authData,error:authError}=await supabaseAdmin.auth.getUser(token);if(authError||!authData.user)return Response.json({error:"Your session has expired."},{status:401});
 const{data:video,error:videoError}=await supabaseAdmin.from("creator_videos").select("id,creator_id,provider,provider_video_id,status").eq("id",input.videoId).eq("creator_id",authData.user.id).maybeSingle();if(videoError||!video)return Response.json({error:"Video was not found."},{status:404});if(video.provider!=="cloudflare_stream")return Response.json({state:video.status,progress:100});
 const response=await fetch(`https://api.cloudflare.com/client/v4/accounts/${accountId}/stream/${encodeURIComponent(video.provider_video_id)}`,{headers:{Authorization:`Bearer ${apiToken}`}});const cloudflare=(await response.json().catch(()=>({}))) as {success?:boolean;result?:{readyToStream?:boolean;readyToStreamAt?:string;duration?:number;thumbnail?:string;status?:{state?:string;pctComplete?:string|number;errorReasonText?:string}};errors?:Array<{message?:string}>};if(!response.ok||!cloudflare.success||!cloudflare.result)return Response.json({error:cloudflare.errors?.[0]?.message||"Could not check Stream processing."},{status:502});
 const result=cloudflare.result;const state=result.readyToStream||result.status?.state==="ready"?"ready":result.status?.state==="error"?"error":"processing";const progress=state==="ready"?100:Math.max(0,Math.min(99,Math.round(Number(result.status?.pctComplete)||0)));const update=state==="ready"?{status:"draft",processing_progress:100,processing_error:null,ready_at:result.readyToStreamAt||new Date().toISOString(),duration_sec:result.duration?Math.round(result.duration):null,thumbnail_url:result.thumbnail||null}:state==="error"?{status:"failed",processing_progress:progress,processing_error:result.status?.errorReasonText||"Stream could not process this video."}:{status:"processing",processing_progress:progress,processing_error:null};const{error:updateError}=await db.from("creator_videos").update(update).eq("id",video.id).eq("creator_id",authData.user.id);if(updateError)return Response.json({error:updateError.message},{status:500});return Response.json({state,progress,error:state==="error"?update.processing_error:null});
}}}});
