import { supabase } from "@/integrations/supabase/client";
import { membershipService } from "@/services/membership/membershipService";
import type { WrittenCollection, WrittenCollectionItem, WrittenProject, WrittenWork, WrittenWorkMedia, WrittenWorkType, WrittenVisibility } from "@/features/writing/schema";
const db:any=supabase; const AUDIO_BUCKET="writing-audio"; const COVER_BUCKET="writing-covers"; const MAX_AUDIO=100*1024*1024; const MAX_COVER=5*1024*1024;
const safe=(name:string)=>name.replace(/[^a-zA-Z0-9._-]+/g,"_");
const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,80)||"work";
async function signed(bucket:string,path:string|null,ttl=60*60*3){if(!path)return null;const{data}=await supabase.storage.from(bucket).createSignedUrl(path,ttl);return data?.signedUrl||null;}
async function hydrateWork(row:any):Promise<WrittenWork>{return{...row,cover_url:await signed(COVER_BUCKET,row.cover_path)};}
async function hydrateMedia(row:any):Promise<WrittenWorkMedia>{return{...row,audio_url:row.audio_path?await signed(AUDIO_BUCKET,row.audio_path):null};}
export const writingService={
 async assertCanCreate(){const m=await membershipService.getMine();const limit=m.future_allowances.written_posts;const{count,error}=await db.from("creator_written_works").select("id",{count:"exact",head:true}).neq("status","archived");if(error)throw error;if(limit>=0&&(count??0)>=limit)throw new Error(`Your membership currently includes ${limit} written works. Archive a work or review your membership before creating another.`);return m;},
 async listMine(creatorId:string){const{data,error}=await db.from("creator_written_works").select("*").eq("creator_id",creatorId).order("updated_at",{ascending:false});if(error)throw error;return Promise.all((data||[]).map(hydrateWork));},
 async listPublic(creatorId?:string){let q=db.from("creator_written_works").select("*").eq("status","published").eq("visibility","public").order("published_at",{ascending:false});if(creatorId)q=q.eq("creator_id",creatorId);const{data,error}=await q;if(error)throw error;return Promise.all((data||[]).map(hydrateWork));},
 async getMine(id:string,creatorId:string){const{data,error}=await db.from("creator_written_works").select("*").eq("id",id).eq("creator_id",creatorId).single();if(error)throw error;return hydrateWork(data);},
 async getPublic(slug:string){const{data,error}=await db.from("creator_written_works").select("*").eq("slug",slug).eq("status","published").in("visibility",["public","unlisted"]).maybeSingle();if(error)throw error;if(!data)return null;const work=await hydrateWork(data);const media=await this.listMedia(work.id,true);const{data:profile}=await db.from("creator_profiles").select("user_id,username,artist_name,display_name,avatar_url,avatar_path").eq("user_id",work.creator_id).maybeSingle();return{work,media,profile};},
 async create(creatorId:string,input:{title:string;workType:WrittenWorkType;excerpt?:string;body?:string}){await this.assertCanCreate();const base=slugify(input.title);const slug=`${base}-${crypto.randomUUID().slice(0,8)}`;const{data,error}=await db.from("creator_written_works").insert({creator_id:creatorId,slug,title:input.title.trim(),work_type:input.workType,excerpt:(input.excerpt||"").trim(),body:input.body||"",status:"draft",visibility:"private",rights_confirmed:false}).select("*").single();if(error)throw error;return data as WrittenWork;},
 async update(id:string,creatorId:string,input:{title:string;workType:WrittenWorkType;excerpt:string;body:string;projectId:string|null;visibility:WrittenVisibility;showOnPublicProfile:boolean;rightsConfirmed:boolean}){const{data,error}=await db.from("creator_written_works").update({title:input.title.trim(),work_type:input.workType,excerpt:input.excerpt.trim(),body:input.body,project_id:input.projectId,visibility:input.visibility,show_on_public_profile:input.showOnPublicProfile,rights_confirmed:input.rightsConfirmed}).eq("id",id).eq("creator_id",creatorId).select("*").single();if(error)throw error;return hydrateWork(data);},
 async setPublished(id:string,creatorId:string,published:boolean){const{data:current,error:r}=await db.from("creator_written_works").select("rights_confirmed,visibility").eq("id",id).eq("creator_id",creatorId).single();if(r)throw r;if(published&&!current.rights_confirmed)throw new Error("Confirm that you have the rights to publish this work before publishing.");const payload=published?{status:"published",visibility:current.visibility==="private"?"public":current.visibility,published_at:new Date().toISOString()}:{status:"draft",published_at:null};const{error}=await db.from("creator_written_works").update(payload).eq("id",id).eq("creator_id",creatorId);if(error)throw error;},
 async uploadAudio(workId:string,creatorId:string,file:File,title:string){if(file.size>MAX_AUDIO)throw new Error("Spoken-word audio must be 100MB or smaller.");if(!file.type.startsWith("audio/"))throw new Error("Choose an audio file.");const path=`${creatorId}/${workId}/${Date.now()}-${safe(file.name)}`;const{error:u}=await supabase.storage.from(AUDIO_BUCKET).upload(path,file,{contentType:file.type,cacheControl:"3600"});if(u)throw u;const{data,error}=await db.from("creator_written_work_media").insert({work_id:workId,creator_id:creatorId,media_type:"audio",audio_path:path,title:title.trim()||file.name}).select("*").single();if(error){await supabase.storage.from(AUDIO_BUCKET).remove([path]);throw error;}return hydrateMedia(data);},
 async attachVideo(workId:string,creatorId:string,videoId:string,title:string){const{data:v,error:ve}=await db.from("creator_videos").select("id,creator_id,title").eq("id",videoId).eq("creator_id",creatorId).single();if(ve||!v)throw ve||new Error("Video not found.");const{data,error}=await db.from("creator_written_work_media").insert({work_id:workId,creator_id:creatorId,media_type:"video",video_id:videoId,title:title.trim()||v.title}).select("*").single();if(error)throw error;return data as WrittenWorkMedia;},
 async addExternal(workId:string,creatorId:string,url:string,title:string){new URL(url);const{data,error}=await db.from("creator_written_work_media").insert({work_id:workId,creator_id:creatorId,media_type:"external",external_url:url.trim(),title:title.trim()||"Related link"}).select("*").single();if(error)throw error;return data as WrittenWorkMedia;},
 async listMedia(workId:string,publicOnly=false){let q=db.from("creator_written_work_media").select("*").eq("work_id",workId).order("sort_order");const{data,error}=await q;if(error)throw error;return Promise.all((data||[]).map(hydrateMedia));},
 async removeMedia(id:string,creatorId:string){const{data,error:r}=await db.from("creator_written_work_media").select("audio_path").eq("id",id).eq("creator_id",creatorId).single();if(r)throw r;const{error}=await db.from("creator_written_work_media").delete().eq("id",id).eq("creator_id",creatorId);if(error)throw error;if(data.audio_path)await supabase.storage.from(AUDIO_BUCKET).remove([data.audio_path]);},
 async listProjects(creatorId:string){const{data,error}=await db.from("creator_written_projects").select("*").eq("creator_id",creatorId).order("updated_at",{ascending:false});if(error)throw error;return(data||[]) as WrittenProject[];},
 async createProject(creatorId:string,title:string,projectType:string){const{data,error}=await db.from("creator_written_projects").insert({creator_id:creatorId,title:title.trim(),project_type:projectType}).select("*").single();if(error)throw error;return data as WrittenProject;},
 async listCollections(creatorId:string){const{data,error}=await db.from("creator_written_collections").select("*").eq("creator_id",creatorId).order("updated_at",{ascending:false});if(error)throw error;return(data||[]) as WrittenCollection[];},
 async listPublicCollections(creatorId?:string){let q=db.from("creator_written_collections").select("*").eq("status","published").eq("visibility","public").order("updated_at",{ascending:false});if(creatorId)q=q.eq("creator_id",creatorId);const{data,error}=await q;if(error)throw error;return(data||[]) as WrittenCollection[];},
 async createCollection(creatorId:string,title:string,description:string){const slug=`${slugify(title)}-${crypto.randomUUID().slice(0,8)}`;const{data,error}=await db.from("creator_written_collections").insert({creator_id:creatorId,slug,title:title.trim(),description:description.trim()}).select("*").single();if(error)throw error;return data as WrittenCollection;},
 async addCollectionItem(collectionId:string,workId:string,mediaId:string|null,creatorId:string){const{data:c,error:ce}=await db.from("creator_written_collections").select("id").eq("id",collectionId).eq("creator_id",creatorId).single();if(ce||!c)throw ce||new Error("Collection not found.");const{data:w,error:we}=await db.from("creator_written_works").select("id").eq("id",workId).eq("creator_id",creatorId).single();if(we||!w)throw we||new Error("Work not found.");const{data:last}=await db.from("creator_written_collection_items").select("position").eq("collection_id",collectionId).order("position",{ascending:false}).limit(1);const position=(last?.[0]?.position??0)+1;const{data,error}=await db.from("creator_written_collection_items").insert({collection_id:collectionId,work_id:workId,media_id:mediaId,position}).select("*").single();if(error)throw error;return data as WrittenCollectionItem;},
 async removeCollectionItem(itemId:string,creatorId:string){const{data:item,error:r}=await db.from("creator_written_collection_items").select("id,collection_id").eq("id",itemId).single();if(r||!item)throw r||new Error("Collection item not found.");const{data:collection,error:c}=await db.from("creator_written_collections").select("id").eq("id",item.collection_id).eq("creator_id",creatorId).single();if(c||!collection)throw c||new Error("Collection not found.");const{error}=await db.from("creator_written_collection_items").delete().eq("id",itemId);if(error)throw error;},
 async listCollectionItems(collectionId:string){const{data,error}=await db.from("creator_written_collection_items").select("*,work:creator_written_works(*),media:creator_written_work_media(*)").eq("collection_id",collectionId).order("position");if(error)throw error;return(data||[]) as WrittenCollectionItem[];},
 async getPublicCollection(slug:string){const{data:collection,error}=await db.from("creator_written_collections").select("*").eq("slug",slug).eq("status","published").in("visibility",["public","unlisted"]).maybeSingle();if(error)throw error;if(!collection)return null;const{data:rows,error:itemsError}=await db.from("creator_written_collection_items").select("*,work:creator_written_works(*),media:creator_written_work_media(*)").eq("collection_id",collection.id).order("position");if(itemsError)throw itemsError;const items=[];for(const row of rows||[]){const work=await hydrateWork(row.work);let media=row.media?await hydrateMedia(row.media):null;if(!media){const{data:first}=await db.from("creator_written_work_media").select("*").eq("work_id",work.id).eq("media_type","audio").order("sort_order").limit(1);if(first?.[0])media=await hydrateMedia(first[0]);}items.push({...row,work,media});}const{data:profile}=await db.from("creator_profiles").select("user_id,username,artist_name,display_name").eq("user_id",collection.creator_id).maybeSingle();return{collection,items,profile};},
 async setCollectionPublished(id:string,creatorId:string,published:boolean){const{error}=await db.from("creator_written_collections").update(published?{status:"published",visibility:"public"}:{status:"draft"}).eq("id",id).eq("creator_id",creatorId);if(error)throw error;}
};
