import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ShieldAlert } from "lucide-react";
import { toast } from "sonner";
import { RoleGuard } from "@/components/auth/RoleGuard";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { WorkspacePageHeader } from "@/components/workspace/WorkspacePageHeader";
import { copyrightComplianceService } from "@/services/compliance/copyrightComplianceService";

export const Route = createFileRoute("/_authenticated/admin_/copyright")({component:()=> <RoleGuard allow={["admin"]}><CopyrightAdmin /></RoleGuard>});

function CopyrightAdmin(){
  const client=useQueryClient(); const [notes,setNotes]=useState<Record<string,string>>({}); const [targets,setTargets]=useState<Record<string,{type:string;id:string;creatorId:string}>>({});
  const [auditTarget,setAuditTarget]=useState({creatorId:"",targetType:"track",targetId:"",reason:"manual",request:"Provide ownership, contributor, license, sample-clearance and artwork evidence applicable to this item."});
  const {data:cases=[],isLoading}=useQuery({queryKey:["admin-copyright-cases"],queryFn:copyrightComplianceService.adminCases});
  const {data:audits=[]}=useQuery({queryKey:["admin-rights-audits"],queryFn:copyrightComplianceService.audits});
  const refresh=()=>Promise.all([client.invalidateQueries({queryKey:["admin-copyright-cases"]}),client.invalidateQueries({queryKey:["admin-rights-audits"]})]);
  const update=useMutation({mutationFn:({id,status}:{id:string;status:string})=>copyrightComplianceService.updateCase(id,status,notes[id]||"",targets[id]),onSuccess:async()=>{await refresh();toast.success("Case updated.");},onError:(e)=>toast.error(e instanceof Error?e.message:"Case update failed.")});
  const strike=useMutation({mutationFn:({id}:{id:string})=>copyrightComplianceService.issueStrike(id,notes[id]||"Documented copyright violation"),onSuccess:async(count)=>{await refresh();toast.success(`Strike recorded. ${count} counting strike(s) in 12 months.`);}});
  const restore=useMutation({mutationFn:(id:string)=>copyrightComplianceService.scheduleRestoration(id),onSuccess:async()=>{await refresh();toast.success("Restoration window recorded. Verify business-day calculation and court-action status before restoring.");}});
  const restoreMaterial=useMutation({mutationFn:(id:string)=>copyrightComplianceService.restoreMaterial(id),onSuccess:async()=>{await refresh();toast.success("Material restored and case closed.");},onError:(e)=>toast.error(e instanceof Error?e.message:"Restoration failed.")});
  const generate=useMutation({mutationFn:copyrightComplianceService.generateAudits,onSuccess:async(count)=>{await refresh();toast.success(`${count} neutral random audit(s) created.`);}});
  const createAudit=useMutation({mutationFn:()=>copyrightComplianceService.createAudit(auditTarget),onSuccess:async()=>{await refresh();toast.success("Targeted rights check created.");setAuditTarget((c)=>({...c,creatorId:"",targetId:""}));},onError:(e)=>toast.error(e instanceof Error?e.message:"Could not create rights check.")});
  return <div className="mx-auto max-w-6xl space-y-5"><WorkspacePageHeader eyebrow="Trust and safety" title="Copyright Operations" description="Triage notices, control access, process counter-notices, document strikes and administer neutral rights checks." status={<Badge variant="outline">{cases.filter((x:any)=>!["closed","rejected","restored"].includes(x.status)).length} open</Badge>}/>
    <Card><CardContent className="space-y-4 p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-semibold">Monthly neutral sample</h2><p className="text-sm text-muted-foreground">Select approximately 5% of eligible public tracks, capped at 25. Selection alone is not a strike or accusation.</p></div><Button variant="outline" onClick={()=>generate.mutate()} disabled={generate.isPending}>Generate random audits</Button></div><div className="border-t pt-4"><h3 className="font-semibold">Create a documented risk-based check</h3><div className="mt-3 grid gap-3 md:grid-cols-4"><Field label="Creator UUID" value={auditTarget.creatorId} onChange={(creatorId)=>setAuditTarget((c)=>({...c,creatorId}))}/><Field label="Target type" value={auditTarget.targetType} onChange={(targetType)=>setAuditTarget((c)=>({...c,targetType}))}/><Field label="Target UUID" value={auditTarget.targetId} onChange={(targetId)=>setAuditTarget((c)=>({...c,targetId}))}/><Field label="Reason" value={auditTarget.reason} onChange={(reason)=>setAuditTarget((c)=>({...c,reason}))}/></div><Textarea className="mt-3" value={auditTarget.request} onChange={(e)=>setAuditTarget((c)=>({...c,request:e.target.value}))}/><Button className="mt-3" variant="outline" disabled={createAudit.isPending||!auditTarget.creatorId||!auditTarget.targetId} onClick={()=>createAudit.mutate()}>Create targeted check</Button></div></CardContent></Card>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Notice and dispute queue</h2>{isLoading?<p>Loading...</p>:cases.length?cases.map((item:any)=><Card key={item.id}><CardContent className="space-y-4 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{item.case_number}</p><p className="text-sm text-muted-foreground">Received {new Date(item.received_at).toLocaleString()} · {item.claimant_name} · {item.claimant_email}</p></div><Badge>{item.status}</Badge></div><div className="grid gap-3 text-sm md:grid-cols-2"><p><strong>Claimed work:</strong> {item.copyrighted_work}</p><p><strong>Reported material:</strong> {item.material_url}</p><p className="md:col-span-2"><strong>Locator/details:</strong> {item.material_description}</p></div>
      <div className="grid gap-3 md:grid-cols-3"><Field label="Target type" value={targets[item.id]?.type||item.target_type||""} onChange={(value)=>setTargets((c)=>({...c,[item.id]:{...c[item.id],type:value,id:c[item.id]?.id||item.target_id||"",creatorId:c[item.id]?.creatorId||item.creator_id||""}}))}/><Field label="Target UUID" value={targets[item.id]?.id||item.target_id||""} onChange={(value)=>setTargets((c)=>({...c,[item.id]:{...c[item.id],id:value,type:c[item.id]?.type||item.target_type||"",creatorId:c[item.id]?.creatorId||item.creator_id||""}}))}/><Field label="Creator UUID" value={targets[item.id]?.creatorId||item.creator_id||""} onChange={(value)=>setTargets((c)=>({...c,[item.id]:{...c[item.id],creatorId:value,type:c[item.id]?.type||item.target_type||"",id:c[item.id]?.id||item.target_id||""}}))}/></div>
      <div><Label>Internal decision notes</Label><Textarea className="mt-2" value={notes[item.id]||""} onChange={(e)=>setNotes((c)=>({...c,[item.id]:e.target.value}))}/></div>
      <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>update.mutate({id:item.id,status:"needs_information"})}>Request information</Button><Button onClick={()=>update.mutate({id:item.id,status:"access_disabled"})}><ShieldAlert className="mr-2 h-4 w-4"/>Disable access</Button>{item.status==="counter_received"?<Button variant="outline" onClick={()=>restore.mutate(item.id)}>Confirm forwarding & schedule</Button>:null}{item.status==="restoration_scheduled"?<Button onClick={()=>{if(window.confirm("Confirm no qualifying court action or legal hold prevents restoration."))restoreMaterial.mutate(item.id)}}>Restore when eligible</Button>:null}<Button variant="outline" onClick={()=>strike.mutate({id:item.id})}>Issue documented strike</Button><Button variant="ghost" onClick={()=>update.mutate({id:item.id,status:"rejected"})}>Reject notice</Button><Button variant="ghost" onClick={()=>update.mutate({id:item.id,status:"closed"})}>Close</Button></div>
      {item.restore_not_before?<p className="text-xs text-muted-foreground">Recorded restoration window: {item.restore_not_before} through {item.restore_not_after}. Confirm weekends, federal holidays and any court action with counsel before restoration.</p>:null}
    </CardContent></Card>):<Card><CardContent className="p-6 text-sm text-muted-foreground">No copyright cases received.</CardContent></Card>}</section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Rights-audit queue</h2>{audits.length?audits.map((a:any)=><Card key={a.id}><CardContent className="flex flex-wrap justify-between gap-3 p-4"><div><p className="font-medium">{a.selection_reason.replaceAll("_"," ")} · {a.target_type}</p><p className="text-sm text-muted-foreground">Creator {a.creator_id} · due {new Date(a.due_at).toLocaleDateString()}</p></div><Badge variant="outline">{a.status}</Badge></CardContent></Card>):<Card><CardContent className="p-5 text-sm text-muted-foreground">No rights audits are open.</CardContent></Card>}</section>
  </div>;
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <div><Label>{label}</Label><Input className="mt-2" value={value} onChange={(e)=>onChange(e.target.value)}/></div>}
