import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, ArrowLeft, CheckCircle2, Fingerprint, RefreshCw, Search, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { AdminPermissionGuard } from "@/components/auth/AdminPermissionGuard";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { supabase } from "@/integrations/supabase/client";
import { adminService, type AdminCreatorRecord } from "@/services/admin/adminService";

export const Route = createFileRoute("/_authenticated/admin_/fingerprints")({ component: FingerprintOperationsRoute });

type JobRow = { id:string; track_id:string; creator_id:string; status:string; attempt_count:number; processor_version:string|null; queued_at:string; started_at:string|null; completed_at:string|null; last_error:string|null; tracks:{title:string;primary_artist_name:string|null}|null; };
type MatchRow = { id:string; source_track_id:string; candidate_track_id:string; exact_hash_match:boolean; fingerprint_score:number|null; metadata_score:number|null; combined_risk_score:number|null; status:string; reason_codes:string[]; reviewed_at:string|null; created_at:string; };
type FingerprintRow = { track_id:string; creator_id:string; sha256:string; processor_version:string|null; duration_sec:number|null; file_type:string|null; created_at:string; };
type TrackIdentity = { id:string; creator_id:string; title:string; primary_artist_name:string|null; };

function FingerprintOperationsRoute(){return <AdminPermissionGuard anyOf={["admin.rights.read","admin.content.read"]}><FingerprintOperationsPage/></AdminPermissionGuard>;}

function FingerprintOperationsPage(){
 const [jobs,setJobs]=useState<JobRow[]>([]); const [matches,setMatches]=useState<MatchRow[]>([]); const [fingerprints,setFingerprints]=useState<FingerprintRow[]>([]); const [tracks,setTracks]=useState<TrackIdentity[]>([]); const [creators,setCreators]=useState<AdminCreatorRecord[]>([]); const [search,setSearch]=useState(""); const [jobFilter,setJobFilter]=useState("all"); const [loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);try{const database=supabase as any; const [creatorRows,jobResult,matchResult,fingerprintResult,trackResult]=await Promise.all([
  adminService.listCreators(),
  database.from("audio_processing_jobs").select("id,track_id,creator_id,status,attempt_count,processor_version,queued_at,started_at,completed_at,last_error,tracks(title,primary_artist_name)").order("queued_at",{ascending:false}).limit(500),
  database.from("audio_match_candidates").select("id,source_track_id,candidate_track_id,exact_hash_match,fingerprint_score,metadata_score,combined_risk_score,status,reason_codes,reviewed_at,created_at").order("created_at",{ascending:false}).limit(500),
  database.from("audio_fingerprints").select("track_id,creator_id,sha256,processor_version,duration_sec,file_type,created_at").order("created_at",{ascending:false}).limit(500),
  database.from("tracks").select("id,creator_id,title,primary_artist_name").limit(1000),
 ]); const firstError=jobResult.error??matchResult.error??fingerprintResult.error??trackResult.error;if(firstError)throw firstError;setCreators(creatorRows);setJobs((jobResult.data??[]) as JobRow[]);setMatches((matchResult.data??[]) as MatchRow[]);setFingerprints((fingerprintResult.data??[]) as FingerprintRow[]);setTracks((trackResult.data??[]) as TrackIdentity[]);}catch(error){toast.error(error instanceof Error?error.message:"Could not load fingerprint operations");}finally{setLoading(false);}},[]); useEffect(()=>{void load();},[load]);
 const creatorMap=useMemo(()=>new Map(creators.map((x)=>[x.user_id,x])),[creators]); const trackMap=useMemo(()=>new Map(tracks.map((x)=>[x.id,x])),[tracks]);
 const counts=useMemo(()=>jobs.reduce<Record<string,number>>((r,j)=>{r[j.status]=(r[j.status]??0)+1;return r;},{}),[jobs]);
 const processorObserved=jobs.some((j)=>Boolean(j.processor_version)&&["processing","completed","flagged","failed"].includes(j.status))||fingerprints.length>0;
 const filteredJobs=useMemo(()=>{const q=search.trim().toLowerCase();return jobs.filter((j)=>{if(jobFilter!=="all"&&j.status!==jobFilter)return false;if(!q)return true;const creator=creatorMap.get(j.creator_id);return [j.tracks?.title,j.tracks?.primary_artist_name,creator?.creator_name,creator?.display_name,creator?.email,j.status,j.last_error].filter(Boolean).join(" ").toLowerCase().includes(q);});},[jobs,jobFilter,search,creatorMap]);
 return <div className="mx-auto max-w-7xl space-y-6">
  <header><Button variant="ghost" size="sm" asChild><Link to="/admin/rights"><ArrowLeft className="mr-1 h-4 w-4"/>Back to Rights Overview</Link></Button><div className="mt-3 flex items-center gap-2 text-primary"><Fingerprint className="h-5 w-5"/>Rights & Protection</div><div className="mt-2 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-semibold tracking-tight">Fingerprint Processing & Matches</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">Operational visibility for VYBE audio fingerprint jobs, completed fingerprint records, and recording-match candidates. A match is a review signal; it is not by itself a finding of ownership or infringement.</p></div><Button variant="outline" size="icon" onClick={()=>void load()} aria-label="Refresh"><RefreshCw className="h-4 w-4"/></Button></div></header>
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Queued" value={counts.queued??0} icon={Activity}/><Metric label="Skipped" value={counts.skipped??0} icon={ShieldCheck}/><Metric label="Completed" value={counts.completed??0} icon={CheckCircle2}/><Metric label="Fingerprint records" value={fingerprints.length} icon={Fingerprint}/><Metric label="Match candidates" value={matches.length} icon={AlertTriangle}/></div>
  <Card className={processorObserved?"border-primary/30":"border-amber-500/40 bg-amber-500/5"}><CardContent className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">Processor status: {processorObserved?"processor activity observed":"not activated"}</p><p className="mt-1 max-w-3xl text-sm leading-6 text-muted-foreground">{processorObserved?"Fingerprint output exists in the registry. Continue to treat candidate matches as operational review signals.":"The queue and registry are ready for controlled processing, but this screen does not start, retry, backfill, or alter jobs. Processor activation remains a separate deployment step."}</p></div><Badge variant={processorObserved?"secondary":"outline"}>{processorObserved?"Observed":"Safe / read-only"}</Badge></div></CardContent></Card>
  <Card><CardContent className="p-5"><div className="mb-4 flex flex-wrap items-end gap-3"><div className="min-w-[260px] flex-1"><label className="mb-1 block text-xs font-medium text-muted-foreground">Search processing jobs</label><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Song, artist, creator, email, status or error"/></div></div><div><label className="mb-1 block text-xs font-medium text-muted-foreground">Job status</label><select className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={jobFilter} onChange={(e)=>setJobFilter(e.target.value)}><option value="all">All</option><option value="queued">Queued</option><option value="skipped">Skipped</option><option value="processing">Processing</option><option value="completed">Completed</option><option value="flagged">Flagged</option><option value="failed">Failed</option></select></div></div>
   <div className="overflow-x-auto rounded-lg border"><table className="w-full min-w-[1050px] border-collapse text-sm"><thead className="bg-muted/25 text-left text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-3 py-2">Creator</th><th className="px-3 py-2">Track</th><th className="px-3 py-2">Status</th><th className="px-3 py-2">Attempts</th><th className="px-3 py-2">Processor</th><th className="px-3 py-2">Queued</th><th className="px-3 py-2">Result</th></tr></thead><tbody>{filteredJobs.map((j)=>{const creator=creatorMap.get(j.creator_id);return <tr key={j.id} className="border-t align-top hover:bg-muted/20"><td className="px-3 py-3"><p className="font-medium">{creator?.creator_name||creator?.display_name||"Unknown creator"}</p><p className="text-xs text-muted-foreground">{creator?.email||j.creator_id}</p></td><td className="px-3 py-3"><p className="font-medium">{j.tracks?.title||trackMap.get(j.track_id)?.title||"Unavailable track"}</p><p className="text-xs text-muted-foreground">{j.tracks?.primary_artist_name||trackMap.get(j.track_id)?.primary_artist_name||j.track_id}</p></td><td className="px-3 py-3"><StatusBadge status={j.status}/></td><td className="px-3 py-3">{j.attempt_count}</td><td className="px-3 py-3 text-muted-foreground">{j.processor_version||"—"}</td><td className="px-3 py-3 text-muted-foreground">{new Date(j.queued_at).toLocaleString()}</td><td className="px-3 py-3">{j.last_error?<p className="max-w-sm text-xs text-destructive">{j.last_error}</p>:j.completed_at?<span className="text-xs text-muted-foreground">Completed {new Date(j.completed_at).toLocaleString()}</span>:<span className="text-xs text-muted-foreground">Awaiting processor</span>}</td></tr>;})}{!loading&&!filteredJobs.length?<tr><td colSpan={7} className="px-4 py-8 text-center text-muted-foreground">No processing jobs match the current filters.</td></tr>:null}</tbody></table></div>{loading?<p className="mt-4 text-sm text-muted-foreground">Loading fingerprint operations…</p>:null}
  </CardContent></Card>
  <section className="space-y-3"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-semibold">Recording-match candidates</h2><p className="mt-1 text-sm text-muted-foreground">Potential relationships between two VYBE recordings. Resolve authorization and collaboration context before escalating to infringement workflows.</p></div><Badge variant="outline">{matches.length} candidates</Badge></div>{matches.length?matches.map((m)=>{const source=trackMap.get(m.source_track_id);const candidate=trackMap.get(m.candidate_track_id);return <Card key={m.id}><CardContent className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{source?.title||m.source_track_id} ↔ {candidate?.title||m.candidate_track_id}</p><p className="mt-1 text-sm text-muted-foreground">{source?.primary_artist_name||"Source recording"} · {candidate?.primary_artist_name||"Candidate recording"}</p></div><StatusBadge status={m.status}/></div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-4"><Signal label="Exact file hash" value={m.exact_hash_match?"Yes":"No"}/><Signal label="Fingerprint score" value={score(m.fingerprint_score)}/><Signal label="Metadata score" value={score(m.metadata_score)}/><Signal label="Combined risk" value={score(m.combined_risk_score)}/></div>{m.reason_codes?.length?<div className="mt-4 flex flex-wrap gap-2">{m.reason_codes.map((r)=><Badge key={r} variant="secondary">{r.replaceAll("_"," ")}</Badge>)}</div>:null}<p className="mt-4 text-xs text-muted-foreground">Created {new Date(m.created_at).toLocaleString()}{m.reviewed_at?` · reviewed ${new Date(m.reviewed_at).toLocaleString()}`:" · not yet reviewed"}</p></CardContent></Card>;}):<Card><CardContent className="p-7 text-sm text-muted-foreground">No match candidates exist yet. This is expected before the processor begins producing fingerprint comparisons.</CardContent></Card>}</section>
 </div>;
}
function score(value:number|null){if(value===null||value===undefined)return "—";return `${Math.round(Number(value)*100)}%`;}
function Metric({label,value,icon:Icon}:{label:string;value:number;icon:typeof Activity}){return <Card><CardContent className="flex items-center gap-3 p-5"><Icon className="h-5 w-5 text-primary"/><div><p className="text-2xl font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div></CardContent></Card>;}
function Signal({label,value}:{label:string;value:string}){return <div className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div>;}
function StatusBadge({status}:{status:string}){const variant=status==="failed"?"destructive":status==="flagged"?"outline":"secondary";return <Badge variant={variant}>{status.replaceAll("_"," ")}</Badge>;}
