import { useEffect, useRef, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, CheckCircle2, Circle, ExternalLink, GraduationCap, RotateCcw, Sparkles } from "lucide-react";
import { RoleGuard } from "@/components/auth/RoleGuard";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { effectivePublicPlan } from "@/features/membership/access";
import type { PublicCreatorPlanCode } from "@/features/membership/catalog";
import { useMembership } from "@/hooks/useMembership";
import { useUser } from "@/hooks/useUser";
import { openCreatorAcademyCoach } from "@/components/academy/CreatorAcademyCoach";

export const Route = createFileRoute("/_authenticated/creator-academy/nova")({
  component: () => <RoleGuard allow={["creator", "admin"]}><NovaCreatorAcademy /></RoleGuard>,
});

type Phase = { plan: PublicCreatorPlanCode; title: string; promise: string; ending: string; next?: string };
type Lesson = { number: number; phase: PublicCreatorPlanCode; title: string; location: string; route: string; objective: string; nova: string; meaning: string; tasks: string[]; result: string };

const labels: Record<PublicCreatorPlanCode, string> = {
  creator_free: "Creator Free", creator_plus: "Creator Plus", creator_pro: "Creator Pro", creator_studio: "Creator Studio",
};
const rank: Record<PublicCreatorPlanCode, number> = { creator_free: 0, creator_plus: 1, creator_pro: 2, creator_studio: 3 };
const phases: Phase[] = [
  { plan: "creator_free", title: "Build the public foundation", promise: "Create a recognizable identity, publish authorized music, control how it can be heard, and share a useful first playlist.", ending: "Creator Free features end here. You now have a complete public foundation.", next: "Creator Plus includes everything you just built, then adds enhanced presentation, advanced music organization, video, written content, protected playlists, EPK Lite, and broader merch preparation." },
  { plan: "creator_plus", title: "Add context and stronger presentation", promise: "Organize the catalog, add visual and written context, and give supporters more reasons to stay connected.", ending: "Creator Plus features end here. Your profile now explains more than the music alone.", next: "Creator Pro includes every Free and Plus feature, then adds a full creator website, advanced access controls, full EPK tools, deeper reporting, commerce readiness, and professional networking." },
  { plan: "creator_pro", title: "Operate a professional creator presence", promise: "Build press, partner, audience, access, analytics, and commerce workflows around the catalog.", ending: "Creator Pro features end here. You now have a professional public and business-facing system.", next: "Creator Studio includes everything in Free, Plus, and Pro, then adds team operations, larger catalogs, multiple EPKs, approval workflows, and advanced protected sharing and reporting." },
  { plan: "creator_studio", title: "Run the complete creator operation", promise: "Coordinate people, catalog, publishing, campaigns, protected delivery, EPKs, commerce, and reporting.", ending: "Creator Studio curriculum complete. Nova's account now demonstrates the full VYBE creator workflow." },
];

const lessons: Lesson[] = [
  { number: 1, phase: "creator_free", title: "Start with rights and creator rules", location: "Creator Rules", route: "/creator-compliance", objective: "Confirm what Nova owns, what she is authorized to upload, and how AI-assisted work is disclosed.", nova: "Nova identifies the real people behind the project, credits Jerzo and C. Blount where applicable, and clearly describes Nova as an AI-created persona guided by a real writer.", meaning: "Rights are the foundation of every upload, share, sale, pitch, and public claim.", tasks: ["Read the creator and upload rules.", "Confirm ownership or authorization for every source file.", "Write a consistent AI-transparency statement.", "Keep contributor names and agreements ready before uploading."], result: "A rights-ready creator account with truthful, repeatable disclosures." },
  { number: 2, phase: "creator_free", title: "Choose the name, VYBE tag, and creator focus", location: "Public Profile & Discovery", route: "/profile", objective: "Make Nova identifiable and searchable before adding decoration.", nova: "Nova Vale is the artist name; @novavale is the memorable tag; Country Soul, blues-rooted writing, poetry, and AI-assisted storytelling define the focus.", meaning: "A stable name and tag make every future link, credit, playlist, and mention easier to recognize.", tasks: ["Choose a durable artist name.", "Claim a short, readable VYBE tag.", "Select accurate creator focuses and genres.", "Use the same naming across credits and links."], result: "A clear creator identity that can anchor the rest of the account." },
  { number: 3, phase: "creator_free", title: "Build the profile image and standard banner", location: "Public Profile & Discovery", route: "/profile", objective: "Use the profile image for recognition and the banner for the larger brand story.", nova: "Nova's close portrait remains readable at small sizes. Her banner uses the wider soul-country visual world without repeating tiny text.", meaning: "The avatar travels across VYBE; the banner establishes atmosphere when someone reaches the full profile.", tasks: ["Upload a square, face-forward profile image.", "Upload a wide standard banner with a safe center crop.", "Preview both on mobile and desktop.", "Avoid important text near banner edges."], result: "A professional identity that stays recognizable in cards and full profiles." },
  { number: 4, phase: "creator_free", title: "Write a useful biography and discovery details", location: "Public Profile & Discovery", route: "/profile", objective: "Turn Nova's history into a concise story supporters and search tools can understand.", nova: "Born in New Orleans, raised through New York and Florida, reshaped by New Jersey and Texas, Nova returns to poetry and song after motherhood and creates an AI alter ego for the voice she never lost.", meaning: "A strong bio combines origin, sound, present purpose, and a reason to keep listening—not a list of vague adjectives.", tasks: ["Open with the clearest one-sentence identity.", "Add the life journey that shaped the work.", "Name the sound and creative method honestly.", "Add location, genres, links, and searchable specifics."], result: "A human, searchable story that gives the catalog meaning." },
  { number: 5, phase: "creator_free", title: "Upload and credit the first song", location: "Upload Music", route: "/music/upload", objective: "Publish a clean master record for Rise Together.", nova: "Rise Together becomes the lead song with an accurate title, cover, writers and contributors, rights confirmation, genre, and release context.", meaning: "Correct metadata protects identity and prevents the same song from becoming fragmented across pages, playlists, and reports.", tasks: ["Upload the authorized audio file.", "Add cover art and an exact title.", "Enter writers, performers, producers, and contributors.", "Confirm rights and save before moving on."], result: "One reliable song record that can safely travel through VYBE." },
  { number: 6, phase: "creator_free", title: "Control each song's visibility and listening position", location: "Music Library", route: "/music", objective: "Choose who can find a song, how much they can hear, and what role it plays.", nova: "Rise Together is public and leads the profile. Safe With Me demonstrates a public preview. Other songs can be unlisted for direct sharing or private while unfinished.", meaning: "Public affects discovery; unlisted supports link-only sharing; private protects work in progress. Preview, follower, member, and full-song playback answer a separate question: how much can this audience hear?",
    tasks: ["Choose Public, Unlisted, or Private for each song.", "Choose preview, follower, member, or full-song playback where available.", "Set the strongest public introduction as the profile lead.", "Test the song as a signed-out visitor and a supporter."], result: "A catalog whose access settings match the purpose of every track." },
  { number: 7, phase: "creator_free", title: "Create the first playlist and launch the Free foundation", location: "Playlists", route: "/playlists", objective: "Turn individual songs into a guided first listening path.", nova: "Start Here: Nova Vale introduces three songs in a deliberate order and gives the playlist a clear description and shareable public link.", meaning: "A playlist reduces decision fatigue and lets the creator frame the first listening experience.", tasks: ["Create a short introductory playlist.", "Order songs intentionally.", "Add a useful title, description, and cover.", "Open the public link on mobile before sharing."], result: "A complete Creator Free launch: identity, story, music, access, and one shareable path." },

  { number: 8, phase: "creator_plus", title: "Upgrade the profile showcase", location: "Public Profile & Discovery", route: "/profile", objective: "Use the stronger Plus presentation to direct attention instead of adding clutter.", nova: "Nova highlights her lead work, strongest links, and the next action a supporter should take.", meaning: "Enhanced presentation is valuable when it creates hierarchy: what to notice first, what to play next, and where to go afterward.", tasks: ["Choose the strongest showcase items.", "Prioritize links by supporter value.", "Remove competing calls to action.", "Review the profile as a first-time visitor."], result: "A profile that guides attention rather than simply holding information." },
  { number: 9, phase: "creator_plus", title: "Organize music by category and production stage", location: "Music Library", route: "/music", objective: "Use advanced organization to manage why a song exists and where it is in the workflow.", nova: "Nova marks released masters separately from demos, works in progress, sync candidates, and archive material.", meaning: "Music category groups the business or creative purpose of a song. Production stage tracks readiness. Neither setting makes a song public or changes playback access; visibility and listening controls do that.", tasks: ["Assign an honest music category.", "Set the current production stage.", "Separate finished releases from demos and works in progress.", "Use consistent terms so the catalog can be filtered later."], result: "A catalog that supports creative decisions, pitching, production, and team handoffs." },
  { number: 10, phase: "creator_plus", title: "Add video that supports a release", location: "Video Library", route: "/videos", objective: "Use visual media to deepen the song story.", nova: "Behind Rise Together contains clearly labeled AI-generated studio clips and explains why they belong with the release.", meaning: "Video works best when it adds context—performance, process, interview, trailer, or behind-the-scenes—not when it repeats the cover art.", tasks: ["Choose a video with a defined purpose.", "Add an accurate title and disclosure.", "Connect it to the relevant song or story.", "Set visibility and test playback."], result: "A visual layer that makes the release more memorable and transparent." },
  { number: 11, phase: "creator_plus", title: "Publish stories, poetry, and release context", location: "Create & Manage", route: "/content", objective: "Give Nova's writing a home beside the music.", nova: "The Woman in the Mirror Has Lived, What My Children Didn't Know, and The Dream Didn't Die connect her poetry, motherhood, and return to creativity.", meaning: "Written content creates search context, emotional continuity, and material that can support releases between music drops.", tasks: ["Choose the right format for each piece.", "Write a clear title and introduction.", "Credit source material and collaborators.", "Schedule or publish in a useful sequence."], result: "A creator story that continues even when no new song is released." },
  { number: 12, phase: "creator_plus", title: "Design protected and follower listening paths", location: "Playlists", route: "/playlists", objective: "Match playlist access to the relationship being built.", nova: "Nova keeps Start Here public, creates a follower path for returning supporters, and uses protected sharing for selected previews.", meaning: "Different playlists can acquire new listeners, reward followers, support members, or deliver private work without exposing the entire catalog.", tasks: ["Define one audience goal per playlist.", "Choose public, follower, member, or protected access.", "Confirm every included song permits that audience.", "Explain what the listener receives and why."], result: "Purposeful listening paths instead of duplicate song lists." },
  { number: 13, phase: "creator_plus", title: "Build EPK Lite and prepare the merch story", location: "Industry Kit & EPK", route: "/epk", objective: "Package the essential public facts for people evaluating Nova.", nova: "Nova's short bio, hero image, lead music, selected photos, contact path, and concise project description form the first press-ready kit; merch concepts extend the same visual story.", meaning: "EPK Lite is a focused introduction, not a storage folder. Early merch planning should connect product, audience, pricing, fulfillment, and creator identity.", tasks: ["Choose one strong bio and hero image.", "Add only the most useful music and media.", "Create a clear contact path.", "Document merch concept, audience, costs, and fulfillment before selling."], result: "A concise Plus-level professional introduction and an intentional merch foundation." },

  { number: 14, phase: "creator_pro", title: "Build the full creator website experience", location: "Public Profile & Discovery", route: "/profile", objective: "Turn the profile into a complete public destination.", nova: "Nova's website organizes music, story, video, poetry, playlists, merch, and contact without making visitors hunt.", meaning: "A full creator destination should answer who, what, why now, how to listen, and how to connect in a clear order.", tasks: ["Choose the page hierarchy.", "Use the full background and theme intentionally.", "Place the lead action above secondary sections.", "Test every public section signed out."], result: "A coherent public website rather than disconnected creator tools." },
  { number: 15, phase: "creator_pro", title: "Manage approved listeners and controlled access", location: "Playlists", route: "/playlists", objective: "Share sensitive work with named audiences and retain control.", nova: "Nova sends selected material to approved listeners, tracks access, and can revoke it when the purpose ends.", meaning: "Approved access supports reviewers, collaborators, partners, and early listeners without treating every private share as permanent.", tasks: ["Define who needs access and why.", "Choose the minimum material required.", "Set or review access conditions.", "Audit and revoke access when appropriate."], result: "Professional sharing with accountability and less accidental exposure." },
  { number: 16, phase: "creator_pro", title: "Assemble the full EPK and exports", location: "Industry Kit & EPK", route: "/epk", objective: "Create a deeper package for press, venues, partners, and opportunities.", nova: "Nova adds long and short bios, press photos, music, video, story, credits, milestones, contact details, and audience-ready exports.", meaning: "Different recipients need different levels of detail; a strong EPK is editable, current, and easy to share or export.", tasks: ["Build short and expanded narratives.", "Select press-ready media and credits.", "Add relevant proof, milestones, and contact roles.", "Preview and export before distributing."], result: "A complete opportunity-ready professional kit." },
  { number: 17, phase: "creator_pro", title: "Read advanced insights and export useful reports", location: "Creator Insights", route: "/creator-analytics", objective: "Use audience behavior to decide what to improve next.", nova: "Nova compares profile visits, plays, playlist opens, supporter actions, and content pathways without confusing activity with meaningful growth.", meaning: "Analytics are useful when attached to a question: which entry point works, what keeps attention, and what action follows listening?",
    tasks: ["Choose one decision before reading data.", "Compare related metrics instead of isolated totals.", "Identify a repeatable pattern and a weak point.", "Export or document the finding and next test."], result: "Evidence-based decisions instead of vanity-number chasing." },
  { number: 18, phase: "creator_pro", title: "Prepare commerce and professional networking", location: "Commerce", route: "/commerce", objective: "Connect products, opportunities, and professional relationships to a ready creator operation.", nova: "Nova validates products, pricing, permissions, fulfillment, policies, contact roles, and professional goals before publishing or pitching.", meaning: "Commerce and networking work when the offer, audience, rights, delivery, and response process are clear before promotion begins.", tasks: ["Define the offer and intended supporter or partner.", "Confirm rights, cost, price, and fulfillment.", "Complete professional Creator Mode information.", "Test the inquiry or purchase path end to end."], result: "A Pro-level creator presence prepared for responsible opportunities and sales." },

  { number: 19, phase: "creator_studio", title: "Set team roles and approval workflows", location: "Creator Settings", route: "/settings", objective: "Decide who can prepare, review, approve, and publish work.", nova: "Nova's owner, creative, rights, and release responsibilities are separated so collaborators do not need unrestricted access.", meaning: "Team roles reduce mistakes and make responsibility visible as the operation grows.", tasks: ["List every recurring responsibility.", "Assign the least access each role needs.", "Define review and approval checkpoints.", "Test a draft-to-publish handoff."], result: "A safer, repeatable team workflow." },
  { number: 20, phase: "creator_studio", title: "Scale the catalog and advanced website", location: "Public Profile & Discovery", route: "/profile", objective: "Keep a larger body of work navigable without losing the lead story.", nova: "Nova organizes releases, poetry, visuals, playlists, and campaigns into a clear current focus with accessible archives.", meaning: "More content should create depth, not noise. Studio organization preserves a strong first visit while supporting a larger catalog.", tasks: ["Define current, featured, and archive layers.", "Audit names, covers, credits, and links at scale.", "Keep navigation and calls to action consistent.", "Test mobile performance and public clarity."], result: "A scalable catalog with a controlled public presentation." },
  { number: 21, phase: "creator_studio", title: "Create multiple EPKs for different opportunities", location: "Industry Kit & EPK", route: "/epk", objective: "Match each professional package to its recipient.", nova: "Nova maintains separate kits for press, live opportunities, brand partnerships, and the AI-assisted creative project.", meaning: "A targeted EPK removes irrelevant material and makes the recipient's decision easier.", tasks: ["Define the recipient and desired decision.", "Duplicate only verified core facts.", "Customize media, proof, and call to action.", "Name, version, preview, and retire kits deliberately."], result: "Multiple focused professional packages without conflicting information." },
  { number: 22, phase: "creator_studio", title: "Operate advanced protected delivery", location: "Playlists", route: "/playlists", objective: "Coordinate sensitive media across campaigns, teams, and external reviewers.", nova: "Nova separates internal review, approved partner preview, follower reward, and public launch links while preserving one source of truth.", meaning: "Advanced protected sharing prevents unfinished or restricted media from escaping through copied files and outdated links.", tasks: ["Map each audience and release stage.", "Use the correct protected container and permissions.", "Track versions, recipients, and expiration or revocation.", "Promote the approved version without rebuilding the catalog."], result: "Controlled multi-audience delivery that can survive a real release cycle." },
  { number: 23, phase: "creator_studio", title: "Run the final Studio launch review", location: "Creator Dashboard", route: "/dashboard", objective: "Verify the complete system before a campaign or opportunity goes live.", nova: "Nova reviews rights, team approvals, public identity, catalog status, access, EPKs, content, commerce, supporter paths, analytics, and response ownership.", meaning: "A final operational review catches contradictions that individual feature checks cannot see.", tasks: ["Review the platform as public visitor, supporter, partner, and team member.", "Confirm every asset, permission, credit, price, and link.", "Assign monitoring and response ownership.", "Record the launch baseline and next review date."], result: "A complete Creator Studio operation ready to launch, learn, and improve." },
];

function NovaCreatorAcademy() {
  const { user } = useUser();
  const membership = useMembership();
  const currentPlan = effectivePublicPlan(membership.planCode);
  const storageKey = `vybe:creator-academy:nova:v2:${user?.id ?? "creator"}`;
  const [activeNumber, setActiveNumber] = useState(1);
  const [complete, setComplete] = useState<number[]>([]);
  const lessonTopRef = useRef<HTMLElement | null>(null);
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem(storageKey) || "[]"); if (Array.isArray(saved)) setComplete(saved.filter(Number.isFinite)); } catch { setComplete([]); } }, [storageKey]);
  useEffect(() => { localStorage.setItem(storageKey, JSON.stringify(complete)); }, [complete, storageKey]);
  useEffect(() => {
    lessonTopRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
  }, [activeNumber]);
  const active = lessons.find((lesson) => lesson.number === activeNumber) ?? lessons[0];
  const phase = phases.find((item) => item.plan === active.phase)!;
  const phaseLessons = lessons.filter((lesson) => lesson.phase === active.phase);
  const isPhaseEnd = active.number === phaseLessons[phaseLessons.length - 1]?.number;
  const progress = Math.round((complete.length / lessons.length) * 100);
  const included = rank[active.phase] <= rank[currentPlan];
  const toggle = () => setComplete((value) => value.includes(active.number) ? value.filter((n) => n !== active.number) : [...value, active.number]);
  const move = (delta: number) => setActiveNumber(Math.min(lessons.length, Math.max(1, active.number + delta)));

  return <main className="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6 lg:px-8">
    <section className="overflow-hidden rounded-3xl border border-primary/25 bg-gradient-to-br from-primary/15 via-card to-cyan-500/10 p-6 sm:p-8">
      <div className="flex flex-wrap items-start justify-between gap-5"><div className="max-w-3xl"><Badge className="mb-4 gap-2"><GraduationCap className="h-4 w-4" /> Paid guided curriculum preview</Badge><h1 className="text-3xl font-bold sm:text-5xl">Build a creator account from Free through Studio.</h1><p className="mt-4 text-base leading-7 text-muted-foreground sm:text-lg">Follow Nova Vale through {lessons.length} real setup lessons. Complete the actual work in VYBE, learn what each choice means, and cross each membership boundary only after that phase's working features are complete.</p></div><Button variant="outline" onClick={() => setComplete([])}><RotateCcw className="mr-2 h-4 w-4" />Reset progress</Button></div>
      <div className="mt-7 grid gap-4 md:grid-cols-[1fr_auto]"><div><div className="mb-2 flex justify-between text-sm"><span>{complete.length} of {lessons.length} lessons completed</span><span>{progress}%</span></div><Progress value={progress} /></div><div className="rounded-2xl border border-border bg-background/60 px-4 py-3 text-sm"><span className="text-muted-foreground">Current membership</span><p className="font-semibold">{labels[currentPlan]}</p></div></div>
      <p className="mt-4 text-sm leading-6 text-muted-foreground">The academy teaches the complete path. Your real VYBE controls still enforce your current membership. Payment access for this course will be activated separately; this build keeps testing open.</p>
    </section>

    <div className="grid gap-6 lg:grid-cols-[330px_minmax(0,1fr)]">
      <aside className="space-y-4 lg:sticky lg:top-24 lg:self-start">{phases.map((item) => <Card key={item.plan}><CardContent className="p-4"><div className="mb-3 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">{labels[item.plan]}</p><p className="font-semibold">{item.title}</p></div>{rank[item.plan] <= rank[currentPlan] ? <Badge variant="secondary">Included</Badge> : <Badge variant="outline">Preview</Badge>}</div><div className="space-y-1">{lessons.filter((lesson) => lesson.phase === item.plan).map((lesson) => <button key={lesson.number} onClick={() => setActiveNumber(lesson.number)} className={`flex w-full items-start gap-3 rounded-xl px-3 py-2 text-left text-sm transition ${lesson.number === active.number ? "bg-primary/15 text-foreground" : "hover:bg-muted"}`}>{complete.includes(lesson.number) ? <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-400" /> : <Circle className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" />}<span><span className="mr-2 text-muted-foreground">{lesson.number}.</span>{lesson.title}</span></button>)}</div></CardContent></Card>)}</aside>

      <section ref={lessonTopRef} className="scroll-mt-24 space-y-5">
        {active.number === phaseLessons[0]?.number && <div className="rounded-2xl border border-primary/30 bg-primary/10 p-5"><p className="text-sm font-semibold uppercase tracking-[.18em] text-primary">Beginning {labels[phase.plan]}</p><h2 className="mt-2 text-2xl font-semibold">{phase.title}</h2><p className="mt-2 leading-7 text-muted-foreground">{phase.promise}</p>{phase.plan !== "creator_free" && <p className="mt-3 text-sm font-medium">{labels[phase.plan]} includes every lesson and feature taught in the earlier phases.</p>}</div>}
        <Card><CardContent className="space-y-7 p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-primary">Lesson {active.number} · {labels[active.phase]}</p><h2 className="mt-2 text-3xl font-bold">{active.title}</h2><p className="mt-2 text-sm text-muted-foreground">Work location: {active.location}</p></div><Badge variant={included ? "secondary" : "outline"}>{included ? `Included in ${labels[currentPlan]}` : `${labels[active.phase]} curriculum preview`}</Badge></div>
          <div className="rounded-2xl border border-border bg-muted/30 p-5"><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">Lesson objective</p><p className="mt-2 text-lg leading-8">{active.objective}</p></div>
          <div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-border p-5"><p className="font-semibold">What Nova demonstrates</p><p className="mt-2 leading-7 text-muted-foreground">{active.nova}</p></div><div className="rounded-2xl border border-cyan-400/25 bg-cyan-500/5 p-5"><p className="font-semibold">What this feature means</p><p className="mt-2 leading-7 text-muted-foreground">{active.meaning}</p></div></div>
          <div><h3 className="text-xl font-semibold">Complete the real setup work</h3><ol className="mt-4 space-y-3">{active.tasks.map((task, index) => <li key={task} className="flex gap-3 rounded-xl border border-border p-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary/15 text-sm font-semibold text-primary">{index + 1}</span><span className="leading-7">{task}</span></li>)}</ol></div>
          <div className="rounded-2xl border border-emerald-400/25 bg-emerald-500/5 p-5"><p className="font-semibold text-emerald-300">Lesson result</p><p className="mt-2 leading-7 text-muted-foreground">{active.result}</p></div>
          <div className="flex flex-wrap items-center justify-between gap-3 border-t border-border pt-6"><Button asChild><a href={active.route} onClick={() => openCreatorAcademyCoach({ number: active.number, title: active.title, plan: labels[active.phase], location: active.location, objective: active.objective, meaning: active.meaning, tasks: active.tasks })}>Open {active.location}<ExternalLink className="ml-2 h-4 w-4" /></a></Button><Button variant={complete.includes(active.number) ? "secondary" : "outline"} onClick={toggle}>{complete.includes(active.number) ? <><CheckCircle2 className="mr-2 h-4 w-4" />Completed</> : "Mark lesson complete"}</Button></div>
        </CardContent></Card>

        {isPhaseEnd && <div className="rounded-3xl border border-fuchsia-400/30 bg-gradient-to-br from-fuchsia-500/10 to-cyan-500/10 p-6"><div className="flex gap-3"><Sparkles className="mt-1 h-6 w-6 shrink-0 text-fuchsia-300" /><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-fuchsia-300">Membership boundary</p><h3 className="mt-2 text-2xl font-bold">{phase.ending}</h3>{phase.next && <p className="mt-3 leading-7 text-muted-foreground">{phase.next}</p>}</div></div></div>}
        <div className="flex justify-between gap-3"><Button variant="outline" disabled={active.number === 1} onClick={() => move(-1)}><ArrowLeft className="mr-2 h-4 w-4" />Previous</Button><Button disabled={active.number === lessons.length} onClick={() => move(1)}>{isPhaseEnd && phase.next ? `Begin ${labels[phases[phases.findIndex((item) => item.plan === phase.plan) + 1].plan]}` : "Next lesson"}<ArrowRight className="ml-2 h-4 w-4" /></Button></div>
      </section>
    </div>
  </main>;
}
