import { FormEvent } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { RoleGuard } from "@/components/auth/RoleGuard";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { WorkspacePageHeader } from "@/components/workspace/WorkspacePageHeader";
import { useUser } from "@/hooks/useUser";
import { copyrightComplianceService } from "@/services/compliance/copyrightComplianceService";

export const Route = createFileRoute("/_authenticated/creator-compliance")({ component: () => <RoleGuard allow={["creator","admin"]}><CreatorCompliance /></RoleGuard> });

function CreatorCompliance() {
  const { user } = useUser(); const client=useQueryClient();
  const { data: ready=false }=useQuery({queryKey:["creator-compliance-ready",user?.id],queryFn:()=>copyrightComplianceService.acceptanceReady(user!.id),enabled:!!user});
  const { data: cases=[] }=useQuery({queryKey:["creator-copyright-cases",user?.id],queryFn:()=>copyrightComplianceService.creatorCases(user!.id),enabled:!!user});
  const { data: audits=[] }=useQuery({queryKey:["creator-rights-audits",user?.id],queryFn:copyrightComplianceService.audits,enabled:!!user});
  const accept=useMutation({mutationFn:()=>copyrightComplianceService.accept(navigator.userAgent),onSuccess:async()=>{await client.invalidateQueries({queryKey:["creator-compliance-ready",user?.id]});toast.success("Creator copyright policies accepted.");}});
  return <div className="mx-auto max-w-5xl space-y-5"><WorkspacePageHeader eyebrow="Trust and safety" title="Copyright Center" description="Review upload rules, rights audits and copyright cases connected to your creator account." status={<Badge variant={ready?"default":"outline"}>{ready?"Current":"Action required"}</Badge>} />
    {!ready?<Card><CardContent className="space-y-4 p-5"><h2 className="text-xl font-semibold">Accept the current creator policies</h2><p className="text-sm leading-6 text-muted-foreground">Before uploading new music, read the Creator Upload and Rights Agreement and Repeat Infringer Policy. Your acceptance is versioned and recorded.</p><Label className="flex items-start gap-3 rounded-xl border p-4 text-sm font-normal"><Checkbox id="acceptPolicies" required className="mt-0.5" /><span>I have read and agree to the current <Link to="/copyright" hash="creator-agreement" className="text-primary underline">Creator Upload and Rights Agreement</Link> and <Link to="/copyright" hash="repeat-infringer" className="text-primary underline">Repeat Infringer Policy</Link>. I certify that my uploads and rights information will be accurate.</span></Label><Button onClick={()=>{const box=document.querySelector("#acceptPolicies") as HTMLButtonElement|null;if(box?.getAttribute("data-state")!=="checked")return toast.error("Check the agreement box first.");accept.mutate();}} disabled={accept.isPending}><ShieldCheck className="mr-2 h-4 w-4" />Accept policies</Button></CardContent></Card>:null}
    <section className="space-y-3"><h2 className="text-xl font-semibold">Rights checks</h2>{audits.length?audits.map((audit:any)=><Card key={audit.id}><CardContent className="p-4"><div className="flex justify-between gap-3"><div><p className="font-medium">{audit.selection_reason.replaceAll("_"," ")} review</p><p className="mt-1 text-sm text-muted-foreground">{audit.requested_evidence}</p></div><Badge variant="outline">{audit.status}</Badge></div><p className="mt-3 text-xs text-muted-foreground">Respond by {new Date(audit.due_at).toLocaleDateString()}. Do not place passwords, bank data or Social Security numbers in your response.</p>{["requested","changes_requested"].includes(audit.status)?<AuditResponse auditId={audit.id}/>:audit.creator_response?<p className="mt-3 rounded-lg bg-muted p-3 text-sm">Your response: {audit.creator_response}</p>:null}</CardContent></Card>):<Card><CardContent className="p-5 text-sm text-muted-foreground">No rights checks require your response.</CardContent></Card>}</section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Copyright cases</h2>{cases.length?cases.map((item:any)=><Card key={item.id}><CardContent className="space-y-3 p-4"><div className="flex justify-between gap-3"><div><p className="font-medium">{item.case_number}</p><p className="text-sm text-muted-foreground">{item.material_url}</p></div><Badge>{item.status}</Badge></div>{item.status==="access_disabled"?<CounterForm caseId={item.id}/>:null}</CardContent></Card>):<Card><CardContent className="p-5 text-sm text-muted-foreground">No copyright cases are connected to this account.</CardContent></Card>}</section>
  </div>;
}

function CounterForm({caseId}:{caseId:string}) { const client=useQueryClient(); const submit=useMutation({mutationFn:(values:Record<string,unknown>)=>copyrightComplianceService.submitCounterNotice(caseId,values),onSuccess:async()=>{await client.invalidateQueries({queryKey:["creator-copyright-cases"]});toast.success("Counter-notice submitted.");},onError:(e)=>toast.error(e instanceof Error?e.message:"Could not submit counter-notice.")}); const send=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget);submit.mutate({_name:String(f.get("name")||""),_address:String(f.get("address")||""),_phone:String(f.get("phone")||""),_material:String(f.get("material")||""),_mistake:f.get("mistake")==="on",_jurisdiction:f.get("jurisdiction")==="on",_service:f.get("service")==="on",_signature:String(f.get("signature")||"")});}; return <form onSubmit={send} className="grid gap-3 rounded-xl border p-4"><p className="font-semibold">Submit a counter-notice only if removal resulted from mistake or misidentification</p><Input name="name" required placeholder="Full legal name"/><Input name="address" required placeholder="Physical address"/><Input name="phone" required placeholder="Telephone"/><Textarea name="material" required placeholder="Identify removed material and its former location"/><Check name="mistake" label="Under penalty of perjury, I have a good-faith belief the material was removed or disabled because of mistake or misidentification."/><Check name="jurisdiction" label="I consent to the jurisdiction of the appropriate U.S. Federal District Court as required by 17 U.S.C. §512(g)."/><Check name="service" label="I will accept service of process from the original claimant or their agent."/><Input name="signature" required placeholder="Electronic signature: full legal name"/><Button disabled={submit.isPending}>Submit counter-notice</Button></form>; }
function Check({name,label}:{name:string;label:string}){return <Label className="flex items-start gap-3 text-sm font-normal"><Checkbox name={name} required className="mt-0.5"/><span>{label}</span></Label>;}
function AuditResponse({auditId}:{auditId:string}){const client=useQueryClient();const respond=useMutation({mutationFn:(response:string)=>copyrightComplianceService.respondToAudit(auditId,response),onSuccess:async()=>{await client.invalidateQueries({queryKey:["creator-rights-audits"]});toast.success("Rights-check response submitted.");}});return <form className="mt-3 space-y-2" onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);respond.mutate(String(f.get("response")||""));}}><Textarea name="response" required placeholder="Explain your ownership and list the evidence you can provide. VYBE Support will arrange secure document delivery if needed."/><Button size="sm" disabled={respond.isPending}>Submit response</Button></form>}
