import { useEffect, useState, type ReactNode } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Bell, CalendarDays, Check, Circle, Compass, Gamepad2, Heart, Loader2, Music2, ShoppingBag, UsersRound } from "lucide-react";
import { RoleGuard } from "@/components/auth/RoleGuard";
import { CreatorBrowseGuard } from "@/components/membership/CreatorBrowseGuard";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { WorkspacePageHeader } from "@/components/workspace/WorkspacePageHeader";
import { useUser } from "@/hooks/useUser";
import { publicDiscoveryService, type DiscoveryCreator, type DiscoveryTrack } from "@/services/discovery/publicDiscoveryService";
import { useSupporterProfile } from "@/hooks/useSupporterProfile";
import { useFollowedCreators, useSupporterCreatorNotifications } from "@/hooks/useSupporterNotifications";
import { useQuery } from "@tanstack/react-query";
import { supporterExperienceService } from "@/services/supporter/supporterExperienceService";
import { savedMusicService } from "@/services/engagement/savedMusicService";

export const Route = createFileRoute("/_authenticated/home")({ component: HomePage });

function HomePage() {
  const { user } = useUser();
  const [creators, setCreators] = useState<DiscoveryCreator[]>([]);
  const [tracks, setTracks] = useState<DiscoveryTrack[]>([]);
  const [loading, setLoading] = useState(true);
  const { data: supporterProfile } = useSupporterProfile(user?.id);
  const { data: followedCreators = [] } = useFollowedCreators();
  const { data: creatorUpdates = [] } = useSupporterCreatorNotifications();
  const { data: preferences } = useQuery({ queryKey: ["supporter-home-preferences", user?.id], queryFn: () => supporterExperienceService.preferences(user!.id), enabled: !!user?.id });
  const { data: savedLists = [] } = useQuery({ queryKey: ["supporter-home-saved-music", user?.id], queryFn: () => savedMusicService.lists(), enabled: !!user?.id, retry: false });
  const name = String(user?.user_metadata?.display_name || user?.user_metadata?.name || user?.email?.split("@")[0] || "VYBE member");
  useEffect(() => { publicDiscoveryService.search("", { creatorLimit: 6, trackLimit: 8 }).then((result) => { setCreators(result.creators.slice(0, 6)); setTracks(result.tracks.slice(0, 8)); }).catch(() => { setCreators([]); setTracks([]); }).finally(() => setLoading(false)); }, []);
  const activation = [
    { done: Boolean(supporterProfile?.display_name || supporterProfile?.username), title: "Set up your supporter identity", text: "Add your name, username, photo, or location.", to: "/profile" as const },
    { done: Boolean(preferences?.genres?.length || preferences?.content_types?.length), title: "Tune your interests", text: "Tell VYBE what kinds of creators and experiences you want to discover.", to: "/supporter-interests" as const },
    { done: followedCreators.length > 0, title: "Follow a creator", text: followedCreators.length ? `You follow ${followedCreators.length} creator${followedCreators.length === 1 ? "" : "s"}.` : "Follow at least one creator so new updates have somewhere to land.", to: "/discover" as const },
    { done: savedLists.some((list) => (list.supporter_music_list_items?.length ?? 0) > 0), title: "Save something to My VYBE", text: "Heart a song or save it to a list so you have something personal to return to.", to: "/my-vybe" as const },
  ];
  const activationDone = activation.filter((item) => item.done).length;
  return <RoleGuard allow={["supporter", "creator", "business", "admin"]}><CreatorBrowseGuard><div className="mx-auto max-w-6xl space-y-7">
    <WorkspacePageHeader eyebrow="Your member home" title={`Welcome back, ${name}.`} description="Discover what is happening across VYBE and return to the creators, music, conversations, and experiences that matter to you." status={<Badge variant="secondary">Supporter</Badge>} />
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Quick to="/discover" title="Discover" text="Find creators and music" image="/images/supporter-cards/discover.webp" icon={<Compass />} /><Quick to="/my-vybe" title="My VYBE" text="Open saved music" image="/images/supporter-cards/my-vybe.webp" icon={<Heart />} /><Quick to="/communities" title="Communities" text="Join conversations" image="/images/supporter-cards/community.webp" icon={<UsersRound />} /><Quick to="/events" title="Events" text="See what is happening" image="/images/supporter-cards/events.webp" icon={<CalendarDays />} /></section>
    <Card className="overflow-hidden border-primary/20 bg-gradient-to-br from-primary/15 via-card to-card"><CardContent className="grid gap-6 p-6 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-sm font-semibold text-primary">YOUR VYBE STARTS HERE</p><h2 className="mt-2 text-3xl font-semibold">Find something worth returning to.</h2><p className="mt-3 max-w-2xl text-muted-foreground">Explore creators, play music, save what moves you, and join the conversation around it.</p></div><Button asChild size="lg" className="rounded-full"><Link to="/discover">Start discovering <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></CardContent></Card>
    {activationDone < activation.length ? <Card><CardContent className="p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold text-primary">MAKE VYBE YOURS</p><h2 className="mt-1 text-xl font-semibold">{activationDone} of {activation.length} first steps complete</h2><p className="mt-1 text-sm text-muted-foreground">A few choices make your account more useful every time you return.</p></div></div><div className="mt-4 grid gap-2 md:grid-cols-2">{activation.map((item) => <Link key={item.title} to={item.to} className="flex gap-3 rounded-xl border p-3 transition hover:border-primary/40 hover:bg-muted/30">{item.done ? <Check className="mt-0.5 h-4 w-4 shrink-0 text-emerald-500" /> : <Circle className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" />}<span><span className="block text-sm font-medium">{item.title}</span><span className="mt-0.5 block text-xs leading-5 text-muted-foreground">{item.text}</span></span></Link>)}</div></CardContent></Card> : null}
    {loading ? <div className="flex min-h-40 items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-primary" /></div> : <>
      <section><div className="flex items-end justify-between"><div><p className="text-sm font-medium text-primary">Creators to discover</p><h2 className="mt-1 text-2xl font-semibold">Meet creators across VYBE</h2></div><Button asChild variant="ghost"><Link to="/discover">View all <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{creators.map((creator) => <Link key={creator.user_id} to="/artist/$username" params={{ username: creator.username }} className="flex items-center gap-3 rounded-2xl border bg-card p-4 transition hover:border-primary/40"><Avatar className="h-12 w-12"><AvatarImage src={creator.avatar_url ?? undefined} /><AvatarFallback>{(creator.artist_name || creator.display_name || "V").slice(0,1)}</AvatarFallback></Avatar><span className="min-w-0"><span className="block truncate font-semibold">{creator.artist_name || creator.display_name}</span><span className="block truncate text-xs text-muted-foreground">{creator.genres?.join(", ") || creator.genre || "Independent creator"}</span></span></Link>)}</div></section>
      <section><div className="flex items-end justify-between"><div><p className="text-sm font-medium text-primary">Music across VYBE</p><h2 className="mt-1 text-2xl font-semibold">Press play on something new</h2></div><Button asChild variant="ghost"><Link to="/discover">More music <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div><div className="mt-4 grid gap-3 md:grid-cols-2">{tracks.map((track) => <Link key={track.id} to="/artist/$username" params={{ username: track.creator!.username }} search={{ track: track.id }} hash="music" className="flex items-center gap-3 rounded-2xl border bg-card p-3 transition hover:border-primary/40"><span className="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-muted">{track.cover_url ? <img src={track.cover_url} alt="" className="h-full w-full object-cover" /> : <Music2 className="h-5 w-5" />}</span><span className="min-w-0"><span className="block truncate font-semibold">{track.title}</span><span className="block truncate text-xs text-muted-foreground">{track.primary_artist_name || track.creator?.artist_name}</span></span></Link>)}</div></section>
    </>}
    <section><div className="mb-3"><p className="text-sm font-medium text-primary">Your return points</p><h2 className="mt-1 text-2xl font-semibold">Come back to what matters to you</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><ReturnCard to="/my-vybe" icon={<Bell />} title="From your creators" text={creatorUpdates.length ? `${creatorUpdates.length} recent creator update${creatorUpdates.length === 1 ? "" : "s"} waiting in My VYBE.` : followedCreators.length ? `You follow ${followedCreators.length} creator${followedCreators.length === 1 ? "" : "s"}. Their updates collect in My VYBE.` : "Follow creators and their updates will collect in My VYBE."} action="Open My VYBE" /><ReturnCard to="/events" icon={<CalendarDays />} title="Events" text="See releases, appearances, shows, and other creator events shared on VYBE." action="See events" /><ReturnCard to="/play" icon={<Gamepad2 />} title="Play" text="Jump into VYBE games, creator focus packs, and interactive experiences." action="Open Play" /><ReturnCard to="/discover" icon={<ShoppingBag />} title="Explore more" text="Keep finding creators, music, and new things worth saving for later." action="Keep exploring" /></div></section>
  </div></CreatorBrowseGuard></RoleGuard>;
}
function ReturnCard({ to, icon, title, text, action }: { to: "/my-vybe" | "/events" | "/play" | "/discover"; icon: ReactNode; title: string; text: string; action: string }) { return <Link to={to} className="group rounded-2xl border bg-card p-5 transition hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-elevated"><span className="text-primary [&>svg]:h-5 [&>svg]:w-5">{icon}</span><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p><span className="mt-4 inline-flex items-center text-sm font-medium text-primary">{action}<ArrowRight className="ml-2 h-4 w-4 transition group-hover:translate-x-0.5" /></span></Link>; }
function Quick({ to, title, text, image, icon }: { to: "/discover" | "/my-vybe" | "/communities" | "/events"; title: string; text: string; image: string; icon: ReactNode }) { return <Link to={to} className="group overflow-hidden rounded-2xl border bg-card transition hover:-translate-y-0.5 hover:border-primary/50 hover:shadow-elevated"><span className="relative block aspect-[16/8] overflow-hidden bg-muted"><img src={image} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]" /><span className="absolute inset-0 bg-gradient-to-t from-background/80 via-transparent to-transparent" /><span className="absolute left-3 top-3 flex h-9 w-9 items-center justify-center rounded-full border border-white/15 bg-background/75 text-primary shadow-lg backdrop-blur [&>svg]:h-4 [&>svg]:w-4">{icon}</span></span><span className="block p-4"><span className="block font-semibold">{title}</span><span className="mt-1 block text-xs text-muted-foreground">{text}</span></span></Link>; }
