import { FormEvent, useEffect, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Card,CardContent } from "@/components/ui/card"; import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Textarea } from "@/components/ui/textarea";
export const Route=createFileRoute("/_authenticated/organization")({component:OrganizationWorkspace});
const TYPES=[["music_collective","Music Collective"],["independent_label","Independent Label"],["creative_organization","Creative Organization"],["entertainment_company","Entertainment Company"],["management_company","Management Company"],["production_company","Production Company"],["film_studio","Film Studio"],["podcast_network","Podcast Network"],["creative_agency","Creative Agency"]];
function OrganizationWorkspace(){const [org,setOrg]=useState<any>(null); const [members,setMembers]=useState<any[]>([]); const load=async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data}=await (supabase.from("creator_organizations") as any).select("*").eq("owner_user_id",user.id).maybeSingle();setOrg(data);if(data){const {data:m}=await (supabase.from("creator_organization_members") as any).select("*").eq("organization_id",data.id).order("display_order");setMembers(m||[])}};useEffect(()=>{void load()},[]);
 const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);const {data:{user}}=await supabase.auth.getUser();if(!user)return;const payload={owner_user_id:user.id,creator_type:fd.get("creator_type"),name:fd.get("name"),biography:fd.get("biography"),mission_statement:fd.get("mission_statement")};const q=org?(supabase.from("creator_organizations") as any).update(payload).eq("id",org.id):(supabase.from("creator_organizations") as any).insert(payload);const {error}=await q;if(error)toast.error(error.message);else{toast.success("Organization workspace saved");await load()}};
 const addMember=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!org)return toast.error("Save the organization first");const fd=new FormData(e.currentTarget);const {error}=await (supabase.from("creator_organization_members") as any).insert({organization_id:org.id,name:fd.get("member_name"),role:fd.get("role"),department:fd.get("department"),short_bio:fd.get("short_bio"),featured:fd.get("featured")==="on"});if(error)toast.error(error.message);else{e.currentTarget.reset();await load();toast.success("Roster member added")}};
 return <div className="mx-auto max-w-5xl space-y-8"><header><p className="text-sm font-semibold uppercase tracking-widest text-primary">Creator Studio</p><h1 className="mt-2 text-4xl font-semibold">Organization Workspace</h1><p className="mt-2 text-muted-foreground">Represent multiple creators while preserving each creator's identity and ownership.</p></header><Card><CardContent className="p-6"><form onSubmit={save} className="grid gap-4 md:grid-cols-2"><div><Label>Creator type</Label><select name="creator_type" defaultValue={org?.creator_type||"music_collective"} className="h-10 w-full rounded-md border bg-background px-3">{TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div><Label>Organization name</Label><Input name="name" required defaultValue={org?.name||""}/></div><div className="md:col-span-2"><Label>Biography</Label><Textarea name="biography" defaultValue={org?.biography||""}/></div><div className="md:col-span-2"><Label>Mission statement</Label><Textarea name="mission_statement" defaultValue={org?.mission_statement||""}/></div><Button className="md:col-span-2">Save organization</Button></form></CardContent></Card><Card><CardContent className="p-6"><h2 className="text-2xl font-semibold">Featured Creators and Roster</h2><form onSubmit={addMember} className="mt-5 grid gap-3 md:grid-cols-2"><Input name="member_name" required placeholder="Creator or team member name"/><Input name="role" required placeholder="Role"/><Input name="department" placeholder="Department"/><Input name="short_bio" placeholder="Short description"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="featured"/>Featured creator</label><Button>Add roster member</Button></form><div className="mt-6 grid gap-3 sm:grid-cols-2">{members.map(m=><div key={m.id} className="rounded-xl border p-4"><p className="font-semibold">{m.name}</p><p className="text-sm text-primary">{m.role}{m.featured?" · Featured":""}</p><p className="text-sm text-muted-foreground">{m.department||m.short_bio}</p></div>)}</div></CardContent></Card></div>}

