import { FormEvent,useState } from "react";import{ImagePlus,Loader2,Pencil,Save}from"lucide-react";import{toast}from"sonner";
import{Button}from"@/components/ui/button";import{Input}from"@/components/ui/input";import{Label}from"@/components/ui/label";import{Textarea}from"@/components/ui/textarea";import{Select,SelectContent,SelectItem,SelectTrigger,SelectValue}from"@/components/ui/select";
import{VIDEO_TYPES,type CreatorVideo,type VideoType,type VideoVisibility}from"@/features/video/schema";import{useUpdateVideo}from"@/hooks/useVideos";
export function VideoEditor({creatorId,video}:{creatorId:string;video:CreatorVideo}){const[open,setOpen]=useState(false);const[thumbnail,setThumbnail]=useState<File|null>(null);const[preview,setPreview]=useState(video.thumbnail_url);const[type,setType]=useState<VideoType>(video.video_type);const[visibility,setVisibility]=useState<VideoVisibility>(video.visibility);const[status,setStatus]=useState<"draft"|"published">(video.status==="published"?"published":"draft");const update=useUpdateVideo(creatorId);
const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=new FormData(e.currentTarget);try{await update.mutateAsync({id:video.id,thumbnail,input:{title:String(data.get("title")||""),description:String(data.get("description")||""),videoType:type,sourceUrl:video.provider==="cloudflare_stream"?null:String(data.get("source_url")||""),thumbnailUrl:String(data.get("thumbnail_url")||"")||null,visibility,status}});setOpen(false);setThumbnail(null);toast.success("Video updated");}catch(error){toast.error(error instanceof Error?error.message:"Could not update video");}};
return <div className="mt-3 border-t border-border pt-3"><Button type="button" variant="outline" size="sm" className="w-full" onClick={()=>setOpen(v=>!v)}><Pencil className="mr-2 h-4 w-4"/>{open?"Close editor":"Edit video"}</Button>{open&&<form onSubmit={submit} className="mt-4 space-y-3 rounded-xl bg-muted/35 p-3">
<div><Label>Title</Label><Input name="title" required defaultValue={video.title} className="mt-1"/></div><div><Label>Description</Label><Textarea name="description" defaultValue={video.description} className="mt-1"/></div>
<div className="grid gap-3 sm:grid-cols-2"><div><Label>Video type</Label><Select value={type} onValueChange={v=>setType(v as VideoType)}><SelectTrigger className="mt-1"><SelectValue/></SelectTrigger><SelectContent>{VIDEO_TYPES.map(v=><SelectItem key={v.value} value={v.value}>{v.label}</SelectItem>)}</SelectContent></Select></div><div><Label>Visibility</Label><Select value={visibility} onValueChange={v=>setVisibility(v as VideoVisibility)}><SelectTrigger className="mt-1"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="public">Public</SelectItem><SelectItem value="unlisted">Unlisted</SelectItem><SelectItem value="private">Private</SelectItem></SelectContent></Select></div></div>
{video.provider!=="cloudflare_stream"&&<div><Label>YouTube or Vimeo URL</Label><Input name="source_url" type="url" required defaultValue={video.source_url||""} className="mt-1"/></div>}<div><Label>Thumbnail URL (optional)</Label><Input name="thumbnail_url" type="url" defaultValue={video.thumbnail_path?"":video.thumbnail_url||""} className="mt-1"/></div>
<label className="flex cursor-pointer items-center gap-3 rounded-xl border border-dashed p-3">{preview?<img src={preview} alt="Thumbnail preview" className="h-16 w-28 rounded-lg object-cover"/>:<span className="flex h-16 w-28 items-center justify-center bg-muted"><ImagePlus/></span>}<span className="text-sm">Upload or replace thumbnail<br/><span className="text-muted-foreground">16:9 JPG, PNG, or WebP · 2MB maximum</span></span><input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>{const f=e.target.files?.[0]||null;setThumbnail(f);if(f)setPreview(URL.createObjectURL(f));}}/></label>
<div><Label>Status</Label><Select value={status} onValueChange={v=>setStatus(v as "draft"|"published")}><SelectTrigger className="mt-1"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="draft">Draft</SelectItem><SelectItem value="published">Published</SelectItem></SelectContent></Select></div><Button className="w-full bg-gradient-brand text-white" disabled={update.isPending}>{update.isPending?<Loader2 className="mr-2 animate-spin"/>:<Save className="mr-2"/>}{update.isPending?"Saving…":"Save video"}</Button></form>}</div>}
