/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForWritersPoetsRouteImport } from './routes/for-writers-poets'
import { Route as ForFilmVideoRouteImport } from './routes/for-film-video'
import { Route as ForBusinessesRouteImport } from './routes/for-businesses'
import { Route as ForArtistsRouteImport } from './routes/for-artists'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CreatorRouteImport } from './routes/creator_'
import { Route as CreatorMembershipsRouteImport } from './routes/creator-memberships'
import { Route as CopyrightRouteImport } from './routes/copyright'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideoVideoIdRouteImport } from './routes/video.$videoId'
import { Route as PlaylistSlugRouteImport } from './routes/playlist.$slug'
import { Route as ExperienceWatchRouteImport } from './routes/experience.watch'
import { Route as ExperienceReadRouteImport } from './routes/experience.read'
import { Route as ExperiencePlayRouteImport } from './routes/experience.play'
import { Route as ExperienceListenRouteImport } from './routes/experience.listen'
import { Route as ExperienceEventsRouteImport } from './routes/experience.events'
import { Route as ExperienceCommunitiesRouteImport } from './routes/experience.communities'
import { Route as DemoCreatorRouteImport } from './routes/demo.creator'
import { Route as CreatorUsernameRouteImport } from './routes/creator.$username'
import { Route as CreatorInviteTokenRouteImport } from './routes/creator-invite.$token'
import { Route as CopyrightReportRouteImport } from './routes/copyright_.report'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthRedirectRouteImport } from './routes/auth.redirect'
import { Route as AuthOnboardingRouteImport } from './routes/auth.onboarding'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as ArtistUsernameRouteImport } from './routes/artist.$username'
import { Route as ApiVideoUploadUrlRouteImport } from './routes/api.video-upload-url'
import { Route as ApiSecurePlaylistRouteImport } from './routes/api.secure-playlist'
import { Route as ApiAdminTeamInviteRouteImport } from './routes/api.admin-team-invite'
import { Route as ApiAccountDeletionRouteImport } from './routes/api.account-deletion'
import { Route as AdminInviteTokenRouteImport } from './routes/admin-invite.$token'
import { Route as AuthenticatedWatchRouteImport } from './routes/_authenticated/watch'
import { Route as AuthenticatedVideosRouteImport } from './routes/_authenticated/videos'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReadRouteImport } from './routes/_authenticated/read'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlaylistsRouteImport } from './routes/_authenticated/playlists'
import { Route as AuthenticatedPlayRouteImport } from './routes/_authenticated/play'
import { Route as AuthenticatedMyVybeRouteImport } from './routes/_authenticated/my-vybe'
import { Route as AuthenticatedMusicRouteImport } from './routes/_authenticated/music'
import { Route as AuthenticatedMerchRouteImport } from './routes/_authenticated/merch'
import { Route as AuthenticatedListenRouteImport } from './routes/_authenticated/listen'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedEpkRouteImport } from './routes/_authenticated/epk'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContentRouteImport } from './routes/_authenticated/content'
import { Route as AuthenticatedConnectionsRouteImport } from './routes/_authenticated/connections'
import { Route as AuthenticatedCommunitiesRouteImport } from './routes/_authenticated/communities'
import { Route as AuthenticatedBusinessRouteImport } from './routes/_authenticated/business'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as DemoStorySlugRouteImport } from './routes/demo.story.$slug'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe.webhook'
import { Route as ApiStripePortalRouteImport } from './routes/api.stripe.portal'
import { Route as ApiStripeCheckoutRouteImport } from './routes/api.stripe.checkout'
import { Route as AuthenticatedPlaylistsPlaylistIdRouteImport } from './routes/_authenticated/playlists_.$playlistId'
import { Route as AuthenticatedMusicUploadRouteImport } from './routes/_authenticated/music_.upload'
import { Route as AuthenticatedMusicTrackIdRouteImport } from './routes/_authenticated/music_.$trackId'
import { Route as AuthenticatedAdminWorkQueueRouteImport } from './routes/_authenticated/admin_.work-queue'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin_.team'
import { Route as AuthenticatedAdminSystemHealthRouteImport } from './routes/_authenticated/admin_.system-health'
import { Route as AuthenticatedAdminSearchRouteImport } from './routes/_authenticated/admin_.search'
import { Route as AuthenticatedAdminRightsRouteImport } from './routes/_authenticated/admin_.rights'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin_.reports'
import { Route as AuthenticatedAdminPlayRouteImport } from './routes/_authenticated/admin_.play'
import { Route as AuthenticatedAdminPartnerCenterRouteImport } from './routes/_authenticated/admin_.partner-center'
import { Route as AuthenticatedAdminOffersRouteImport } from './routes/_authenticated/admin_.offers'
import { Route as AuthenticatedAdminMembershipsRouteImport } from './routes/_authenticated/admin_.memberships'
import { Route as AuthenticatedAdminCreatorsRouteImport } from './routes/_authenticated/admin_.creators'
import { Route as AuthenticatedAdminBusinessesRouteImport } from './routes/_authenticated/admin_.businesses'
import { Route as AuthenticatedAdminBusinessPilotRouteImport } from './routes/_authenticated/admin_.business-pilot'
import { Route as AuthenticatedAdminAccountsRouteImport } from './routes/_authenticated/admin_.accounts'
import { Route as ArtistUsernamePlaylistSlugRouteImport } from './routes/artist.$username_.playlist.$slug'
import { Route as AuthenticatedMusicTrackIdLyricsRouteImport } from './routes/_authenticated/music_.$trackId_.lyrics'
import { Route as AuthenticatedAdminCampaignsCampaignIdRouteImport } from './routes/_authenticated/admin_.campaigns_.$campaignId'
import { Route as AuthenticatedAdminCampaignsCampaignIdAnalyticsRouteImport } from './routes/_authenticated/admin_.campaigns_.$campaignId_.analytics'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForWritersPoetsRoute = ForWritersPoetsRouteImport.update({
  id: '/for-writers-poets',
  path: '/for-writers-poets',
  getParentRoute: () => rootRouteImport,
} as any)
const ForFilmVideoRoute = ForFilmVideoRouteImport.update({
  id: '/for-film-video',
  path: '/for-film-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBusinessesRoute = ForBusinessesRouteImport.update({
  id: '/for-businesses',
  path: '/for-businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const ForArtistsRoute = ForArtistsRouteImport.update({
  id: '/for-artists',
  path: '/for-artists',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator_',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorMembershipsRoute = CreatorMembershipsRouteImport.update({
  id: '/creator-memberships',
  path: '/creator-memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightRoute = CopyrightRouteImport.update({
  id: '/copyright',
  path: '/copyright',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoVideoIdRoute = VideoVideoIdRouteImport.update({
  id: '/video/$videoId',
  path: '/video/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistSlugRoute = PlaylistSlugRouteImport.update({
  id: '/playlist/$slug',
  path: '/playlist/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceWatchRoute = ExperienceWatchRouteImport.update({
  id: '/experience/watch',
  path: '/experience/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceReadRoute = ExperienceReadRouteImport.update({
  id: '/experience/read',
  path: '/experience/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencePlayRoute = ExperiencePlayRouteImport.update({
  id: '/experience/play',
  path: '/experience/play',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceListenRoute = ExperienceListenRouteImport.update({
  id: '/experience/listen',
  path: '/experience/listen',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceEventsRoute = ExperienceEventsRouteImport.update({
  id: '/experience/events',
  path: '/experience/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceCommunitiesRoute = ExperienceCommunitiesRouteImport.update({
  id: '/experience/communities',
  path: '/experience/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCreatorRoute = DemoCreatorRouteImport.update({
  id: '/demo/creator',
  path: '/demo/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorUsernameRoute = CreatorUsernameRouteImport.update({
  id: '/creator/$username',
  path: '/creator/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorInviteTokenRoute = CreatorInviteTokenRouteImport.update({
  id: '/creator-invite/$token',
  path: '/creator-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightReportRoute = CopyrightReportRouteImport.update({
  id: '/copyright_/report',
  path: '/copyright/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRedirectRoute = AuthRedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const ArtistUsernameRoute = ArtistUsernameRouteImport.update({
  id: '/artist/$username',
  path: '/artist/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoUploadUrlRoute = ApiVideoUploadUrlRouteImport.update({
  id: '/api/video-upload-url',
  path: '/api/video-upload-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSecurePlaylistRoute = ApiSecurePlaylistRouteImport.update({
  id: '/api/secure-playlist',
  path: '/api/secure-playlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTeamInviteRoute = ApiAdminTeamInviteRouteImport.update({
  id: '/api/admin-team-invite',
  path: '/api/admin-team-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountDeletionRoute = ApiAccountDeletionRouteImport.update({
  id: '/api/account-deletion',
  path: '/api/account-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInviteTokenRoute = AdminInviteTokenRouteImport.update({
  id: '/admin-invite/$token',
  path: '/admin-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWatchRoute = AuthenticatedWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVideosRoute = AuthenticatedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReadRoute = AuthenticatedReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaylistsRoute = AuthenticatedPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayRoute = AuthenticatedPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyVybeRoute = AuthenticatedMyVybeRouteImport.update({
  id: '/my-vybe',
  path: '/my-vybe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMusicRoute = AuthenticatedMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMerchRoute = AuthenticatedMerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListenRoute = AuthenticatedListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEpkRoute = AuthenticatedEpkRouteImport.update({
  id: '/epk',
  path: '/epk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContentRoute = AuthenticatedContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConnectionsRoute =
  AuthenticatedConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommunitiesRoute =
  AuthenticatedCommunitiesRouteImport.update({
    id: '/communities',
    path: '/communities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessRoute = AuthenticatedBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DemoStorySlugRoute = DemoStorySlugRouteImport.update({
  id: '/demo/story/$slug',
  path: '/demo/story/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripePortalRoute = ApiStripePortalRouteImport.update({
  id: '/api/stripe/portal',
  path: '/api/stripe/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeCheckoutRoute = ApiStripeCheckoutRouteImport.update({
  id: '/api/stripe/checkout',
  path: '/api/stripe/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlaylistsPlaylistIdRoute =
  AuthenticatedPlaylistsPlaylistIdRouteImport.update({
    id: '/playlists_/$playlistId',
    path: '/playlists/$playlistId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMusicUploadRoute =
  AuthenticatedMusicUploadRouteImport.update({
    id: '/music_/upload',
    path: '/music/upload',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMusicTrackIdRoute =
  AuthenticatedMusicTrackIdRouteImport.update({
    id: '/music_/$trackId',
    path: '/music/$trackId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminWorkQueueRoute =
  AuthenticatedAdminWorkQueueRouteImport.update({
    id: '/admin_/work-queue',
    path: '/admin/work-queue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/admin_/team',
  path: '/admin/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSystemHealthRoute =
  AuthenticatedAdminSystemHealthRouteImport.update({
    id: '/admin_/system-health',
    path: '/admin/system-health',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSearchRoute =
  AuthenticatedAdminSearchRouteImport.update({
    id: '/admin_/search',
    path: '/admin/search',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRightsRoute =
  AuthenticatedAdminRightsRouteImport.update({
    id: '/admin_/rights',
    path: '/admin/rights',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin_/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPlayRoute = AuthenticatedAdminPlayRouteImport.update({
  id: '/admin_/play',
  path: '/admin/play',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPartnerCenterRoute =
  AuthenticatedAdminPartnerCenterRouteImport.update({
    id: '/admin_/partner-center',
    path: '/admin/partner-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOffersRoute =
  AuthenticatedAdminOffersRouteImport.update({
    id: '/admin_/offers',
    path: '/admin/offers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMembershipsRoute =
  AuthenticatedAdminMembershipsRouteImport.update({
    id: '/admin_/memberships',
    path: '/admin/memberships',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCreatorsRoute =
  AuthenticatedAdminCreatorsRouteImport.update({
    id: '/admin_/creators',
    path: '/admin/creators',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBusinessesRoute =
  AuthenticatedAdminBusinessesRouteImport.update({
    id: '/admin_/businesses',
    path: '/admin/businesses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBusinessPilotRoute =
  AuthenticatedAdminBusinessPilotRouteImport.update({
    id: '/admin_/business-pilot',
    path: '/admin/business-pilot',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAccountsRoute =
  AuthenticatedAdminAccountsRouteImport.update({
    id: '/admin_/accounts',
    path: '/admin/accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ArtistUsernamePlaylistSlugRoute =
  ArtistUsernamePlaylistSlugRouteImport.update({
    id: '/artist/$username_/playlist/$slug',
    path: '/artist/$username/playlist/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMusicTrackIdLyricsRoute =
  AuthenticatedMusicTrackIdLyricsRouteImport.update({
    id: '/music_/$trackId_/lyrics',
    path: '/music/$trackId/lyrics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCampaignsCampaignIdRoute =
  AuthenticatedAdminCampaignsCampaignIdRouteImport.update({
    id: '/admin_/campaigns_/$campaignId',
    path: '/admin/campaigns/$campaignId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCampaignsCampaignIdAnalyticsRoute =
  AuthenticatedAdminCampaignsCampaignIdAnalyticsRouteImport.update({
    id: '/admin_/campaigns_/$campaignId_/analytics',
    path: '/admin/campaigns/$campaignId/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/copyright': typeof CopyrightRoute
  '/creator-memberships': typeof CreatorMembershipsRoute
  '/creator': typeof CreatorRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/for-artists': typeof ForArtistsRoute
  '/for-businesses': typeof ForBusinessesRoute
  '/for-film-video': typeof ForFilmVideoRoute
  '/for-writers-poets': typeof ForWritersPoetsRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/business': typeof AuthenticatedBusinessRoute
  '/communities': typeof AuthenticatedCommunitiesRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/content': typeof AuthenticatedContentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/epk': typeof AuthenticatedEpkRoute
  '/events': typeof AuthenticatedEventsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/listen': typeof AuthenticatedListenRoute
  '/merch': typeof AuthenticatedMerchRoute
  '/music': typeof AuthenticatedMusicRoute
  '/my-vybe': typeof AuthenticatedMyVybeRoute
  '/play': typeof AuthenticatedPlayRoute
  '/playlists': typeof AuthenticatedPlaylistsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/read': typeof AuthenticatedReadRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/watch': typeof AuthenticatedWatchRoute
  '/admin-invite/$token': typeof AdminInviteTokenRoute
  '/api/account-deletion': typeof ApiAccountDeletionRoute
  '/api/admin-team-invite': typeof ApiAdminTeamInviteRoute
  '/api/secure-playlist': typeof ApiSecurePlaylistRoute
  '/api/video-upload-url': typeof ApiVideoUploadUrlRoute
  '/artist/$username': typeof ArtistUsernameRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/copyright/report': typeof CopyrightReportRoute
  '/creator-invite/$token': typeof CreatorInviteTokenRoute
  '/creator/$username': typeof CreatorUsernameRoute
  '/demo/creator': typeof DemoCreatorRoute
  '/experience/communities': typeof ExperienceCommunitiesRoute
  '/experience/events': typeof ExperienceEventsRoute
  '/experience/listen': typeof ExperienceListenRoute
  '/experience/play': typeof ExperiencePlayRoute
  '/experience/read': typeof ExperienceReadRoute
  '/experience/watch': typeof ExperienceWatchRoute
  '/playlist/$slug': typeof PlaylistSlugRoute
  '/video/$videoId': typeof VideoVideoIdRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/admin/business-pilot': typeof AuthenticatedAdminBusinessPilotRoute
  '/admin/businesses': typeof AuthenticatedAdminBusinessesRoute
  '/admin/creators': typeof AuthenticatedAdminCreatorsRoute
  '/admin/memberships': typeof AuthenticatedAdminMembershipsRoute
  '/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/admin/partner-center': typeof AuthenticatedAdminPartnerCenterRoute
  '/admin/play': typeof AuthenticatedAdminPlayRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/rights': typeof AuthenticatedAdminRightsRoute
  '/admin/search': typeof AuthenticatedAdminSearchRoute
  '/admin/system-health': typeof AuthenticatedAdminSystemHealthRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/work-queue': typeof AuthenticatedAdminWorkQueueRoute
  '/music/$trackId': typeof AuthenticatedMusicTrackIdRoute
  '/music/upload': typeof AuthenticatedMusicUploadRoute
  '/playlists/$playlistId': typeof AuthenticatedPlaylistsPlaylistIdRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/demo/story/$slug': typeof DemoStorySlugRoute
  '/admin/campaigns/$campaignId': typeof AuthenticatedAdminCampaignsCampaignIdRoute
  '/music/$trackId/lyrics': typeof AuthenticatedMusicTrackIdLyricsRoute
  '/artist/$username/playlist/$slug': typeof ArtistUsernamePlaylistSlugRoute
  '/admin/campaigns/$campaignId/analytics': typeof AuthenticatedAdminCampaignsCampaignIdAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/copyright': typeof CopyrightRoute
  '/creator-memberships': typeof CreatorMembershipsRoute
  '/creator': typeof CreatorRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/for-artists': typeof ForArtistsRoute
  '/for-businesses': typeof ForBusinessesRoute
  '/for-film-video': typeof ForFilmVideoRoute
  '/for-writers-poets': typeof ForWritersPoetsRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/business': typeof AuthenticatedBusinessRoute
  '/communities': typeof AuthenticatedCommunitiesRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/content': typeof AuthenticatedContentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/epk': typeof AuthenticatedEpkRoute
  '/events': typeof AuthenticatedEventsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/listen': typeof AuthenticatedListenRoute
  '/merch': typeof AuthenticatedMerchRoute
  '/music': typeof AuthenticatedMusicRoute
  '/my-vybe': typeof AuthenticatedMyVybeRoute
  '/play': typeof AuthenticatedPlayRoute
  '/playlists': typeof AuthenticatedPlaylistsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/read': typeof AuthenticatedReadRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/watch': typeof AuthenticatedWatchRoute
  '/admin-invite/$token': typeof AdminInviteTokenRoute
  '/api/account-deletion': typeof ApiAccountDeletionRoute
  '/api/admin-team-invite': typeof ApiAdminTeamInviteRoute
  '/api/secure-playlist': typeof ApiSecurePlaylistRoute
  '/api/video-upload-url': typeof ApiVideoUploadUrlRoute
  '/artist/$username': typeof ArtistUsernameRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/copyright/report': typeof CopyrightReportRoute
  '/creator-invite/$token': typeof CreatorInviteTokenRoute
  '/creator/$username': typeof CreatorUsernameRoute
  '/demo/creator': typeof DemoCreatorRoute
  '/experience/communities': typeof ExperienceCommunitiesRoute
  '/experience/events': typeof ExperienceEventsRoute
  '/experience/listen': typeof ExperienceListenRoute
  '/experience/play': typeof ExperiencePlayRoute
  '/experience/read': typeof ExperienceReadRoute
  '/experience/watch': typeof ExperienceWatchRoute
  '/playlist/$slug': typeof PlaylistSlugRoute
  '/video/$videoId': typeof VideoVideoIdRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/admin/business-pilot': typeof AuthenticatedAdminBusinessPilotRoute
  '/admin/businesses': typeof AuthenticatedAdminBusinessesRoute
  '/admin/creators': typeof AuthenticatedAdminCreatorsRoute
  '/admin/memberships': typeof AuthenticatedAdminMembershipsRoute
  '/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/admin/partner-center': typeof AuthenticatedAdminPartnerCenterRoute
  '/admin/play': typeof AuthenticatedAdminPlayRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/rights': typeof AuthenticatedAdminRightsRoute
  '/admin/search': typeof AuthenticatedAdminSearchRoute
  '/admin/system-health': typeof AuthenticatedAdminSystemHealthRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/work-queue': typeof AuthenticatedAdminWorkQueueRoute
  '/music/$trackId': typeof AuthenticatedMusicTrackIdRoute
  '/music/upload': typeof AuthenticatedMusicUploadRoute
  '/playlists/$playlistId': typeof AuthenticatedPlaylistsPlaylistIdRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/demo/story/$slug': typeof DemoStorySlugRoute
  '/admin/campaigns/$campaignId': typeof AuthenticatedAdminCampaignsCampaignIdRoute
  '/music/$trackId/lyrics': typeof AuthenticatedMusicTrackIdLyricsRoute
  '/artist/$username/playlist/$slug': typeof ArtistUsernamePlaylistSlugRoute
  '/admin/campaigns/$campaignId/analytics': typeof AuthenticatedAdminCampaignsCampaignIdAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/copyright': typeof CopyrightRoute
  '/creator-memberships': typeof CreatorMembershipsRoute
  '/creator_': typeof CreatorRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/for-artists': typeof ForArtistsRoute
  '/for-businesses': typeof ForBusinessesRoute
  '/for-film-video': typeof ForFilmVideoRoute
  '/for-writers-poets': typeof ForWritersPoetsRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/business': typeof AuthenticatedBusinessRoute
  '/_authenticated/communities': typeof AuthenticatedCommunitiesRoute
  '/_authenticated/connections': typeof AuthenticatedConnectionsRoute
  '/_authenticated/content': typeof AuthenticatedContentRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/epk': typeof AuthenticatedEpkRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/listen': typeof AuthenticatedListenRoute
  '/_authenticated/merch': typeof AuthenticatedMerchRoute
  '/_authenticated/music': typeof AuthenticatedMusicRoute
  '/_authenticated/my-vybe': typeof AuthenticatedMyVybeRoute
  '/_authenticated/play': typeof AuthenticatedPlayRoute
  '/_authenticated/playlists': typeof AuthenticatedPlaylistsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/read': typeof AuthenticatedReadRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/videos': typeof AuthenticatedVideosRoute
  '/_authenticated/watch': typeof AuthenticatedWatchRoute
  '/admin-invite/$token': typeof AdminInviteTokenRoute
  '/api/account-deletion': typeof ApiAccountDeletionRoute
  '/api/admin-team-invite': typeof ApiAdminTeamInviteRoute
  '/api/secure-playlist': typeof ApiSecurePlaylistRoute
  '/api/video-upload-url': typeof ApiVideoUploadUrlRoute
  '/artist/$username': typeof ArtistUsernameRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/copyright_/report': typeof CopyrightReportRoute
  '/creator-invite/$token': typeof CreatorInviteTokenRoute
  '/creator/$username': typeof CreatorUsernameRoute
  '/demo/creator': typeof DemoCreatorRoute
  '/experience/communities': typeof ExperienceCommunitiesRoute
  '/experience/events': typeof ExperienceEventsRoute
  '/experience/listen': typeof ExperienceListenRoute
  '/experience/play': typeof ExperiencePlayRoute
  '/experience/read': typeof ExperienceReadRoute
  '/experience/watch': typeof ExperienceWatchRoute
  '/playlist/$slug': typeof PlaylistSlugRoute
  '/video/$videoId': typeof VideoVideoIdRoute
  '/_authenticated/admin_/accounts': typeof AuthenticatedAdminAccountsRoute
  '/_authenticated/admin_/business-pilot': typeof AuthenticatedAdminBusinessPilotRoute
  '/_authenticated/admin_/businesses': typeof AuthenticatedAdminBusinessesRoute
  '/_authenticated/admin_/creators': typeof AuthenticatedAdminCreatorsRoute
  '/_authenticated/admin_/memberships': typeof AuthenticatedAdminMembershipsRoute
  '/_authenticated/admin_/offers': typeof AuthenticatedAdminOffersRoute
  '/_authenticated/admin_/partner-center': typeof AuthenticatedAdminPartnerCenterRoute
  '/_authenticated/admin_/play': typeof AuthenticatedAdminPlayRoute
  '/_authenticated/admin_/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin_/rights': typeof AuthenticatedAdminRightsRoute
  '/_authenticated/admin_/search': typeof AuthenticatedAdminSearchRoute
  '/_authenticated/admin_/system-health': typeof AuthenticatedAdminSystemHealthRoute
  '/_authenticated/admin_/team': typeof AuthenticatedAdminTeamRoute
  '/_authenticated/admin_/work-queue': typeof AuthenticatedAdminWorkQueueRoute
  '/_authenticated/music_/$trackId': typeof AuthenticatedMusicTrackIdRoute
  '/_authenticated/music_/upload': typeof AuthenticatedMusicUploadRoute
  '/_authenticated/playlists_/$playlistId': typeof AuthenticatedPlaylistsPlaylistIdRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/demo/story/$slug': typeof DemoStorySlugRoute
  '/_authenticated/admin_/campaigns_/$campaignId': typeof AuthenticatedAdminCampaignsCampaignIdRoute
  '/_authenticated/music_/$trackId_/lyrics': typeof AuthenticatedMusicTrackIdLyricsRoute
  '/artist/$username_/playlist/$slug': typeof ArtistUsernamePlaylistSlugRoute
  '/_authenticated/admin_/campaigns_/$campaignId_/analytics': typeof AuthenticatedAdminCampaignsCampaignIdAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/community-guidelines'
    | '/copyright'
    | '/creator-memberships'
    | '/creator'
    | '/explore'
    | '/faq'
    | '/for-artists'
    | '/for-businesses'
    | '/for-film-video'
    | '/for-writers-poets'
    | '/help'
    | '/privacy'
    | '/terms'
    | '/trust'
    | '/activity'
    | '/admin'
    | '/business'
    | '/communities'
    | '/connections'
    | '/content'
    | '/dashboard'
    | '/discover'
    | '/epk'
    | '/events'
    | '/home'
    | '/listen'
    | '/merch'
    | '/music'
    | '/my-vybe'
    | '/play'
    | '/playlists'
    | '/profile'
    | '/read'
    | '/settings'
    | '/videos'
    | '/watch'
    | '/admin-invite/$token'
    | '/api/account-deletion'
    | '/api/admin-team-invite'
    | '/api/secure-playlist'
    | '/api/video-upload-url'
    | '/artist/$username'
    | '/auth/forgot-password'
    | '/auth/onboarding'
    | '/auth/redirect'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/copyright/report'
    | '/creator-invite/$token'
    | '/creator/$username'
    | '/demo/creator'
    | '/experience/communities'
    | '/experience/events'
    | '/experience/listen'
    | '/experience/play'
    | '/experience/read'
    | '/experience/watch'
    | '/playlist/$slug'
    | '/video/$videoId'
    | '/admin/accounts'
    | '/admin/business-pilot'
    | '/admin/businesses'
    | '/admin/creators'
    | '/admin/memberships'
    | '/admin/offers'
    | '/admin/partner-center'
    | '/admin/play'
    | '/admin/reports'
    | '/admin/rights'
    | '/admin/search'
    | '/admin/system-health'
    | '/admin/team'
    | '/admin/work-queue'
    | '/music/$trackId'
    | '/music/upload'
    | '/playlists/$playlistId'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/api/stripe/webhook'
    | '/demo/story/$slug'
    | '/admin/campaigns/$campaignId'
    | '/music/$trackId/lyrics'
    | '/artist/$username/playlist/$slug'
    | '/admin/campaigns/$campaignId/analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/community-guidelines'
    | '/copyright'
    | '/creator-memberships'
    | '/creator'
    | '/explore'
    | '/faq'
    | '/for-artists'
    | '/for-businesses'
    | '/for-film-video'
    | '/for-writers-poets'
    | '/help'
    | '/privacy'
    | '/terms'
    | '/trust'
    | '/activity'
    | '/admin'
    | '/business'
    | '/communities'
    | '/connections'
    | '/content'
    | '/dashboard'
    | '/discover'
    | '/epk'
    | '/events'
    | '/home'
    | '/listen'
    | '/merch'
    | '/music'
    | '/my-vybe'
    | '/play'
    | '/playlists'
    | '/profile'
    | '/read'
    | '/settings'
    | '/videos'
    | '/watch'
    | '/admin-invite/$token'
    | '/api/account-deletion'
    | '/api/admin-team-invite'
    | '/api/secure-playlist'
    | '/api/video-upload-url'
    | '/artist/$username'
    | '/auth/forgot-password'
    | '/auth/onboarding'
    | '/auth/redirect'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/copyright/report'
    | '/creator-invite/$token'
    | '/creator/$username'
    | '/demo/creator'
    | '/experience/communities'
    | '/experience/events'
    | '/experience/listen'
    | '/experience/play'
    | '/experience/read'
    | '/experience/watch'
    | '/playlist/$slug'
    | '/video/$videoId'
    | '/admin/accounts'
    | '/admin/business-pilot'
    | '/admin/businesses'
    | '/admin/creators'
    | '/admin/memberships'
    | '/admin/offers'
    | '/admin/partner-center'
    | '/admin/play'
    | '/admin/reports'
    | '/admin/rights'
    | '/admin/search'
    | '/admin/system-health'
    | '/admin/team'
    | '/admin/work-queue'
    | '/music/$trackId'
    | '/music/upload'
    | '/playlists/$playlistId'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/api/stripe/webhook'
    | '/demo/story/$slug'
    | '/admin/campaigns/$campaignId'
    | '/music/$trackId/lyrics'
    | '/artist/$username/playlist/$slug'
    | '/admin/campaigns/$campaignId/analytics'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/community-guidelines'
    | '/copyright'
    | '/creator-memberships'
    | '/creator_'
    | '/explore'
    | '/faq'
    | '/for-artists'
    | '/for-businesses'
    | '/for-film-video'
    | '/for-writers-poets'
    | '/help'
    | '/privacy'
    | '/terms'
    | '/trust'
    | '/_authenticated/activity'
    | '/_authenticated/admin'
    | '/_authenticated/business'
    | '/_authenticated/communities'
    | '/_authenticated/connections'
    | '/_authenticated/content'
    | '/_authenticated/dashboard'
    | '/_authenticated/discover'
    | '/_authenticated/epk'
    | '/_authenticated/events'
    | '/_authenticated/home'
    | '/_authenticated/listen'
    | '/_authenticated/merch'
    | '/_authenticated/music'
    | '/_authenticated/my-vybe'
    | '/_authenticated/play'
    | '/_authenticated/playlists'
    | '/_authenticated/profile'
    | '/_authenticated/read'
    | '/_authenticated/settings'
    | '/_authenticated/videos'
    | '/_authenticated/watch'
    | '/admin-invite/$token'
    | '/api/account-deletion'
    | '/api/admin-team-invite'
    | '/api/secure-playlist'
    | '/api/video-upload-url'
    | '/artist/$username'
    | '/auth/forgot-password'
    | '/auth/onboarding'
    | '/auth/redirect'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/copyright_/report'
    | '/creator-invite/$token'
    | '/creator/$username'
    | '/demo/creator'
    | '/experience/communities'
    | '/experience/events'
    | '/experience/listen'
    | '/experience/play'
    | '/experience/read'
    | '/experience/watch'
    | '/playlist/$slug'
    | '/video/$videoId'
    | '/_authenticated/admin_/accounts'
    | '/_authenticated/admin_/business-pilot'
    | '/_authenticated/admin_/businesses'
    | '/_authenticated/admin_/creators'
    | '/_authenticated/admin_/memberships'
    | '/_authenticated/admin_/offers'
    | '/_authenticated/admin_/partner-center'
    | '/_authenticated/admin_/play'
    | '/_authenticated/admin_/reports'
    | '/_authenticated/admin_/rights'
    | '/_authenticated/admin_/search'
    | '/_authenticated/admin_/system-health'
    | '/_authenticated/admin_/team'
    | '/_authenticated/admin_/work-queue'
    | '/_authenticated/music_/$trackId'
    | '/_authenticated/music_/upload'
    | '/_authenticated/playlists_/$playlistId'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/api/stripe/webhook'
    | '/demo/story/$slug'
    | '/_authenticated/admin_/campaigns_/$campaignId'
    | '/_authenticated/music_/$trackId_/lyrics'
    | '/artist/$username_/playlist/$slug'
    | '/_authenticated/admin_/campaigns_/$campaignId_/analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  CopyrightRoute: typeof CopyrightRoute
  CreatorMembershipsRoute: typeof CreatorMembershipsRoute
  CreatorRoute: typeof CreatorRoute
  ExploreRoute: typeof ExploreRoute
  FaqRoute: typeof FaqRoute
  ForArtistsRoute: typeof ForArtistsRoute
  ForBusinessesRoute: typeof ForBusinessesRoute
  ForFilmVideoRoute: typeof ForFilmVideoRoute
  ForWritersPoetsRoute: typeof ForWritersPoetsRoute
  HelpRoute: typeof HelpRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  AdminInviteTokenRoute: typeof AdminInviteTokenRoute
  ApiAccountDeletionRoute: typeof ApiAccountDeletionRoute
  ApiAdminTeamInviteRoute: typeof ApiAdminTeamInviteRoute
  ApiSecurePlaylistRoute: typeof ApiSecurePlaylistRoute
  ApiVideoUploadUrlRoute: typeof ApiVideoUploadUrlRoute
  ArtistUsernameRoute: typeof ArtistUsernameRoute
  CopyrightReportRoute: typeof CopyrightReportRoute
  CreatorInviteTokenRoute: typeof CreatorInviteTokenRoute
  CreatorUsernameRoute: typeof CreatorUsernameRoute
  DemoCreatorRoute: typeof DemoCreatorRoute
  ExperienceCommunitiesRoute: typeof ExperienceCommunitiesRoute
  ExperienceEventsRoute: typeof ExperienceEventsRoute
  ExperienceListenRoute: typeof ExperienceListenRoute
  ExperiencePlayRoute: typeof ExperiencePlayRoute
  ExperienceReadRoute: typeof ExperienceReadRoute
  ExperienceWatchRoute: typeof ExperienceWatchRoute
  PlaylistSlugRoute: typeof PlaylistSlugRoute
  VideoVideoIdRoute: typeof VideoVideoIdRoute
  ApiStripeCheckoutRoute: typeof ApiStripeCheckoutRoute
  ApiStripePortalRoute: typeof ApiStripePortalRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  DemoStorySlugRoute: typeof DemoStorySlugRoute
  ArtistUsernamePlaylistSlugRoute: typeof ArtistUsernamePlaylistSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-writers-poets': {
      id: '/for-writers-poets'
      path: '/for-writers-poets'
      fullPath: '/for-writers-poets'
      preLoaderRoute: typeof ForWritersPoetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-film-video': {
      id: '/for-film-video'
      path: '/for-film-video'
      fullPath: '/for-film-video'
      preLoaderRoute: typeof ForFilmVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-businesses': {
      id: '/for-businesses'
      path: '/for-businesses'
      fullPath: '/for-businesses'
      preLoaderRoute: typeof ForBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-artists': {
      id: '/for-artists'
      path: '/for-artists'
      fullPath: '/for-artists'
      preLoaderRoute: typeof ForArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator_': {
      id: '/creator_'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-memberships': {
      id: '/creator-memberships'
      path: '/creator-memberships'
      fullPath: '/creator-memberships'
      preLoaderRoute: typeof CreatorMembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright': {
      id: '/copyright'
      path: '/copyright'
      fullPath: '/copyright'
      preLoaderRoute: typeof CopyrightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$videoId': {
      id: '/video/$videoId'
      path: '/video/$videoId'
      fullPath: '/video/$videoId'
      preLoaderRoute: typeof VideoVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$slug': {
      id: '/playlist/$slug'
      path: '/playlist/$slug'
      fullPath: '/playlist/$slug'
      preLoaderRoute: typeof PlaylistSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/watch': {
      id: '/experience/watch'
      path: '/experience/watch'
      fullPath: '/experience/watch'
      preLoaderRoute: typeof ExperienceWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/read': {
      id: '/experience/read'
      path: '/experience/read'
      fullPath: '/experience/read'
      preLoaderRoute: typeof ExperienceReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/play': {
      id: '/experience/play'
      path: '/experience/play'
      fullPath: '/experience/play'
      preLoaderRoute: typeof ExperiencePlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/listen': {
      id: '/experience/listen'
      path: '/experience/listen'
      fullPath: '/experience/listen'
      preLoaderRoute: typeof ExperienceListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/events': {
      id: '/experience/events'
      path: '/experience/events'
      fullPath: '/experience/events'
      preLoaderRoute: typeof ExperienceEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/communities': {
      id: '/experience/communities'
      path: '/experience/communities'
      fullPath: '/experience/communities'
      preLoaderRoute: typeof ExperienceCommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/creator': {
      id: '/demo/creator'
      path: '/demo/creator'
      fullPath: '/demo/creator'
      preLoaderRoute: typeof DemoCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/$username': {
      id: '/creator/$username'
      path: '/creator/$username'
      fullPath: '/creator/$username'
      preLoaderRoute: typeof CreatorUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-invite/$token': {
      id: '/creator-invite/$token'
      path: '/creator-invite/$token'
      fullPath: '/creator-invite/$token'
      preLoaderRoute: typeof CreatorInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright_/report': {
      id: '/copyright_/report'
      path: '/copyright/report'
      fullPath: '/copyright/report'
      preLoaderRoute: typeof CopyrightReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/redirect': {
      id: '/auth/redirect'
      path: '/redirect'
      fullPath: '/auth/redirect'
      preLoaderRoute: typeof AuthRedirectRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/onboarding': {
      id: '/auth/onboarding'
      path: '/onboarding'
      fullPath: '/auth/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/artist/$username': {
      id: '/artist/$username'
      path: '/artist/$username'
      fullPath: '/artist/$username'
      preLoaderRoute: typeof ArtistUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-upload-url': {
      id: '/api/video-upload-url'
      path: '/api/video-upload-url'
      fullPath: '/api/video-upload-url'
      preLoaderRoute: typeof ApiVideoUploadUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/secure-playlist': {
      id: '/api/secure-playlist'
      path: '/api/secure-playlist'
      fullPath: '/api/secure-playlist'
      preLoaderRoute: typeof ApiSecurePlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-team-invite': {
      id: '/api/admin-team-invite'
      path: '/api/admin-team-invite'
      fullPath: '/api/admin-team-invite'
      preLoaderRoute: typeof ApiAdminTeamInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account-deletion': {
      id: '/api/account-deletion'
      path: '/api/account-deletion'
      fullPath: '/api/account-deletion'
      preLoaderRoute: typeof ApiAccountDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-invite/$token': {
      id: '/admin-invite/$token'
      path: '/admin-invite/$token'
      fullPath: '/admin-invite/$token'
      preLoaderRoute: typeof AdminInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/watch': {
      id: '/_authenticated/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof AuthenticatedWatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/read': {
      id: '/_authenticated/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof AuthenticatedReadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playlists': {
      id: '/_authenticated/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof AuthenticatedPlaylistsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play': {
      id: '/_authenticated/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AuthenticatedPlayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-vybe': {
      id: '/_authenticated/my-vybe'
      path: '/my-vybe'
      fullPath: '/my-vybe'
      preLoaderRoute: typeof AuthenticatedMyVybeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/music': {
      id: '/_authenticated/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof AuthenticatedMusicRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/merch': {
      id: '/_authenticated/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof AuthenticatedMerchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listen': {
      id: '/_authenticated/listen'
      path: '/listen'
      fullPath: '/listen'
      preLoaderRoute: typeof AuthenticatedListenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/epk': {
      id: '/_authenticated/epk'
      path: '/epk'
      fullPath: '/epk'
      preLoaderRoute: typeof AuthenticatedEpkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content': {
      id: '/_authenticated/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof AuthenticatedContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communities': {
      id: '/_authenticated/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof AuthenticatedCommunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business': {
      id: '/_authenticated/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AuthenticatedBusinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/demo/story/$slug': {
      id: '/demo/story/$slug'
      path: '/demo/story/$slug'
      fullPath: '/demo/story/$slug'
      preLoaderRoute: typeof DemoStorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/portal': {
      id: '/api/stripe/portal'
      path: '/api/stripe/portal'
      fullPath: '/api/stripe/portal'
      preLoaderRoute: typeof ApiStripePortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/checkout': {
      id: '/api/stripe/checkout'
      path: '/api/stripe/checkout'
      fullPath: '/api/stripe/checkout'
      preLoaderRoute: typeof ApiStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/playlists_/$playlistId': {
      id: '/_authenticated/playlists_/$playlistId'
      path: '/playlists/$playlistId'
      fullPath: '/playlists/$playlistId'
      preLoaderRoute: typeof AuthenticatedPlaylistsPlaylistIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/music_/upload': {
      id: '/_authenticated/music_/upload'
      path: '/music/upload'
      fullPath: '/music/upload'
      preLoaderRoute: typeof AuthenticatedMusicUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/music_/$trackId': {
      id: '/_authenticated/music_/$trackId'
      path: '/music/$trackId'
      fullPath: '/music/$trackId'
      preLoaderRoute: typeof AuthenticatedMusicTrackIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/work-queue': {
      id: '/_authenticated/admin_/work-queue'
      path: '/admin/work-queue'
      fullPath: '/admin/work-queue'
      preLoaderRoute: typeof AuthenticatedAdminWorkQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/team': {
      id: '/_authenticated/admin_/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/system-health': {
      id: '/_authenticated/admin_/system-health'
      path: '/admin/system-health'
      fullPath: '/admin/system-health'
      preLoaderRoute: typeof AuthenticatedAdminSystemHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/search': {
      id: '/_authenticated/admin_/search'
      path: '/admin/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AuthenticatedAdminSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/rights': {
      id: '/_authenticated/admin_/rights'
      path: '/admin/rights'
      fullPath: '/admin/rights'
      preLoaderRoute: typeof AuthenticatedAdminRightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/reports': {
      id: '/_authenticated/admin_/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/play': {
      id: '/_authenticated/admin_/play'
      path: '/admin/play'
      fullPath: '/admin/play'
      preLoaderRoute: typeof AuthenticatedAdminPlayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/partner-center': {
      id: '/_authenticated/admin_/partner-center'
      path: '/admin/partner-center'
      fullPath: '/admin/partner-center'
      preLoaderRoute: typeof AuthenticatedAdminPartnerCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/offers': {
      id: '/_authenticated/admin_/offers'
      path: '/admin/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AuthenticatedAdminOffersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/memberships': {
      id: '/_authenticated/admin_/memberships'
      path: '/admin/memberships'
      fullPath: '/admin/memberships'
      preLoaderRoute: typeof AuthenticatedAdminMembershipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/creators': {
      id: '/_authenticated/admin_/creators'
      path: '/admin/creators'
      fullPath: '/admin/creators'
      preLoaderRoute: typeof AuthenticatedAdminCreatorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/businesses': {
      id: '/_authenticated/admin_/businesses'
      path: '/admin/businesses'
      fullPath: '/admin/businesses'
      preLoaderRoute: typeof AuthenticatedAdminBusinessesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/business-pilot': {
      id: '/_authenticated/admin_/business-pilot'
      path: '/admin/business-pilot'
      fullPath: '/admin/business-pilot'
      preLoaderRoute: typeof AuthenticatedAdminBusinessPilotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/accounts': {
      id: '/_authenticated/admin_/accounts'
      path: '/admin/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AuthenticatedAdminAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/artist/$username_/playlist/$slug': {
      id: '/artist/$username_/playlist/$slug'
      path: '/artist/$username/playlist/$slug'
      fullPath: '/artist/$username/playlist/$slug'
      preLoaderRoute: typeof ArtistUsernamePlaylistSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/music_/$trackId_/lyrics': {
      id: '/_authenticated/music_/$trackId_/lyrics'
      path: '/music/$trackId/lyrics'
      fullPath: '/music/$trackId/lyrics'
      preLoaderRoute: typeof AuthenticatedMusicTrackIdLyricsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/campaigns_/$campaignId': {
      id: '/_authenticated/admin_/campaigns_/$campaignId'
      path: '/admin/campaigns/$campaignId'
      fullPath: '/admin/campaigns/$campaignId'
      preLoaderRoute: typeof AuthenticatedAdminCampaignsCampaignIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/campaigns_/$campaignId_/analytics': {
      id: '/_authenticated/admin_/campaigns_/$campaignId_/analytics'
      path: '/admin/campaigns/$campaignId/analytics'
      fullPath: '/admin/campaigns/$campaignId/analytics'
      preLoaderRoute: typeof AuthenticatedAdminCampaignsCampaignIdAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBusinessRoute: typeof AuthenticatedBusinessRoute
  AuthenticatedCommunitiesRoute: typeof AuthenticatedCommunitiesRoute
  AuthenticatedConnectionsRoute: typeof AuthenticatedConnectionsRoute
  AuthenticatedContentRoute: typeof AuthenticatedContentRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedEpkRoute: typeof AuthenticatedEpkRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedListenRoute: typeof AuthenticatedListenRoute
  AuthenticatedMerchRoute: typeof AuthenticatedMerchRoute
  AuthenticatedMusicRoute: typeof AuthenticatedMusicRoute
  AuthenticatedMyVybeRoute: typeof AuthenticatedMyVybeRoute
  AuthenticatedPlayRoute: typeof AuthenticatedPlayRoute
  AuthenticatedPlaylistsRoute: typeof AuthenticatedPlaylistsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReadRoute: typeof AuthenticatedReadRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVideosRoute: typeof AuthenticatedVideosRoute
  AuthenticatedWatchRoute: typeof AuthenticatedWatchRoute
  AuthenticatedAdminAccountsRoute: typeof AuthenticatedAdminAccountsRoute
  AuthenticatedAdminBusinessPilotRoute: typeof AuthenticatedAdminBusinessPilotRoute
  AuthenticatedAdminBusinessesRoute: typeof AuthenticatedAdminBusinessesRoute
  AuthenticatedAdminCreatorsRoute: typeof AuthenticatedAdminCreatorsRoute
  AuthenticatedAdminMembershipsRoute: typeof AuthenticatedAdminMembershipsRoute
  AuthenticatedAdminOffersRoute: typeof AuthenticatedAdminOffersRoute
  AuthenticatedAdminPartnerCenterRoute: typeof AuthenticatedAdminPartnerCenterRoute
  AuthenticatedAdminPlayRoute: typeof AuthenticatedAdminPlayRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminRightsRoute: typeof AuthenticatedAdminRightsRoute
  AuthenticatedAdminSearchRoute: typeof AuthenticatedAdminSearchRoute
  AuthenticatedAdminSystemHealthRoute: typeof AuthenticatedAdminSystemHealthRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminWorkQueueRoute: typeof AuthenticatedAdminWorkQueueRoute
  AuthenticatedMusicTrackIdRoute: typeof AuthenticatedMusicTrackIdRoute
  AuthenticatedMusicUploadRoute: typeof AuthenticatedMusicUploadRoute
  AuthenticatedPlaylistsPlaylistIdRoute: typeof AuthenticatedPlaylistsPlaylistIdRoute
  AuthenticatedAdminCampaignsCampaignIdRoute: typeof AuthenticatedAdminCampaignsCampaignIdRoute
  AuthenticatedMusicTrackIdLyricsRoute: typeof AuthenticatedMusicTrackIdLyricsRoute
  AuthenticatedAdminCampaignsCampaignIdAnalyticsRoute: typeof AuthenticatedAdminCampaignsCampaignIdAnalyticsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBusinessRoute: AuthenticatedBusinessRoute,
  AuthenticatedCommunitiesRoute: AuthenticatedCommunitiesRoute,
  AuthenticatedConnectionsRoute: AuthenticatedConnectionsRoute,
  AuthenticatedContentRoute: AuthenticatedContentRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedEpkRoute: AuthenticatedEpkRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedListenRoute: AuthenticatedListenRoute,
  AuthenticatedMerchRoute: AuthenticatedMerchRoute,
  AuthenticatedMusicRoute: AuthenticatedMusicRoute,
  AuthenticatedMyVybeRoute: AuthenticatedMyVybeRoute,
  AuthenticatedPlayRoute: AuthenticatedPlayRoute,
  AuthenticatedPlaylistsRoute: AuthenticatedPlaylistsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReadRoute: AuthenticatedReadRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVideosRoute: AuthenticatedVideosRoute,
  AuthenticatedWatchRoute: AuthenticatedWatchRoute,
  AuthenticatedAdminAccountsRoute: AuthenticatedAdminAccountsRoute,
  AuthenticatedAdminBusinessPilotRoute: AuthenticatedAdminBusinessPilotRoute,
  AuthenticatedAdminBusinessesRoute: AuthenticatedAdminBusinessesRoute,
  AuthenticatedAdminCreatorsRoute: AuthenticatedAdminCreatorsRoute,
  AuthenticatedAdminMembershipsRoute: AuthenticatedAdminMembershipsRoute,
  AuthenticatedAdminOffersRoute: AuthenticatedAdminOffersRoute,
  AuthenticatedAdminPartnerCenterRoute: AuthenticatedAdminPartnerCenterRoute,
  AuthenticatedAdminPlayRoute: AuthenticatedAdminPlayRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminRightsRoute: AuthenticatedAdminRightsRoute,
  AuthenticatedAdminSearchRoute: AuthenticatedAdminSearchRoute,
  AuthenticatedAdminSystemHealthRoute: AuthenticatedAdminSystemHealthRoute,
  AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
  AuthenticatedAdminWorkQueueRoute: AuthenticatedAdminWorkQueueRoute,
  AuthenticatedMusicTrackIdRoute: AuthenticatedMusicTrackIdRoute,
  AuthenticatedMusicUploadRoute: AuthenticatedMusicUploadRoute,
  AuthenticatedPlaylistsPlaylistIdRoute: AuthenticatedPlaylistsPlaylistIdRoute,
  AuthenticatedAdminCampaignsCampaignIdRoute:
    AuthenticatedAdminCampaignsCampaignIdRoute,
  AuthenticatedMusicTrackIdLyricsRoute: AuthenticatedMusicTrackIdLyricsRoute,
  AuthenticatedAdminCampaignsCampaignIdAnalyticsRoute:
    AuthenticatedAdminCampaignsCampaignIdAnalyticsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthRedirectRoute: typeof AuthRedirectRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthRedirectRoute: AuthRedirectRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  CopyrightRoute: CopyrightRoute,
  CreatorMembershipsRoute: CreatorMembershipsRoute,
  CreatorRoute: CreatorRoute,
  ExploreRoute: ExploreRoute,
  FaqRoute: FaqRoute,
  ForArtistsRoute: ForArtistsRoute,
  ForBusinessesRoute: ForBusinessesRoute,
  ForFilmVideoRoute: ForFilmVideoRoute,
  ForWritersPoetsRoute: ForWritersPoetsRoute,
  HelpRoute: HelpRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  AdminInviteTokenRoute: AdminInviteTokenRoute,
  ApiAccountDeletionRoute: ApiAccountDeletionRoute,
  ApiAdminTeamInviteRoute: ApiAdminTeamInviteRoute,
  ApiSecurePlaylistRoute: ApiSecurePlaylistRoute,
  ApiVideoUploadUrlRoute: ApiVideoUploadUrlRoute,
  ArtistUsernameRoute: ArtistUsernameRoute,
  CopyrightReportRoute: CopyrightReportRoute,
  CreatorInviteTokenRoute: CreatorInviteTokenRoute,
  CreatorUsernameRoute: CreatorUsernameRoute,
  DemoCreatorRoute: DemoCreatorRoute,
  ExperienceCommunitiesRoute: ExperienceCommunitiesRoute,
  ExperienceEventsRoute: ExperienceEventsRoute,
  ExperienceListenRoute: ExperienceListenRoute,
  ExperiencePlayRoute: ExperiencePlayRoute,
  ExperienceReadRoute: ExperienceReadRoute,
  ExperienceWatchRoute: ExperienceWatchRoute,
  PlaylistSlugRoute: PlaylistSlugRoute,
  VideoVideoIdRoute: VideoVideoIdRoute,
  ApiStripeCheckoutRoute: ApiStripeCheckoutRoute,
  ApiStripePortalRoute: ApiStripePortalRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  DemoStorySlugRoute: DemoStorySlugRoute,
  ArtistUsernamePlaylistSlugRoute: ArtistUsernamePlaylistSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
