/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForWritersPoetsRouteImport } from './routes/for-writers-poets'
import { Route as ForFilmVideoRouteImport } from './routes/for-film-video'
import { Route as ForBusinessesRouteImport } from './routes/for-businesses'
import { Route as ForArtistsRouteImport } from './routes/for-artists'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CopyrightRouteImport } from './routes/copyright'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistSlugRouteImport } from './routes/playlist.$slug'
import { Route as ExperienceWatchRouteImport } from './routes/experience.watch'
import { Route as ExperienceReadRouteImport } from './routes/experience.read'
import { Route as ExperiencePlayRouteImport } from './routes/experience.play'
import { Route as ExperienceListenRouteImport } from './routes/experience.listen'
import { Route as ExperienceEventsRouteImport } from './routes/experience.events'
import { Route as ExperienceCommunitiesRouteImport } from './routes/experience.communities'
import { Route as CreatorUsernameRouteImport } from './routes/creator.$username'
import { Route as CreatorInviteTokenRouteImport } from './routes/creator-invite.$token'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthRedirectRouteImport } from './routes/auth.redirect'
import { Route as AuthOnboardingRouteImport } from './routes/auth.onboarding'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as ArtistUsernameRouteImport } from './routes/artist.$username'
import { Route as AuthenticatedWatchRouteImport } from './routes/_authenticated/watch'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReadRouteImport } from './routes/_authenticated/read'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlaylistsRouteImport } from './routes/_authenticated/playlists'
import { Route as AuthenticatedPlayRouteImport } from './routes/_authenticated/play'
import { Route as AuthenticatedMyVybeRouteImport } from './routes/_authenticated/my-vybe'
import { Route as AuthenticatedMusicRouteImport } from './routes/_authenticated/music'
import { Route as AuthenticatedMerchRouteImport } from './routes/_authenticated/merch'
import { Route as AuthenticatedListenRouteImport } from './routes/_authenticated/listen'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContentRouteImport } from './routes/_authenticated/content'
import { Route as AuthenticatedConnectionsRouteImport } from './routes/_authenticated/connections'
import { Route as AuthenticatedCommunitiesRouteImport } from './routes/_authenticated/communities'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedPlaylistsPlaylistIdRouteImport } from './routes/_authenticated/playlists_.$playlistId'
import { Route as AuthenticatedMusicUploadRouteImport } from './routes/_authenticated/music_.upload'
import { Route as AuthenticatedMusicTrackIdRouteImport } from './routes/_authenticated/music_.$trackId'
import { Route as ArtistUsernamePlaylistSlugRouteImport } from './routes/artist.$username_.playlist.$slug'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForWritersPoetsRoute = ForWritersPoetsRouteImport.update({
  id: '/for-writers-poets',
  path: '/for-writers-poets',
  getParentRoute: () => rootRouteImport,
} as any)
const ForFilmVideoRoute = ForFilmVideoRouteImport.update({
  id: '/for-film-video',
  path: '/for-film-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBusinessesRoute = ForBusinessesRouteImport.update({
  id: '/for-businesses',
  path: '/for-businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const ForArtistsRoute = ForArtistsRouteImport.update({
  id: '/for-artists',
  path: '/for-artists',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightRoute = CopyrightRouteImport.update({
  id: '/copyright',
  path: '/copyright',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistSlugRoute = PlaylistSlugRouteImport.update({
  id: '/playlist/$slug',
  path: '/playlist/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceWatchRoute = ExperienceWatchRouteImport.update({
  id: '/experience/watch',
  path: '/experience/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceReadRoute = ExperienceReadRouteImport.update({
  id: '/experience/read',
  path: '/experience/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencePlayRoute = ExperiencePlayRouteImport.update({
  id: '/experience/play',
  path: '/experience/play',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceListenRoute = ExperienceListenRouteImport.update({
  id: '/experience/listen',
  path: '/experience/listen',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceEventsRoute = ExperienceEventsRouteImport.update({
  id: '/experience/events',
  path: '/experience/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceCommunitiesRoute = ExperienceCommunitiesRouteImport.update({
  id: '/experience/communities',
  path: '/experience/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorUsernameRoute = CreatorUsernameRouteImport.update({
  id: '/creator/$username',
  path: '/creator/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorInviteTokenRoute = CreatorInviteTokenRouteImport.update({
  id: '/creator-invite/$token',
  path: '/creator-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRedirectRoute = AuthRedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const ArtistUsernameRoute = ArtistUsernameRouteImport.update({
  id: '/artist/$username',
  path: '/artist/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWatchRoute = AuthenticatedWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReadRoute = AuthenticatedReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaylistsRoute = AuthenticatedPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayRoute = AuthenticatedPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyVybeRoute = AuthenticatedMyVybeRouteImport.update({
  id: '/my-vybe',
  path: '/my-vybe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMusicRoute = AuthenticatedMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMerchRoute = AuthenticatedMerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListenRoute = AuthenticatedListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContentRoute = AuthenticatedContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConnectionsRoute =
  AuthenticatedConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommunitiesRoute =
  AuthenticatedCommunitiesRouteImport.update({
    id: '/communities',
    path: '/communities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaylistsPlaylistIdRoute =
  AuthenticatedPlaylistsPlaylistIdRouteImport.update({
    id: '/playlists_/$playlistId',
    path: '/playlists/$playlistId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMusicUploadRoute =
  AuthenticatedMusicUploadRouteImport.update({
    id: '/music_/upload',
    path: '/music/upload',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMusicTrackIdRoute =
  AuthenticatedMusicTrackIdRouteImport.update({
    id: '/music_/$trackId',
    path: '/music/$trackId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ArtistUsernamePlaylistSlugRoute =
  ArtistUsernamePlaylistSlugRouteImport.update({
    id: '/artist/$username_/playlist/$slug',
    path: '/artist/$username/playlist/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/copyright': typeof CopyrightRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/for-artists': typeof ForArtistsRoute
  '/for-businesses': typeof ForBusinessesRoute
  '/for-film-video': typeof ForFilmVideoRoute
  '/for-writers-poets': typeof ForWritersPoetsRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/communities': typeof AuthenticatedCommunitiesRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/content': typeof AuthenticatedContentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/events': typeof AuthenticatedEventsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/listen': typeof AuthenticatedListenRoute
  '/merch': typeof AuthenticatedMerchRoute
  '/music': typeof AuthenticatedMusicRoute
  '/my-vybe': typeof AuthenticatedMyVybeRoute
  '/play': typeof AuthenticatedPlayRoute
  '/playlists': typeof AuthenticatedPlaylistsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/read': typeof AuthenticatedReadRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/watch': typeof AuthenticatedWatchRoute
  '/artist/$username': typeof ArtistUsernameRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/creator-invite/$token': typeof CreatorInviteTokenRoute
  '/creator/$username': typeof CreatorUsernameRoute
  '/experience/communities': typeof ExperienceCommunitiesRoute
  '/experience/events': typeof ExperienceEventsRoute
  '/experience/listen': typeof ExperienceListenRoute
  '/experience/play': typeof ExperiencePlayRoute
  '/experience/read': typeof ExperienceReadRoute
  '/experience/watch': typeof ExperienceWatchRoute
  '/playlist/$slug': typeof PlaylistSlugRoute
  '/music/$trackId': typeof AuthenticatedMusicTrackIdRoute
  '/music/upload': typeof AuthenticatedMusicUploadRoute
  '/playlists/$playlistId': typeof AuthenticatedPlaylistsPlaylistIdRoute
  '/artist/$username/playlist/$slug': typeof ArtistUsernamePlaylistSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/copyright': typeof CopyrightRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/for-artists': typeof ForArtistsRoute
  '/for-businesses': typeof ForBusinessesRoute
  '/for-film-video': typeof ForFilmVideoRoute
  '/for-writers-poets': typeof ForWritersPoetsRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/communities': typeof AuthenticatedCommunitiesRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/content': typeof AuthenticatedContentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/events': typeof AuthenticatedEventsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/listen': typeof AuthenticatedListenRoute
  '/merch': typeof AuthenticatedMerchRoute
  '/music': typeof AuthenticatedMusicRoute
  '/my-vybe': typeof AuthenticatedMyVybeRoute
  '/play': typeof AuthenticatedPlayRoute
  '/playlists': typeof AuthenticatedPlaylistsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/read': typeof AuthenticatedReadRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/watch': typeof AuthenticatedWatchRoute
  '/artist/$username': typeof ArtistUsernameRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/creator-invite/$token': typeof CreatorInviteTokenRoute
  '/creator/$username': typeof CreatorUsernameRoute
  '/experience/communities': typeof ExperienceCommunitiesRoute
  '/experience/events': typeof ExperienceEventsRoute
  '/experience/listen': typeof ExperienceListenRoute
  '/experience/play': typeof ExperiencePlayRoute
  '/experience/read': typeof ExperienceReadRoute
  '/experience/watch': typeof ExperienceWatchRoute
  '/playlist/$slug': typeof PlaylistSlugRoute
  '/music/$trackId': typeof AuthenticatedMusicTrackIdRoute
  '/music/upload': typeof AuthenticatedMusicUploadRoute
  '/playlists/$playlistId': typeof AuthenticatedPlaylistsPlaylistIdRoute
  '/artist/$username/playlist/$slug': typeof ArtistUsernamePlaylistSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/copyright': typeof CopyrightRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/for-artists': typeof ForArtistsRoute
  '/for-businesses': typeof ForBusinessesRoute
  '/for-film-video': typeof ForFilmVideoRoute
  '/for-writers-poets': typeof ForWritersPoetsRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/communities': typeof AuthenticatedCommunitiesRoute
  '/_authenticated/connections': typeof AuthenticatedConnectionsRoute
  '/_authenticated/content': typeof AuthenticatedContentRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/listen': typeof AuthenticatedListenRoute
  '/_authenticated/merch': typeof AuthenticatedMerchRoute
  '/_authenticated/music': typeof AuthenticatedMusicRoute
  '/_authenticated/my-vybe': typeof AuthenticatedMyVybeRoute
  '/_authenticated/play': typeof AuthenticatedPlayRoute
  '/_authenticated/playlists': typeof AuthenticatedPlaylistsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/read': typeof AuthenticatedReadRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/watch': typeof AuthenticatedWatchRoute
  '/artist/$username': typeof ArtistUsernameRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/creator-invite/$token': typeof CreatorInviteTokenRoute
  '/creator/$username': typeof CreatorUsernameRoute
  '/experience/communities': typeof ExperienceCommunitiesRoute
  '/experience/events': typeof ExperienceEventsRoute
  '/experience/listen': typeof ExperienceListenRoute
  '/experience/play': typeof ExperiencePlayRoute
  '/experience/read': typeof ExperienceReadRoute
  '/experience/watch': typeof ExperienceWatchRoute
  '/playlist/$slug': typeof PlaylistSlugRoute
  '/_authenticated/music_/$trackId': typeof AuthenticatedMusicTrackIdRoute
  '/_authenticated/music_/upload': typeof AuthenticatedMusicUploadRoute
  '/_authenticated/playlists_/$playlistId': typeof AuthenticatedPlaylistsPlaylistIdRoute
  '/artist/$username_/playlist/$slug': typeof ArtistUsernamePlaylistSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/community-guidelines'
    | '/copyright'
    | '/explore'
    | '/faq'
    | '/for-artists'
    | '/for-businesses'
    | '/for-film-video'
    | '/for-writers-poets'
    | '/help'
    | '/privacy'
    | '/terms'
    | '/trust'
    | '/activity'
    | '/admin'
    | '/communities'
    | '/connections'
    | '/content'
    | '/dashboard'
    | '/discover'
    | '/events'
    | '/home'
    | '/listen'
    | '/merch'
    | '/music'
    | '/my-vybe'
    | '/play'
    | '/playlists'
    | '/profile'
    | '/read'
    | '/settings'
    | '/watch'
    | '/artist/$username'
    | '/auth/forgot-password'
    | '/auth/onboarding'
    | '/auth/redirect'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/creator-invite/$token'
    | '/creator/$username'
    | '/experience/communities'
    | '/experience/events'
    | '/experience/listen'
    | '/experience/play'
    | '/experience/read'
    | '/experience/watch'
    | '/playlist/$slug'
    | '/music/$trackId'
    | '/music/upload'
    | '/playlists/$playlistId'
    | '/artist/$username/playlist/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/community-guidelines'
    | '/copyright'
    | '/explore'
    | '/faq'
    | '/for-artists'
    | '/for-businesses'
    | '/for-film-video'
    | '/for-writers-poets'
    | '/help'
    | '/privacy'
    | '/terms'
    | '/trust'
    | '/activity'
    | '/admin'
    | '/communities'
    | '/connections'
    | '/content'
    | '/dashboard'
    | '/discover'
    | '/events'
    | '/home'
    | '/listen'
    | '/merch'
    | '/music'
    | '/my-vybe'
    | '/play'
    | '/playlists'
    | '/profile'
    | '/read'
    | '/settings'
    | '/watch'
    | '/artist/$username'
    | '/auth/forgot-password'
    | '/auth/onboarding'
    | '/auth/redirect'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/creator-invite/$token'
    | '/creator/$username'
    | '/experience/communities'
    | '/experience/events'
    | '/experience/listen'
    | '/experience/play'
    | '/experience/read'
    | '/experience/watch'
    | '/playlist/$slug'
    | '/music/$trackId'
    | '/music/upload'
    | '/playlists/$playlistId'
    | '/artist/$username/playlist/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/community-guidelines'
    | '/copyright'
    | '/explore'
    | '/faq'
    | '/for-artists'
    | '/for-businesses'
    | '/for-film-video'
    | '/for-writers-poets'
    | '/help'
    | '/privacy'
    | '/terms'
    | '/trust'
    | '/_authenticated/activity'
    | '/_authenticated/admin'
    | '/_authenticated/communities'
    | '/_authenticated/connections'
    | '/_authenticated/content'
    | '/_authenticated/dashboard'
    | '/_authenticated/discover'
    | '/_authenticated/events'
    | '/_authenticated/home'
    | '/_authenticated/listen'
    | '/_authenticated/merch'
    | '/_authenticated/music'
    | '/_authenticated/my-vybe'
    | '/_authenticated/play'
    | '/_authenticated/playlists'
    | '/_authenticated/profile'
    | '/_authenticated/read'
    | '/_authenticated/settings'
    | '/_authenticated/watch'
    | '/artist/$username'
    | '/auth/forgot-password'
    | '/auth/onboarding'
    | '/auth/redirect'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/creator-invite/$token'
    | '/creator/$username'
    | '/experience/communities'
    | '/experience/events'
    | '/experience/listen'
    | '/experience/play'
    | '/experience/read'
    | '/experience/watch'
    | '/playlist/$slug'
    | '/_authenticated/music_/$trackId'
    | '/_authenticated/music_/upload'
    | '/_authenticated/playlists_/$playlistId'
    | '/artist/$username_/playlist/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  CopyrightRoute: typeof CopyrightRoute
  ExploreRoute: typeof ExploreRoute
  FaqRoute: typeof FaqRoute
  ForArtistsRoute: typeof ForArtistsRoute
  ForBusinessesRoute: typeof ForBusinessesRoute
  ForFilmVideoRoute: typeof ForFilmVideoRoute
  ForWritersPoetsRoute: typeof ForWritersPoetsRoute
  HelpRoute: typeof HelpRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  ArtistUsernameRoute: typeof ArtistUsernameRoute
  CreatorInviteTokenRoute: typeof CreatorInviteTokenRoute
  CreatorUsernameRoute: typeof CreatorUsernameRoute
  ExperienceCommunitiesRoute: typeof ExperienceCommunitiesRoute
  ExperienceEventsRoute: typeof ExperienceEventsRoute
  ExperienceListenRoute: typeof ExperienceListenRoute
  ExperiencePlayRoute: typeof ExperiencePlayRoute
  ExperienceReadRoute: typeof ExperienceReadRoute
  ExperienceWatchRoute: typeof ExperienceWatchRoute
  PlaylistSlugRoute: typeof PlaylistSlugRoute
  ArtistUsernamePlaylistSlugRoute: typeof ArtistUsernamePlaylistSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-writers-poets': {
      id: '/for-writers-poets'
      path: '/for-writers-poets'
      fullPath: '/for-writers-poets'
      preLoaderRoute: typeof ForWritersPoetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-film-video': {
      id: '/for-film-video'
      path: '/for-film-video'
      fullPath: '/for-film-video'
      preLoaderRoute: typeof ForFilmVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-businesses': {
      id: '/for-businesses'
      path: '/for-businesses'
      fullPath: '/for-businesses'
      preLoaderRoute: typeof ForBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-artists': {
      id: '/for-artists'
      path: '/for-artists'
      fullPath: '/for-artists'
      preLoaderRoute: typeof ForArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright': {
      id: '/copyright'
      path: '/copyright'
      fullPath: '/copyright'
      preLoaderRoute: typeof CopyrightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$slug': {
      id: '/playlist/$slug'
      path: '/playlist/$slug'
      fullPath: '/playlist/$slug'
      preLoaderRoute: typeof PlaylistSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/watch': {
      id: '/experience/watch'
      path: '/experience/watch'
      fullPath: '/experience/watch'
      preLoaderRoute: typeof ExperienceWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/read': {
      id: '/experience/read'
      path: '/experience/read'
      fullPath: '/experience/read'
      preLoaderRoute: typeof ExperienceReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/play': {
      id: '/experience/play'
      path: '/experience/play'
      fullPath: '/experience/play'
      preLoaderRoute: typeof ExperiencePlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/listen': {
      id: '/experience/listen'
      path: '/experience/listen'
      fullPath: '/experience/listen'
      preLoaderRoute: typeof ExperienceListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/events': {
      id: '/experience/events'
      path: '/experience/events'
      fullPath: '/experience/events'
      preLoaderRoute: typeof ExperienceEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/communities': {
      id: '/experience/communities'
      path: '/experience/communities'
      fullPath: '/experience/communities'
      preLoaderRoute: typeof ExperienceCommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/$username': {
      id: '/creator/$username'
      path: '/creator/$username'
      fullPath: '/creator/$username'
      preLoaderRoute: typeof CreatorUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-invite/$token': {
      id: '/creator-invite/$token'
      path: '/creator-invite/$token'
      fullPath: '/creator-invite/$token'
      preLoaderRoute: typeof CreatorInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/redirect': {
      id: '/auth/redirect'
      path: '/redirect'
      fullPath: '/auth/redirect'
      preLoaderRoute: typeof AuthRedirectRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/onboarding': {
      id: '/auth/onboarding'
      path: '/onboarding'
      fullPath: '/auth/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/artist/$username': {
      id: '/artist/$username'
      path: '/artist/$username'
      fullPath: '/artist/$username'
      preLoaderRoute: typeof ArtistUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/watch': {
      id: '/_authenticated/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof AuthenticatedWatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/read': {
      id: '/_authenticated/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof AuthenticatedReadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playlists': {
      id: '/_authenticated/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof AuthenticatedPlaylistsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play': {
      id: '/_authenticated/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AuthenticatedPlayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-vybe': {
      id: '/_authenticated/my-vybe'
      path: '/my-vybe'
      fullPath: '/my-vybe'
      preLoaderRoute: typeof AuthenticatedMyVybeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/music': {
      id: '/_authenticated/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof AuthenticatedMusicRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/merch': {
      id: '/_authenticated/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof AuthenticatedMerchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listen': {
      id: '/_authenticated/listen'
      path: '/listen'
      fullPath: '/listen'
      preLoaderRoute: typeof AuthenticatedListenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content': {
      id: '/_authenticated/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof AuthenticatedContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communities': {
      id: '/_authenticated/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof AuthenticatedCommunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playlists_/$playlistId': {
      id: '/_authenticated/playlists_/$playlistId'
      path: '/playlists/$playlistId'
      fullPath: '/playlists/$playlistId'
      preLoaderRoute: typeof AuthenticatedPlaylistsPlaylistIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/music_/upload': {
      id: '/_authenticated/music_/upload'
      path: '/music/upload'
      fullPath: '/music/upload'
      preLoaderRoute: typeof AuthenticatedMusicUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/music_/$trackId': {
      id: '/_authenticated/music_/$trackId'
      path: '/music/$trackId'
      fullPath: '/music/$trackId'
      preLoaderRoute: typeof AuthenticatedMusicTrackIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/artist/$username_/playlist/$slug': {
      id: '/artist/$username_/playlist/$slug'
      path: '/artist/$username/playlist/$slug'
      fullPath: '/artist/$username/playlist/$slug'
      preLoaderRoute: typeof ArtistUsernamePlaylistSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCommunitiesRoute: typeof AuthenticatedCommunitiesRoute
  AuthenticatedConnectionsRoute: typeof AuthenticatedConnectionsRoute
  AuthenticatedContentRoute: typeof AuthenticatedContentRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedListenRoute: typeof AuthenticatedListenRoute
  AuthenticatedMerchRoute: typeof AuthenticatedMerchRoute
  AuthenticatedMusicRoute: typeof AuthenticatedMusicRoute
  AuthenticatedMyVybeRoute: typeof AuthenticatedMyVybeRoute
  AuthenticatedPlayRoute: typeof AuthenticatedPlayRoute
  AuthenticatedPlaylistsRoute: typeof AuthenticatedPlaylistsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReadRoute: typeof AuthenticatedReadRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWatchRoute: typeof AuthenticatedWatchRoute
  AuthenticatedMusicTrackIdRoute: typeof AuthenticatedMusicTrackIdRoute
  AuthenticatedMusicUploadRoute: typeof AuthenticatedMusicUploadRoute
  AuthenticatedPlaylistsPlaylistIdRoute: typeof AuthenticatedPlaylistsPlaylistIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCommunitiesRoute: AuthenticatedCommunitiesRoute,
  AuthenticatedConnectionsRoute: AuthenticatedConnectionsRoute,
  AuthenticatedContentRoute: AuthenticatedContentRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedListenRoute: AuthenticatedListenRoute,
  AuthenticatedMerchRoute: AuthenticatedMerchRoute,
  AuthenticatedMusicRoute: AuthenticatedMusicRoute,
  AuthenticatedMyVybeRoute: AuthenticatedMyVybeRoute,
  AuthenticatedPlayRoute: AuthenticatedPlayRoute,
  AuthenticatedPlaylistsRoute: AuthenticatedPlaylistsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReadRoute: AuthenticatedReadRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWatchRoute: AuthenticatedWatchRoute,
  AuthenticatedMusicTrackIdRoute: AuthenticatedMusicTrackIdRoute,
  AuthenticatedMusicUploadRoute: AuthenticatedMusicUploadRoute,
  AuthenticatedPlaylistsPlaylistIdRoute: AuthenticatedPlaylistsPlaylistIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthRedirectRoute: typeof AuthRedirectRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthRedirectRoute: AuthRedirectRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  CopyrightRoute: CopyrightRoute,
  ExploreRoute: ExploreRoute,
  FaqRoute: FaqRoute,
  ForArtistsRoute: ForArtistsRoute,
  ForBusinessesRoute: ForBusinessesRoute,
  ForFilmVideoRoute: ForFilmVideoRoute,
  ForWritersPoetsRoute: ForWritersPoetsRoute,
  HelpRoute: HelpRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  ArtistUsernameRoute: ArtistUsernameRoute,
  CreatorInviteTokenRoute: CreatorInviteTokenRoute,
  CreatorUsernameRoute: CreatorUsernameRoute,
  ExperienceCommunitiesRoute: ExperienceCommunitiesRoute,
  ExperienceEventsRoute: ExperienceEventsRoute,
  ExperienceListenRoute: ExperienceListenRoute,
  ExperiencePlayRoute: ExperiencePlayRoute,
  ExperienceReadRoute: ExperienceReadRoute,
  ExperienceWatchRoute: ExperienceWatchRoute,
  PlaylistSlugRoute: PlaylistSlugRoute,
  ArtistUsernamePlaylistSlugRoute: ArtistUsernamePlaylistSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
