-- V24.32: Play Content Management foundation.
-- Knowledge-backed experiences are edited in the back office and consumed by Play.

INSERT INTO public.admin_role_permissions (role_code, permission_code)
VALUES ('rights_reviewer', 'admin.content.read')
ON CONFLICT DO NOTHING;

CREATE TABLE public.play_content_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  content_key text NOT NULL UNIQUE CHECK (content_key ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  experience_type text NOT NULL CHECK (experience_type IN (
    'beat_blitz', 'vybe_match', 'hidden_gems', 'daily_vybe', 'creator_spotlight', 'poll'
  )),
  title text NOT NULL CHECK (char_length(trim(title)) BETWEEN 1 AND 160),
  prompt text NOT NULL CHECK (char_length(trim(prompt)) BETWEEN 1 AND 1200),
  payload jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(payload) = 'object'),
  explanation text NOT NULL DEFAULT '' CHECK (char_length(explanation) <= 2000),
  genre text NOT NULL DEFAULT 'Mixed VYBE' CHECK (char_length(genre) BETWEEN 1 AND 80),
  difficulty text NOT NULL DEFAULT 'intro' CHECK (difficulty IN ('intro', 'easy', 'medium', 'hard', 'expert')),
  status text NOT NULL DEFAULT 'draft' CHECK (status IN (
    'draft', 'review_needed', 'rights_review', 'approved', 'scheduled', 'active', 'paused', 'retired', 'rejected'
  )),
  visibility text NOT NULL DEFAULT 'public' CHECK (visibility IN ('public', 'account_required')),
  rights_status text NOT NULL DEFAULT 'not_required' CHECK (rights_status IN (
    'not_required', 'review_needed', 'creator_approved', 'licensed', 'restricted', 'rejected'
  )),
  source_title text,
  source_url text,
  verification_notes text NOT NULL DEFAULT '',
  discovery_url text,
  scheduled_start_at timestamptz,
  scheduled_end_at timestamptz,
  version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  created_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT DEFAULT auth.uid(),
  updated_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT DEFAULT auth.uid(),
  reviewed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  published_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  published_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (scheduled_end_at IS NULL OR scheduled_start_at IS NULL OR scheduled_end_at > scheduled_start_at),
  CHECK (source_url IS NULL OR source_url ~ '^https?://'),
  CHECK (discovery_url IS NULL OR discovery_url ~ '^(/|https?://)')
);

CREATE TABLE public.play_content_revisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_item_id uuid NOT NULL REFERENCES public.play_content_items(id) ON DELETE CASCADE,
  version integer NOT NULL,
  snapshot jsonb NOT NULL,
  changed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  changed_at timestamptz NOT NULL DEFAULT now(),
  change_reason text NOT NULL DEFAULT 'content_updated',
  UNIQUE (content_item_id, version)
);

CREATE INDEX play_content_items_release_idx
  ON public.play_content_items(status, visibility, scheduled_start_at, scheduled_end_at);
CREATE INDEX play_content_items_editorial_idx
  ON public.play_content_items(experience_type, genre, difficulty, updated_at DESC);
CREATE INDEX play_content_revisions_item_idx
  ON public.play_content_revisions(content_item_id, version DESC);

ALTER TABLE public.play_content_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.play_content_revisions ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON public.play_content_items TO anon, authenticated;
GRANT SELECT ON public.play_content_revisions TO authenticated;
GRANT ALL ON public.play_content_items, public.play_content_revisions TO service_role;

CREATE POLICY "Public reads released Play content"
  ON public.play_content_items FOR SELECT TO anon
  USING (
    status IN ('active', 'scheduled')
    AND visibility = 'public'
    AND (scheduled_start_at IS NULL OR scheduled_start_at <= now())
    AND (scheduled_end_at IS NULL OR scheduled_end_at > now())
  );

CREATE POLICY "Members read released Play content"
  ON public.play_content_items FOR SELECT TO authenticated
  USING (
    (
      status IN ('active', 'scheduled')
      AND (scheduled_start_at IS NULL OR scheduled_start_at <= now())
      AND (scheduled_end_at IS NULL OR scheduled_end_at > now())
    )
    OR public.has_admin_permission(auth.uid(), 'admin.content.read')
  );

CREATE POLICY "Content administrators read Play revisions"
  ON public.play_content_revisions FOR SELECT TO authenticated
  USING (public.has_admin_permission(auth.uid(), 'admin.content.read'));

CREATE OR REPLACE FUNCTION public.capture_play_content_revision_v24_32()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.play_content_revisions (
    content_item_id, version, snapshot, changed_by, change_reason
  ) VALUES (
    OLD.id, OLD.version, to_jsonb(OLD), auth.uid(),
    CASE WHEN OLD.status IS DISTINCT FROM NEW.status THEN 'status_changed' ELSE 'content_updated' END
  );
  NEW.version := OLD.version + 1;
  NEW.updated_at := now();
  NEW.updated_by := auth.uid();
  RETURN NEW;
END;
$$;

CREATE TRIGGER play_content_capture_revision
  BEFORE UPDATE ON public.play_content_items
  FOR EACH ROW EXECUTE FUNCTION public.capture_play_content_revision_v24_32();

CREATE OR REPLACE FUNCTION public.save_play_content_item_v24_32(
  _id uuid,
  _content_key text,
  _experience_type text,
  _title text,
  _prompt text,
  _payload jsonb DEFAULT '{}'::jsonb,
  _explanation text DEFAULT '',
  _genre text DEFAULT 'Mixed VYBE',
  _difficulty text DEFAULT 'intro',
  _visibility text DEFAULT 'public',
  _rights_status text DEFAULT 'not_required',
  _source_title text DEFAULT NULL,
  _source_url text DEFAULT NULL,
  _verification_notes text DEFAULT '',
  _discovery_url text DEFAULT NULL,
  _scheduled_start_at timestamptz DEFAULT NULL,
  _scheduled_end_at timestamptz DEFAULT NULL
)
RETURNS public.play_content_items
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  actor_id uuid := auth.uid();
  saved public.play_content_items;
BEGIN
  IF actor_id IS NULL OR NOT public.has_admin_permission(actor_id, 'admin.content.moderate') THEN
    RAISE EXCEPTION 'Content Moderator permission is required';
  END IF;

  IF _id IS NULL THEN
    INSERT INTO public.play_content_items (
      content_key, experience_type, title, prompt, payload, explanation, genre, difficulty,
      visibility, rights_status, source_title, source_url, verification_notes, discovery_url,
      scheduled_start_at, scheduled_end_at, created_by, updated_by
    ) VALUES (
      lower(trim(_content_key)), _experience_type, trim(_title), trim(_prompt), coalesce(_payload, '{}'::jsonb),
      trim(coalesce(_explanation, '')), trim(_genre), _difficulty, _visibility, _rights_status,
      nullif(trim(coalesce(_source_title, '')), ''), nullif(trim(coalesce(_source_url, '')), ''),
      trim(coalesce(_verification_notes, '')), nullif(trim(coalesce(_discovery_url, '')), ''),
      _scheduled_start_at, _scheduled_end_at, actor_id, actor_id
    ) RETURNING * INTO saved;
  ELSE
    UPDATE public.play_content_items SET
      content_key = lower(trim(_content_key)), experience_type = _experience_type,
      title = trim(_title), prompt = trim(_prompt), payload = coalesce(_payload, '{}'::jsonb),
      explanation = trim(coalesce(_explanation, '')), genre = trim(_genre), difficulty = _difficulty,
      visibility = _visibility, rights_status = _rights_status,
      source_title = nullif(trim(coalesce(_source_title, '')), ''),
      source_url = nullif(trim(coalesce(_source_url, '')), ''),
      verification_notes = trim(coalesce(_verification_notes, '')),
      discovery_url = nullif(trim(coalesce(_discovery_url, '')), ''),
      scheduled_start_at = _scheduled_start_at, scheduled_end_at = _scheduled_end_at
    WHERE id = _id RETURNING * INTO saved;
    IF saved.id IS NULL THEN RAISE EXCEPTION 'Play content item was not found'; END IF;
  END IF;
  RETURN saved;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_play_content_status_v24_32(
  _id uuid,
  _status text
)
RETURNS public.play_content_items
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  actor_id uuid := auth.uid();
  saved public.play_content_items;
  current_item public.play_content_items;
BEGIN
  IF _status NOT IN ('draft', 'review_needed', 'rights_review', 'approved', 'scheduled', 'active', 'paused', 'retired', 'rejected') THEN
    RAISE EXCEPTION 'Unsupported Play content status';
  END IF;
  IF actor_id IS NULL OR NOT public.has_admin_permission(actor_id,
    CASE WHEN _status IN ('approved', 'scheduled', 'active', 'paused', 'retired', 'rejected')
      THEN 'admin.content.publish' ELSE 'admin.content.moderate' END
  ) THEN
    RAISE EXCEPTION 'The required Play publishing permission is not assigned';
  END IF;

  SELECT * INTO current_item FROM public.play_content_items WHERE id = _id;
  IF current_item.id IS NULL THEN RAISE EXCEPTION 'Play content item was not found'; END IF;
  IF _status IN ('approved', 'scheduled', 'active') THEN
    IF current_item.rights_status IN ('review_needed', 'restricted', 'rejected') THEN
      RAISE EXCEPTION 'Rights review must be cleared before approval or release';
    END IF;
    IF current_item.experience_type <> 'poll'
      AND nullif(trim(coalesce(current_item.source_title, '')), '') IS NULL
      AND current_item.rights_status NOT IN ('creator_approved', 'licensed') THEN
      RAISE EXCEPTION 'A verified source or creator-approved material is required before release';
    END IF;
  END IF;
  IF _status = 'scheduled' AND current_item.scheduled_start_at IS NULL THEN
    RAISE EXCEPTION 'A scheduled release requires a start date and time';
  END IF;

  UPDATE public.play_content_items SET
    status = _status,
    reviewed_by = CASE WHEN _status IN ('approved', 'scheduled', 'active', 'rejected') THEN actor_id ELSE reviewed_by END,
    published_by = CASE WHEN _status IN ('scheduled', 'active') THEN actor_id ELSE published_by END,
    published_at = CASE WHEN _status = 'active' THEN now() WHEN _status IN ('draft', 'review_needed', 'rejected') THEN NULL ELSE published_at END
  WHERE id = _id RETURNING * INTO saved;
  RETURN saved;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_play_content_rights_status_v24_32(
  _id uuid,
  _rights_status text,
  _verification_notes text DEFAULT ''
)
RETURNS public.play_content_items
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  actor_id uuid := auth.uid();
  saved public.play_content_items;
BEGIN
  IF _rights_status NOT IN ('not_required', 'review_needed', 'creator_approved', 'licensed', 'restricted', 'rejected') THEN
    RAISE EXCEPTION 'Unsupported Play rights status';
  END IF;
  IF actor_id IS NULL OR NOT (
    public.has_admin_permission(actor_id, 'admin.rights.review')
    OR public.has_admin_permission(actor_id, 'admin.content.moderate')
  ) THEN
    RAISE EXCEPTION 'Rights Reviewer permission is required';
  END IF;

  UPDATE public.play_content_items SET
    rights_status = _rights_status,
    verification_notes = trim(coalesce(_verification_notes, verification_notes))
  WHERE id = _id RETURNING * INTO saved;
  IF saved.id IS NULL THEN RAISE EXCEPTION 'Play content item was not found'; END IF;
  RETURN saved;
END;
$$;

REVOKE ALL ON FUNCTION public.save_play_content_item_v24_32(
  uuid, text, text, text, text, jsonb, text, text, text, text, text, text, text, text, text, timestamptz, timestamptz
) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.set_play_content_status_v24_32(uuid, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.set_play_content_rights_status_v24_32(uuid, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.save_play_content_item_v24_32(
  uuid, text, text, text, text, jsonb, text, text, text, text, text, text, text, text, text, timestamptz, timestamptz
) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_play_content_status_v24_32(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_play_content_rights_status_v24_32(uuid, text, text) TO authenticated;
