-- V24.46A2: Creator Focus launch content
-- Seeds six source-backed non-music game packs as DRAFTS only.
-- No pack is published by this migration. Editorial review remains required.

DO $$
DECLARE
  seed_actor uuid;
  pack_id uuid;
  verification_note text := 'V24.46A2 source-backed draft. Review wording and source support before approval.';
BEGIN
  SELECT created_by INTO seed_actor FROM public.play_game_packs WHERE created_by IS NOT NULL ORDER BY created_at LIMIT 1;
  IF seed_actor IS NULL THEN RAISE EXCEPTION 'V24.46A2 requires at least one existing Play game pack.'; END IF;

  -- Wait...WHAT?! Movie Edition
  INSERT INTO public.play_game_packs (pack_key, game_type, title, description, genre, focus_scope, creator_focus, topic, game_style, artwork_url, discovery_url, featured, status, visibility, created_by, updated_by)
  VALUES ('film-ww-001', 'hidden_gems', 'Wait...WHAT?! Movie Edition', 'Some movie stories sound fake. Which ones actually happened?', 'Mixed VYBE', 'single_focus', 'film', 'Behind the Scenes', 'true_or_made_up', '/images/play/focus-packs/wait-what-movie-edition.webp', '/explore', true, 'draft', 'public', seed_actor, seed_actor)
  ON CONFLICT (pack_key) DO NOTHING;
  SELECT id INTO pack_id FROM public.play_game_packs WHERE pack_key = 'film-ww-001';
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 1, 'film-ww-jaws-bruce', 'hidden_gems', 'Bruce had problems', 'TRUE OR MADE UP? Production difficulties on Jaws were caused in part by malfunctioning mechanical sharks nicknamed Bruce.', '{"choices": ["True", "Made up"], "answer": "True"}'::jsonb, 'The Academy notes that malfunctioning mechanical sharks nicknamed Bruce caused many production difficulties, forcing Steven Spielberg and the crew to improvise with editing and camera angles.', 'Mixed VYBE', 'easy', 'public', 'not_required', 'Academy of Motion Picture Arts and Sciences - Jaws', 'https://www.oscars.org/collection-highlights/all/jaws', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'film-ww-jaws-bruce');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 2, 'film-ww-oz-first-version', 'hidden_gems', 'Oz was not first', 'TRUE OR MADE UP? The 1939 Wizard of Oz was the first screen version of L. Frank Baum''s story.', '{"choices": ["True", "Made up"], "answer": "Made up"}'::jsonb, 'The Academy says the 1939 film was not the first screen version; two silent versions and a cartoon came before it.', 'Mixed VYBE', 'medium', 'public', 'not_required', 'Academy of Motion Picture Arts and Sciences - The Wizard of Oz', 'https://www.oscars.org/collection-highlights/wizard-oz', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'film-ww-oz-first-version');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 3, 'film-ww-oz-slippers', 'hidden_gems', 'Silver before ruby', 'TRUE OR MADE UP? Dorothy''s famous ruby slippers were silver in L. Frank Baum''s original book.', '{"choices": ["True", "Made up"], "answer": "True"}'::jsonb, 'The Academy notes that Dorothy''s slippers were silver in the original books before MGM made them ruby for the film.', 'Mixed VYBE', 'easy', 'public', 'not_required', 'Academy of Motion Picture Arts and Sciences - The Wizard of Oz', 'https://www.oscars.org/collection-highlights/wizard-oz', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'film-ww-oz-slippers');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 4, 'film-ww-jaws-stars', 'hidden_gems', 'The shark was the star', 'TRUE OR MADE UP? Steven Spielberg wanted Jaws packed with major movie stars because he believed celebrity casting was essential.', '{"choices": ["True", "Made up"], "answer": "Made up"}'::jsonb, 'The Academy says Spielberg did not want major names and felt the shark should be the superstar.', 'Mixed VYBE', 'medium', 'public', 'not_required', 'Academy of Motion Picture Arts and Sciences - Jaws', 'https://www.oscars.org/collection-highlights/all/jaws', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'film-ww-jaws-stars');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 5, 'film-ww-psycho-storyboards', 'hidden_gems', 'Psycho storyboards', 'TRUE OR MADE UP? The Academy preserves Saul Bass storyboard material connected to the shower scene in Psycho.', '{"choices": ["True", "Made up"], "answer": "True"}'::jsonb, 'The Academy''s Saul Bass materials include xerographic reproductions of storyboard frames for the Psycho shower scene.', 'Mixed VYBE', 'hard', 'public', 'not_required', 'Academy of Motion Picture Arts and Sciences - A Saul Bass Celebration', 'https://www.oscars.org/events/saul-bass-celebration', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'film-ww-psycho-storyboards');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 6, 'film-ww-jaws-size', 'hidden_gems', 'A very large Bruce', 'TRUE OR MADE UP? One Jaws shark design used a 25-foot body and a 400-pound head.', '{"choices": ["True", "Made up"], "answer": "True"}'::jsonb, 'The Academy Museum describes the mechanical shark design as having a 25-foot body, a 400-pound head, and jaws nearly five feet wide.', 'Mixed VYBE', 'hard', 'public', 'not_required', 'Academy of Motion Picture Arts and Sciences - Only Surviving Jaws Shark', 'https://www.oscars.org/museum/only-surviving-jaws-shark-acquired-academy-museum', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'film-ww-jaws-size');

  -- One Actor. Many Lives.
  INSERT INTO public.play_game_packs (pack_key, game_type, title, description, genre, focus_scope, creator_focus, topic, game_style, artwork_url, discovery_url, featured, status, visibility, created_by, updated_by)
  VALUES ('act-lives-001', 'hidden_gems', 'One Actor. Many Lives.', 'Three roles. One actor. Can you name the performer?', 'Mixed VYBE', 'single_focus', 'acting', 'Actors / Roles', 'three_clue', '/images/play/focus-packs/one-actor-many-lives.webp', '/explore', true, 'draft', 'public', seed_actor, seed_actor)
  ON CONFLICT (pack_key) DO NOTHING;
  SELECT id INTO pack_id FROM public.play_game_packs WHERE pack_key = 'act-lives-001';
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 1, 'act-lives-hanks', 'hidden_gems', 'Forrest, Chuck, Woody', 'Forrest Gump. Chuck Noland. Woody. Which actor connects these roles?', '{"choices": ["Tom Hanks", "Denzel Washington", "Robin Williams", "Jamie Foxx"], "answer": "Tom Hanks"}'::jsonb, 'Tom Hanks played Forrest Gump, starred as stranded engineer Chuck Noland in Cast Away, and voiced Woody in the Toy Story franchise.', 'Mixed VYBE', 'easy', 'public', 'not_required', 'Biography.com - Tom Hanks', 'https://www.biography.com/actors/tom-hanks', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'act-lives-hanks');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 2, 'act-lives-denzel', 'hidden_gems', 'Alonzo, Malcolm, Coach Boone', 'Alonzo Harris. Malcolm X. Coach Herman Boone. Which actor connects these roles?', '{"choices": ["Denzel Washington", "Morgan Freeman", "Jamie Foxx", "Forest Whitaker"], "answer": "Denzel Washington"}'::jsonb, 'Denzel Washington portrayed Alonzo Harris in Training Day, Malcolm X in Spike Lee''s film, and Coach Herman Boone in Remember the Titans.', 'Mixed VYBE', 'easy', 'public', 'not_required', 'Biography.com - Denzel Washington', 'https://www.biography.com/actors/denzel-washington', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'act-lives-denzel');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 3, 'act-lives-foxx', 'hidden_gems', 'Ray, Django, Electro', 'Ray Charles. Django. Electro. Which performer connects these roles?', '{"choices": ["Jamie Foxx", "Will Smith", "Don Cheadle", "Idris Elba"], "answer": "Jamie Foxx"}'::jsonb, 'Jamie Foxx won an Academy Award for portraying Ray Charles, starred as Django in Django Unchained, and played Electro in The Amazing Spider-Man 2.', 'Mixed VYBE', 'medium', 'public', 'not_required', 'Biography.com - Jamie Foxx', 'https://www.biography.com/actors/jamie-foxx', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'act-lives-foxx');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 4, 'act-lives-moreno', 'hidden_gems', 'Anita, Sister Peter Marie, Lydia', 'Anita. Sister Peter Marie. Lydia. Which performer connects these roles?', '{"choices": ["Rita Moreno", "Chita Rivera", "Rosie Perez", "Sonia Manzano"], "answer": "Rita Moreno"}'::jsonb, 'Rita Moreno played Anita in West Side Story, Sister Peter Marie on Oz, and Lydia in the reboot of One Day at a Time.', 'Mixed VYBE', 'medium', 'public', 'not_required', 'PBS American Masters - Rita Moreno biography and timeline', 'https://www.pbs.org/wnet/americanmasters/rita-moreno-biography-and-timeline/18466/', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'act-lives-moreno');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 5, 'act-lives-whoopi', 'hidden_gems', 'Celie, Oda Mae, Mary Clarence', 'Celie. Oda Mae Brown. Sister Mary Clarence. Which performer connects these roles?', '{"choices": ["Whoopi Goldberg", "Alfre Woodard", "Jenifer Lewis", "Loretta Devine"], "answer": "Whoopi Goldberg"}'::jsonb, 'Whoopi Goldberg starred as Celie in The Color Purple, won an Oscar for Ghost as Oda Mae Brown, and starred as Sister Mary Clarence in Sister Act.', 'Mixed VYBE', 'medium', 'public', 'not_required', 'The HistoryMakers - Whoopi Goldberg', 'https://www.thehistorymakers.org/biography/whoopi-goldberg', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'act-lives-whoopi');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 6, 'act-lives-robin', 'hidden_gems', 'Genie, Doubtfire, Sean Maguire', 'The Genie. Mrs. Doubtfire. Sean Maguire. Which performer connects these roles?', '{"choices": ["Robin Williams", "Billy Crystal", "Steve Martin", "Eddie Murphy"], "answer": "Robin Williams"}'::jsonb, 'Robin Williams voiced the Genie in Aladdin, starred in Mrs. Doubtfire, and won an Academy Award for playing Sean Maguire in Good Will Hunting.', 'Mixed VYBE', 'medium', 'public', 'not_required', 'D23 - Robin Williams', 'https://d23.com/walt-disney-legend/robin-williams/', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'act-lives-robin');

  -- Comedy or Myth?
  INSERT INTO public.play_game_packs (pack_key, game_type, title, description, genre, focus_scope, creator_focus, topic, game_style, artwork_url, discovery_url, featured, status, visibility, created_by, updated_by)
  VALUES ('com-myth-001', 'hidden_gems', 'Comedy or Myth?', 'Comedy history is stranger than the jokes. Fact or fiction?', 'Mixed VYBE', 'single_focus', 'comedy', 'Comedy History', 'fact_or_myth', '/images/play/focus-packs/comedy-or-myth.webp', '/explore', true, 'draft', 'public', seed_actor, seed_actor)
  ON CONFLICT (pack_key) DO NOTHING;
  SELECT id INTO pack_id FROM public.play_game_packs WHERE pack_key = 'com-myth-001';
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 1, 'com-myth-vaudeville-popular', 'hidden_gems', 'Vaudeville ruled live entertainment', 'COMEDY OR MYTH? From the early 1880s through the end of the 1920s, vaudeville was the most popular form of live entertainment in the United States.', '{"choices": ["Comedy fact", "Comedy myth"], "answer": "Comedy fact"}'::jsonb, 'The Library of Congress describes vaudeville as the country''s most popular live entertainment form during that period.', 'Mixed VYBE', 'easy', 'public', 'not_required', 'Library of Congress - Bob Hope and American Variety: The Bill', 'https://www.loc.gov/exhibits/bobhope/thebill.html', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'com-myth-vaudeville-popular');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 2, 'com-myth-vaudeville-only-comics', 'hidden_gems', 'More than comedians', 'COMEDY OR MYTH? A typical vaudeville bill consisted only of comedians.', '{"choices": ["Comedy fact", "Comedy myth"], "answer": "Comedy myth"}'::jsonb, 'Vaudeville bills mixed comedians and musicians with dancers, acrobats, magicians, trained animals, and novelty performers.', 'Mixed VYBE', 'easy', 'public', 'not_required', 'Library of Congress - Bob Hope and American Variety: The Bill', 'https://www.loc.gov/exhibits/bobhope/thebill.html', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'com-myth-vaudeville-only-comics');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 3, 'com-myth-hope-dance-team', 'hidden_gems', 'Hope started dancing', 'COMEDY OR MYTH? Bob Hope''s first vaudeville tours were as half of a two-man dancing team.', '{"choices": ["Comedy fact", "Comedy myth"], "answer": "Comedy fact"}'::jsonb, 'The Library of Congress notes that Hope''s first vaudeville tours were with a two-man dancing act.', 'Mixed VYBE', 'medium', 'public', 'not_required', 'Library of Congress - Bob Hope and American Variety: Vaudeville', 'https://www.loc.gov/exhibits/bobhope/vaude.html', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'com-myth-hope-dance-team');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 4, 'com-myth-two-a-days', 'hidden_gems', 'Two shows meant big time', 'COMEDY OR MYTH? In big-time vaudeville, theaters known for ''two-a-days'' presented two shows each day.', '{"choices": ["Comedy fact", "Comedy myth"], "answer": "Comedy fact"}'::jsonb, 'The Library of Congress explains that big-time houses staged two shows a day, unlike continuous small-time schedules.', 'Mixed VYBE', 'medium', 'public', 'not_required', 'Library of Congress - Bob Hope and American Variety: Vaudeville', 'https://www.loc.gov/exhibits/bobhope/vaude.html', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'com-myth-two-a-days');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 5, 'com-myth-stock-material', 'hidden_gems', 'Comedy had stock material', 'COMEDY OR MYTH? Vaudeville comedy commonly used stock material such as monologs, bits, sketches, jokes, and song parodies.', '{"choices": ["Comedy fact", "Comedy myth"], "answer": "Comedy fact"}'::jsonb, 'Library of Congress materials describe these as common building blocks that performers adapted with physical comedy and delivery.', 'Mixed VYBE', 'medium', 'public', 'not_required', 'Library of Congress - Bob Hope and American Variety: Bits & Sketches', 'https://www.loc.gov/exhibits/bobhope/bits.html', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'com-myth-stock-material');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 6, 'com-myth-vaudeville-rise-1930s', 'hidden_gems', 'Movies challenged vaudeville', 'COMEDY OR MYTH? Vaudeville became more dominant in the early 1930s because motion pictures and radio were fading.', '{"choices": ["Comedy fact", "Comedy myth"], "answer": "Comedy myth"}'::jsonb, 'The opposite happened: the Library of Congress says motion pictures and radio helped drive vaudeville''s decline in the early 1930s.', 'Mixed VYBE', 'hard', 'public', 'not_required', 'Library of Congress - Bob Hope and American Variety: Moving On', 'https://www.loc.gov/exhibits/bobhope/moving.html', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'com-myth-vaudeville-rise-1930s');

  -- Behind the Mic
  INSERT INTO public.play_game_packs (pack_key, game_type, title, description, genre, focus_scope, creator_focus, topic, game_style, artwork_url, discovery_url, featured, status, visibility, created_by, updated_by)
  VALUES ('pod-mic-001', 'beat_blitz', 'Behind the Mic', 'From RSS to podfade - how much do you know about podcasting?', 'Mixed VYBE', 'single_focus', 'podcasting', 'Podcast Knowledge', 'choice', '/images/play/focus-packs/behind-the-mic.webp', '/explore', true, 'draft', 'public', seed_actor, seed_actor)
  ON CONFLICT (pack_key) DO NOTHING;
  SELECT id INTO pack_id FROM public.play_game_packs WHERE pack_key = 'pod-mic-001';
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 1, 'pod-mic-rss-spec', 'beat_blitz', 'RSS foundation', 'Apple says a podcast RSS feed submitted through RSS should adhere to which specification?', '{"choices": ["RSS 2.0", "HTML5 only", "FTP 1.0", "SMTP"], "answer": "RSS 2.0"}'::jsonb, 'Apple Podcasts requires RSS-feed submissions to adhere to RSS 2.0 specifications.', 'Mixed VYBE', 'easy', 'public', 'not_required', 'Apple Podcasts for Creators - Podcast RSS feed requirements', 'https://podcasters.apple.com/support/823-podcast-requirements', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'pod-mic-rss-spec');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 2, 'pod-mic-public-feed', 'beat_blitz', 'Public feed', 'Which description fits an Apple Podcasts RSS feed requirement?', '{"choices": ["Publicly addressable", "Password-protected only", "Stored only on a phone", "Sent only by email"], "answer": "Publicly addressable"}'::jsonb, 'Apple says RSS feed URLs must be publicly addressable and not password-protected.', 'Mixed VYBE', 'easy', 'public', 'not_required', 'Apple Podcasts for Creators - Podcast RSS feed requirements', 'https://podcasters.apple.com/support/823-podcast-requirements', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'pod-mic-public-feed');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 3, 'pod-mic-feed-basics', 'beat_blitz', 'Feed basics', 'Which pair does Apple list among the basic content requirements for a podcast submitted from an RSS feed?', '{"choices": ["At least one episode and artwork", "Ten episodes and video", "A paid subscription and transcript", "A live stream and newsletter"], "answer": "At least one episode and artwork"}'::jsonb, 'Apple lists at least one episode and artwork among the required feed content.', 'Mixed VYBE', 'easy', 'public', 'not_required', 'Apple Podcasts for Creators - Podcast RSS feed requirements', 'https://podcasters.apple.com/support/823-podcast-requirements', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'pod-mic-feed-basics');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 4, 'pod-mic-date-format', 'beat_blitz', 'Podcast dates', 'Apple says RSS feed dates and times should conform to which standard?', '{"choices": ["RFC 2822", "MIDI", "JPEG", "HTTP/0.9"], "answer": "RFC 2822"}'::jsonb, 'Apple requires podcast RSS dates and times to follow RFC 2822 formatting.', 'Mixed VYBE', 'medium', 'public', 'not_required', 'Apple Podcasts for Creators - Podcast RSS feed requirements', 'https://podcasters.apple.com/support/823-podcast-requirements', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'pod-mic-date-format');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 5, 'pod-mic-category-tag', 'beat_blitz', 'Category tag', 'Which RSS tag family does Apple show for assigning a podcast category?', '{"choices": ["itunes:category", "video:genre", "mail:topic", "css:category"], "answer": "itunes:category"}'::jsonb, 'Apple documents the itunes:category tag for categories and subcategories in RSS feeds.', 'Mixed VYBE', 'medium', 'public', 'not_required', 'Apple Podcasts for Creators - Apple Podcasts categories', 'https://podcasters.apple.com/support/1691-apple-podcasts-categories', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'pod-mic-category-tag');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 6, 'pod-mic-rss-audio', 'beat_blitz', 'Accepted RSS audio', 'For RSS feeds, which audio formats does Apple Podcasts say it accepts?', '{"choices": ["MP3 or AAC", "WAV only", "FLAC only", "MIDI only"], "answer": "MP3 or AAC"}'::jsonb, 'Apple''s audio requirements state that RSS feeds can use MP3 or AAC audio.', 'Mixed VYBE', 'medium', 'public', 'not_required', 'Apple Podcasts for Creators - Audio requirements', 'https://podcasters.apple.com/support/893-audio-requirements', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'pod-mic-rss-audio');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 7, 'pod-mic-episode-tags', 'beat_blitz', 'Episode essentials', 'For an episode created via RSS, which tags does Apple say must be included?', '{"choices": ["Title and enclosure", "Color and font", "Author photo and map", "Poll and rating"], "answer": "Title and enclosure"}'::jsonb, 'Apple says RSS episodes must include title and enclosure tags.', 'Mixed VYBE', 'hard', 'public', 'not_required', 'Apple Podcasts for Creators - Create an episode', 'https://podcasters.apple.com/support/825-how-to-create-an-episode', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'pod-mic-episode-tags');

  -- Who Wrote Like That?!
  INSERT INTO public.play_game_packs (pack_key, game_type, title, description, genre, focus_scope, creator_focus, topic, game_style, artwork_url, discovery_url, featured, status, visibility, created_by, updated_by)
  VALUES ('write-weird-001', 'hidden_gems', 'Who Wrote Like That?!', 'Famous writers. Unusual habits. Can you guess who did what?', 'Mixed VYBE', 'single_focus', 'writing', 'Writer Habits', 'progressive_clue', '/images/play/focus-packs/who-wrote-like-that.webp', '/explore', true, 'draft', 'public', seed_actor, seed_actor)
  ON CONFLICT (pack_key) DO NOTHING;
  SELECT id INTO pack_id FROM public.play_game_packs WHERE pack_key = 'write-weird-001';
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 1, 'write-weird-george-sand-name', 'hidden_gems', 'George Sand', 'This French Romantic writer was born Amantine Lucile Aurore Dupin and became famous under a male pen name. Who was it?', '{"choices": ["George Sand", "George Eliot", "Colette", "Simone de Beauvoir"], "answer": "George Sand"}'::jsonb, 'The Library of Congress identifies Amantine Lucile Aurore Dupin as the writer who published under the name George Sand.', 'Mixed VYBE', 'easy', 'public', 'not_required', 'Library of Congress - George Sand', 'https://guides.loc.gov/feminism-french-women-history/famous/george-sand', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'write-weird-george-sand-name');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 2, 'write-weird-indiana', 'hidden_gems', 'Indiana made the name', 'Which novel does the Library of Congress identify as George Sand''s first book under that pseudonym?', '{"choices": ["Indiana", "Jane Eyre", "Beloved", "Middlemarch"], "answer": "Indiana"}'::jsonb, 'The Library of Congress notes that Indiana, published in 1832, was Sand''s first book under the pseudonym and established her name.', 'Mixed VYBE', 'medium', 'public', 'not_required', 'Library of Congress - George Sand', 'https://guides.loc.gov/feminism-french-women-history/famous/george-sand', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'write-weird-indiana');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 3, 'write-weird-schoolcraft-penname', 'hidden_gems', 'Leelinau and Rosa', 'Which writer used the pen names Leelinau and Rosa in the manuscript magazine The Literary Voyager?', '{"choices": ["Jane Johnston Schoolcraft", "Emily Dickinson", "Zora Neale Hurston", "Gwendolyn Brooks"], "answer": "Jane Johnston Schoolcraft"}'::jsonb, 'The Library of Congress documents Schoolcraft''s use of Leelinau and Rosa for poems and stories in The Literary Voyager.', 'Mixed VYBE', 'hard', 'public', 'not_required', 'Library of Congress - Jane Johnston Schoolcraft biographical essay', 'https://www.loc.gov/collections/henry-rowe-schoolcraft-papers/articles-and-essays/jane-johnston-schoolcraft-biographical-essay/', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'write-weird-schoolcraft-penname');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 4, 'write-weird-whitman-notebooks', 'hidden_gems', 'Always carrying notebooks', 'Which poet carried small, often handmade notebooks and used them to capture names, places, ideas, slang, and observations?', '{"choices": ["Walt Whitman", "Robert Frost", "Langston Hughes", "Edgar Allan Poe"], "answer": "Walt Whitman"}'::jsonb, 'The Library of Congress describes Whitman carrying small notebooks and filling them with observations and material that fed later writing.', 'Mixed VYBE', 'medium', 'public', 'not_required', 'Library of Congress - Wordsmithing Whitman', 'https://blogs.loc.gov/catbird/2021/05/wordsmithing-whitman-diaries-and-notebooks-from-the-feinberg-whitman-papers/', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'write-weird-whitman-notebooks');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 5, 'write-weird-oates-plans', 'hidden_gems', 'Plans before prose', 'At the 2004 National Book Festival, which writer said she would no more start a novel without knowing where it was going than start a hike without knowing the destination?', '{"choices": ["Joyce Carol Oates", "Toni Morrison", "Alice Walker", "Maya Angelou"], "answer": "Joyce Carol Oates"}'::jsonb, 'The Library of Congress reported Oates describing an extensively planned writing process, including knowing where the novel was going before she began.', 'Mixed VYBE', 'hard', 'public', 'not_required', 'Library of Congress - Authors Describe the Hard Work of Creation', 'https://loc.gov/loc/lcib/0412/create.html', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'write-weird-oates-plans');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 6, 'write-weird-edward-jones-revisions', 'hidden_gems', 'Five revisions', 'Which Pulitzer Prize-winning writer told a National Book Festival audience that he revised his manuscript at least five times?', '{"choices": ["Edward P. Jones", "John Grisham", "Walter Mosley", "James Patterson"], "answer": "Edward P. Jones"}'::jsonb, 'The Library of Congress reported Edward P. Jones saying he revised the manuscript of The Known World at least five times.', 'Mixed VYBE', 'hard', 'public', 'not_required', 'Library of Congress - Authors Describe the Hard Work of Creation', 'https://loc.gov/loc/lcib/0412/create.html', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'write-weird-edward-jones-revisions');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 7, 'write-weird-mark-twain-white', 'hidden_gems', 'The white suit', 'Which author dramatically appeared at the Library of Congress in a cream-colored suit in December 1906, helping establish his iconic late-life look?', '{"choices": ["Mark Twain", "Ernest Hemingway", "F. Scott Fitzgerald", "Jack London"], "answer": "Mark Twain"}'::jsonb, 'The Library of Congress recounts Mark Twain unveiling the white-suit look at a 1906 copyright hearing.', 'Mixed VYBE', 'medium', 'public', 'not_required', 'Library of Congress - Mark Twain Debuts Iconic Style', 'https://blogs.loc.gov/loc/2017/12/this-day-in-history-mark-twain-debuts-iconic-style-at-library-of-congress/', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'write-weird-mark-twain-white');

  -- Where Did It Start?
  INSERT INTO public.play_game_packs (pack_key, game_type, title, description, genre, focus_scope, creator_focus, topic, game_style, artwork_url, discovery_url, featured, status, visibility, created_by, updated_by)
  VALUES ('dance-origin-001', 'hidden_gems', 'Where Did It Start?', 'You know the move. Do you know the culture behind it?', 'Mixed VYBE', 'single_focus', 'dance', 'Dance Geography / Origins', 'origin_challenge', '/images/play/focus-packs/where-did-it-start.webp', '/explore', true, 'draft', 'public', seed_actor, seed_actor)
  ON CONFLICT (pack_key) DO NOTHING;
  SELECT id INTO pack_id FROM public.play_game_packs WHERE pack_key = 'dance-origin-001';
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 1, 'dance-origin-tap-south', 'hidden_gems', 'Tap emerged in America', 'Where did tap dance emerge as a distinct American form according to the Library of Congress?', '{"choices": ["Southern United States", "Northern Italy", "Eastern Russia", "Coastal Japan"], "answer": "Southern United States"}'::jsonb, 'The Library of Congress traces tap''s development to the southern United States in the 1700s, blending British and West African traditions.', 'Mixed VYBE', 'easy', 'public', 'not_required', 'Library of Congress - Tap Dance in America: A Short History', 'https://www.loc.gov/collections/songs-of-america/articles-and-essays/musical-styles/parlor-and-concert-stage/tap-dance/', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'dance-origin-tap-south');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 2, 'dance-origin-tap-roots', 'hidden_gems', 'Tap roots', 'Tap dance developed from the interaction of which broad traditions in America?', '{"choices": ["British and West African", "Japanese and French", "Russian and Brazilian", "Spanish and Korean"], "answer": "British and West African"}'::jsonb, 'The Library of Congress describes tap as developing through a fusion of British and West African musical and step-dance traditions.', 'Mixed VYBE', 'easy', 'public', 'not_required', 'Library of Congress - Tap Dance in America: A Short History', 'https://www.loc.gov/collections/songs-of-america/articles-and-essays/musical-styles/parlor-and-concert-stage/tap-dance/', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'dance-origin-tap-roots');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 3, 'dance-origin-metal-taps', 'hidden_gems', 'Metal taps came later', 'When did metal plates commonly begin appearing on tap dancers'' shoes on the Broadway musical stage?', '{"choices": ["Early 20th century", "Early 1700s", "Immediately after the Civil War", "Late 1500s"], "answer": "Early 20th century"}'::jsonb, 'The Library of Congress notes that early tapping used hard-soled shoes, clogs, or boots; metal taps appeared in the early decades of the 20th century.', 'Mixed VYBE', 'medium', 'public', 'not_required', 'Library of Congress - Tap Dance in America: A Short History', 'https://www.loc.gov/collections/songs-of-america/articles-and-essays/musical-styles/parlor-and-concert-stage/tap-dance/', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'dance-origin-metal-taps');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 4, 'dance-origin-hiphop-nyc', 'hidden_gems', 'Hip-hop dance culture', 'Smithsonian Folklife describes hip-hop culture beginning around 1973 in the inner cities of which city?', '{"choices": ["New York City", "Seattle", "Nashville", "San Diego"], "answer": "New York City"}'::jsonb, 'Smithsonian Folklife describes hip-hop culture as emerging around 1973 among young African Americans and Latinos in New York City.', 'Mixed VYBE', 'easy', 'public', 'not_required', 'Smithsonian Folklife Festival - Hip-Hop Dance', 'https://festival.si.edu/articles/1993/hip-hop-dance', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'dance-origin-hiphop-nyc');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 5, 'dance-origin-bojangles', 'hidden_gems', 'Bojangles birthplace', 'Legendary tap dancer Bill ''Bojangles'' Robinson was born in which city?', '{"choices": ["Richmond, Virginia", "Chicago, Illinois", "Atlanta, Georgia", "New Orleans, Louisiana"], "answer": "Richmond, Virginia"}'::jsonb, 'The Library of Congress records Robinson''s birth in Richmond, Virginia, in 1878.', 'Mixed VYBE', 'medium', 'public', 'not_required', 'Library of Congress - Today in History: Bill Bojangles Robinson', 'https://www.loc.gov/item/today-in-history/may-25', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'dance-origin-bojangles');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 6, 'dance-origin-nicholas-brothers', 'hidden_gems', 'Nicholas Brothers blend', 'Which combination best describes the Nicholas Brothers'' celebrated theatrical dance style?', '{"choices": ["Jazz rhythm, tap, acrobatics, ballet, and Black vernacular dance", "Only classical ballet", "Only Irish step dance", "Ballroom without tap"], "answer": "Jazz rhythm, tap, acrobatics, ballet, and Black vernacular dance"}'::jsonb, 'The Library of Congress describes Fayard and Harold Nicholas as combining those forms into an exuberant American theatrical dance style.', 'Mixed VYBE', 'medium', 'public', 'not_required', 'Library of Congress - Tap Dance in America: A Short History', 'https://www.loc.gov/collections/songs-of-america/articles-and-essays/musical-styles/parlor-and-concert-stage/tap-dance/', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'dance-origin-nicholas-brothers');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 7, 'dance-origin-stepping', 'hidden_gems', 'Stepping history', 'The Library of Congress traces African American collegiate stepping back to which period?', '{"choices": ["Early 20th century", "The 1600s", "The 1960s only", "The 1990s"], "answer": "Early 20th century"}'::jsonb, 'The Library of Congress links the form to Black World War I veterans entering colleges and combining military drill influences with Black vernacular dance.', 'Mixed VYBE', 'hard', 'public', 'not_required', 'Library of Congress - Tap Dance in America: A Short History', 'https://www.loc.gov/collections/songs-of-america/articles-and-essays/musical-styles/parlor-and-concert-stage/tap-dance/', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'dance-origin-stepping');
  INSERT INTO public.play_content_items (game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation, genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes, discovery_url, created_by, updated_by)
  SELECT pack_id, 8, 'dance-origin-tap-challenge', 'hidden_gems', 'The tap challenge', 'In tap history, what is a ''tap challenge''?', '{"choices": ["A dance competition or showdown", "A shoe-repair method", "A music copyright form", "A ballet warm-up only"], "answer": "A dance competition or showdown"}'::jsonb, 'The Library of Congress uses tap challenge as a general term for competitions, contests, breakdowns, or showdowns between dancers.', 'Mixed VYBE', 'medium', 'public', 'not_required', 'Library of Congress - Tap Dance in America: A Short History', 'https://www.loc.gov/collections/songs-of-america/articles-and-essays/musical-styles/parlor-and-concert-stage/tap-dance/', verification_note, '/explore', seed_actor, seed_actor
  WHERE NOT EXISTS (SELECT 1 FROM public.play_content_items WHERE content_key = 'dance-origin-tap-challenge');

  RAISE NOTICE 'V24.46A2 seeded draft packs: Film 6, Acting 6, Comedy 6, Podcasting 7, Writing 7, Dance 8.';
END;
$$;
