-- V24.33: Play game packs.
-- A pack is the release unit; its ordered items remain individually editable and revisioned.

CREATE TABLE public.play_game_packs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pack_key text NOT NULL UNIQUE CHECK (pack_key ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  game_type text NOT NULL CHECK (game_type IN ('beat_blitz', 'vybe_match', 'hidden_gems', 'daily_vybe')),
  title text NOT NULL CHECK (char_length(trim(title)) BETWEEN 1 AND 160),
  description text NOT NULL DEFAULT '' CHECK (char_length(description) <= 1200),
  genre text NOT NULL DEFAULT 'Mixed VYBE' CHECK (char_length(genre) BETWEEN 1 AND 80),
  status text NOT NULL DEFAULT 'draft' CHECK (status IN (
    'draft', 'review_needed', 'approved', 'scheduled', 'active', 'paused', 'retired', 'rejected'
  )),
  visibility text NOT NULL DEFAULT 'public' CHECK (visibility IN ('public', 'account_required')),
  scheduled_start_at timestamptz,
  scheduled_end_at timestamptz,
  version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  created_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT DEFAULT auth.uid(),
  updated_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT DEFAULT auth.uid(),
  reviewed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  published_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  published_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (scheduled_end_at IS NULL OR scheduled_start_at IS NULL OR scheduled_end_at > scheduled_start_at)
);

CREATE TABLE public.play_game_pack_revisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_pack_id uuid NOT NULL REFERENCES public.play_game_packs(id) ON DELETE CASCADE,
  version integer NOT NULL,
  snapshot jsonb NOT NULL,
  changed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  changed_at timestamptz NOT NULL DEFAULT now(),
  change_reason text NOT NULL DEFAULT 'pack_updated',
  UNIQUE (game_pack_id, version)
);

ALTER TABLE public.play_content_items
  ADD COLUMN game_pack_id uuid REFERENCES public.play_game_packs(id) ON DELETE SET NULL,
  ADD COLUMN position integer CHECK (position IS NULL OR position > 0);

CREATE UNIQUE INDEX play_content_items_pack_position_idx
  ON public.play_content_items(game_pack_id, position) WHERE game_pack_id IS NOT NULL;
CREATE INDEX play_game_packs_release_idx
  ON public.play_game_packs(status, visibility, scheduled_start_at, scheduled_end_at);
CREATE INDEX play_game_packs_editorial_idx
  ON public.play_game_packs(game_type, genre, updated_at DESC);

ALTER TABLE public.play_game_packs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.play_game_pack_revisions ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON public.play_game_packs TO anon, authenticated;
GRANT SELECT ON public.play_game_pack_revisions TO authenticated;
GRANT ALL ON public.play_game_packs, public.play_game_pack_revisions TO service_role;

CREATE POLICY "Public reads released Play game packs"
  ON public.play_game_packs FOR SELECT TO anon
  USING (
    status IN ('active', 'scheduled')
    AND visibility = 'public'
    AND (scheduled_start_at IS NULL OR scheduled_start_at <= now())
    AND (scheduled_end_at IS NULL OR scheduled_end_at > now())
  );

CREATE POLICY "Members read released or managed Play game packs"
  ON public.play_game_packs FOR SELECT TO authenticated
  USING (
    (
      status IN ('active', 'scheduled')
      AND (scheduled_start_at IS NULL OR scheduled_start_at <= now())
      AND (scheduled_end_at IS NULL OR scheduled_end_at > now())
    )
    OR public.has_admin_permission(auth.uid(), 'admin.content.read')
  );

CREATE POLICY "Content administrators read Play game pack revisions"
  ON public.play_game_pack_revisions FOR SELECT TO authenticated
  USING (public.has_admin_permission(auth.uid(), 'admin.content.read'));

DROP POLICY "Public reads released Play content" ON public.play_content_items;
CREATE POLICY "Public reads released Play content"
  ON public.play_content_items FOR SELECT TO anon
  USING (
    status IN ('active', 'scheduled')
    AND visibility = 'public'
    AND (scheduled_start_at IS NULL OR scheduled_start_at <= now())
    AND (scheduled_end_at IS NULL OR scheduled_end_at > now())
    AND (
      game_pack_id IS NULL
      OR EXISTS (
        SELECT 1 FROM public.play_game_packs pack
        WHERE pack.id = game_pack_id
          AND pack.status IN ('active', 'scheduled')
          AND pack.visibility = 'public'
          AND (pack.scheduled_start_at IS NULL OR pack.scheduled_start_at <= now())
          AND (pack.scheduled_end_at IS NULL OR pack.scheduled_end_at > now())
      )
    )
  );

DROP POLICY "Members read released Play content" ON public.play_content_items;
CREATE POLICY "Members read released Play content"
  ON public.play_content_items FOR SELECT TO authenticated
  USING (
    public.has_admin_permission(auth.uid(), 'admin.content.read')
    OR (
      status IN ('active', 'scheduled')
      AND (scheduled_start_at IS NULL OR scheduled_start_at <= now())
      AND (scheduled_end_at IS NULL OR scheduled_end_at > now())
      AND (
        game_pack_id IS NULL
        OR EXISTS (
          SELECT 1 FROM public.play_game_packs pack
          WHERE pack.id = game_pack_id
            AND pack.status IN ('active', 'scheduled')
            AND (pack.scheduled_start_at IS NULL OR pack.scheduled_start_at <= now())
            AND (pack.scheduled_end_at IS NULL OR pack.scheduled_end_at > now())
        )
      )
    )
  );

CREATE OR REPLACE FUNCTION public.capture_play_game_pack_revision_v24_33()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.play_game_pack_revisions (
    game_pack_id, version, snapshot, changed_by, change_reason
  ) VALUES (
    OLD.id, OLD.version, to_jsonb(OLD), auth.uid(),
    CASE WHEN OLD.status IS DISTINCT FROM NEW.status THEN 'status_changed' ELSE 'pack_updated' END
  );
  NEW.version := OLD.version + 1;
  NEW.updated_at := now();
  NEW.updated_by := auth.uid();
  RETURN NEW;
END;
$$;

CREATE TRIGGER play_game_pack_capture_revision
  BEFORE UPDATE ON public.play_game_packs
  FOR EACH ROW EXECUTE FUNCTION public.capture_play_game_pack_revision_v24_33();

CREATE OR REPLACE FUNCTION public.guard_live_play_pack_item_edit_v24_33()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF OLD.game_pack_id IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM public.play_game_packs
      WHERE id = OLD.game_pack_id AND status IN ('active', 'scheduled')
    )
    AND (
      OLD.content_key IS DISTINCT FROM NEW.content_key
      OR OLD.title IS DISTINCT FROM NEW.title
      OR OLD.prompt IS DISTINCT FROM NEW.prompt
      OR OLD.payload IS DISTINCT FROM NEW.payload
      OR OLD.explanation IS DISTINCT FROM NEW.explanation
      OR OLD.genre IS DISTINCT FROM NEW.genre
      OR OLD.difficulty IS DISTINCT FROM NEW.difficulty
      OR OLD.rights_status IS DISTINCT FROM NEW.rights_status
      OR OLD.source_title IS DISTINCT FROM NEW.source_title
      OR OLD.source_url IS DISTINCT FROM NEW.source_url
      OR OLD.verification_notes IS DISTINCT FROM NEW.verification_notes
      OR OLD.discovery_url IS DISTINCT FROM NEW.discovery_url
      OR OLD.game_pack_id IS DISTINCT FROM NEW.game_pack_id
      OR OLD.position IS DISTINCT FROM NEW.position
    )
  THEN
    RAISE EXCEPTION 'Pause the game pack before editing its live content';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER play_content_guard_live_pack_edit
  BEFORE UPDATE ON public.play_content_items
  FOR EACH ROW EXECUTE FUNCTION public.guard_live_play_pack_item_edit_v24_33();

CREATE OR REPLACE FUNCTION public.save_play_game_pack_v24_33(
  _id uuid,
  _pack_key text,
  _game_type text,
  _title text,
  _description text DEFAULT '',
  _genre text DEFAULT 'Mixed VYBE',
  _visibility text DEFAULT 'public',
  _scheduled_start_at timestamptz DEFAULT NULL,
  _scheduled_end_at timestamptz DEFAULT NULL
)
RETURNS public.play_game_packs
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  actor_id uuid := auth.uid();
  saved public.play_game_packs;
BEGIN
  IF actor_id IS NULL OR NOT public.has_admin_permission(actor_id, 'admin.content.moderate') THEN
    RAISE EXCEPTION 'Content Moderator permission is required';
  END IF;

  IF _id IS NULL THEN
    INSERT INTO public.play_game_packs (
      pack_key, game_type, title, description, genre, visibility,
      scheduled_start_at, scheduled_end_at, created_by, updated_by
    ) VALUES (
      lower(trim(_pack_key)), _game_type, trim(_title), trim(coalesce(_description, '')),
      trim(_genre), _visibility, _scheduled_start_at, _scheduled_end_at, actor_id, actor_id
    ) RETURNING * INTO saved;
  ELSE
    UPDATE public.play_game_packs SET
      pack_key = lower(trim(_pack_key)), game_type = _game_type, title = trim(_title),
      description = trim(coalesce(_description, '')), genre = trim(_genre), visibility = _visibility,
      scheduled_start_at = _scheduled_start_at, scheduled_end_at = _scheduled_end_at
    WHERE id = _id RETURNING * INTO saved;
    IF saved.id IS NULL THEN RAISE EXCEPTION 'Play game pack was not found'; END IF;
  END IF;
  RETURN saved;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_play_game_pack_status_v24_33(_id uuid, _status text)
RETURNS public.play_game_packs
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  actor_id uuid := auth.uid();
  saved public.play_game_packs;
  item_count integer;
  unreleasable_count integer;
BEGIN
  IF _status NOT IN ('draft', 'review_needed', 'approved', 'scheduled', 'active', 'paused', 'retired', 'rejected') THEN
    RAISE EXCEPTION 'Unsupported Play game pack status';
  END IF;
  IF actor_id IS NULL OR NOT public.has_admin_permission(actor_id,
    CASE WHEN _status IN ('approved', 'scheduled', 'active', 'paused', 'retired', 'rejected')
      THEN 'admin.content.publish' ELSE 'admin.content.moderate' END
  ) THEN
    RAISE EXCEPTION 'The required Play publishing permission is not assigned';
  END IF;

  IF _status IN ('approved', 'scheduled', 'active') THEN
    SELECT count(*), count(*) FILTER (WHERE
      rights_status IN ('review_needed', 'restricted', 'rejected')
      OR (experience_type <> 'poll' AND nullif(trim(coalesce(source_title, '')), '') IS NULL
          AND rights_status NOT IN ('creator_approved', 'licensed'))
    ) INTO item_count, unreleasable_count
    FROM public.play_content_items WHERE game_pack_id = _id;
    IF item_count = 0 THEN RAISE EXCEPTION 'Add at least one approved item before releasing this pack'; END IF;
    IF unreleasable_count > 0 THEN
      RAISE EXCEPTION 'Every pack item must be approved and pass source and rights review';
    END IF;
  END IF;

  UPDATE public.play_game_packs SET
    status = _status,
    reviewed_by = CASE WHEN _status IN ('approved', 'scheduled', 'active', 'rejected') THEN actor_id ELSE reviewed_by END,
    published_by = CASE WHEN _status IN ('scheduled', 'active') THEN actor_id ELSE published_by END,
    published_at = CASE WHEN _status = 'active' THEN now() WHEN _status IN ('draft', 'review_needed', 'rejected') THEN NULL ELSE published_at END
  WHERE id = _id RETURNING * INTO saved;
  IF saved.id IS NULL THEN RAISE EXCEPTION 'Play game pack was not found'; END IF;
  IF _status = 'scheduled' AND saved.scheduled_start_at IS NULL THEN
    RAISE EXCEPTION 'A scheduled release requires a start date and time';
  END IF;

  UPDATE public.play_content_items SET
    status = CASE _status
      WHEN 'review_needed' THEN 'review_needed'
      WHEN 'approved' THEN 'approved'
      WHEN 'scheduled' THEN 'scheduled'
      WHEN 'active' THEN 'active'
      WHEN 'paused' THEN 'paused'
      WHEN 'retired' THEN 'retired'
      WHEN 'rejected' THEN 'rejected'
      ELSE 'draft'
    END,
    reviewed_by = CASE WHEN _status IN ('approved', 'scheduled', 'active', 'rejected') THEN actor_id ELSE reviewed_by END,
    published_by = CASE WHEN _status IN ('scheduled', 'active') THEN actor_id ELSE published_by END,
    published_at = CASE WHEN _status = 'active' THEN now() WHEN _status IN ('draft', 'review_needed', 'rejected') THEN NULL ELSE published_at END
  WHERE game_pack_id = _id;
  RETURN saved;
END;
$$;

CREATE OR REPLACE FUNCTION public.save_play_pack_item_v24_33(
  _id uuid,
  _game_pack_id uuid,
  _position integer,
  _content_key text,
  _title text,
  _prompt text,
  _payload jsonb DEFAULT '{}'::jsonb,
  _explanation text DEFAULT '',
  _difficulty text DEFAULT 'intro',
  _rights_status text DEFAULT 'not_required',
  _source_title text DEFAULT NULL,
  _source_url text DEFAULT NULL,
  _verification_notes text DEFAULT '',
  _discovery_url text DEFAULT NULL
)
RETURNS public.play_content_items
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  actor_id uuid := auth.uid();
  pack public.play_game_packs;
  saved public.play_content_items;
BEGIN
  IF actor_id IS NULL OR NOT public.has_admin_permission(actor_id, 'admin.content.moderate') THEN
    RAISE EXCEPTION 'Content Moderator permission is required';
  END IF;
  SELECT * INTO pack FROM public.play_game_packs WHERE id = _game_pack_id;
  IF pack.id IS NULL THEN RAISE EXCEPTION 'Play game pack was not found'; END IF;
  IF pack.status IN ('active', 'scheduled') THEN
    RAISE EXCEPTION 'Pause the game pack before editing its live content';
  END IF;

  IF _id IS NULL THEN
    INSERT INTO public.play_content_items (
      game_pack_id, position, content_key, experience_type, title, prompt, payload, explanation,
      genre, difficulty, visibility, rights_status, source_title, source_url, verification_notes,
      discovery_url, created_by, updated_by
    ) VALUES (
      pack.id, _position, lower(trim(_content_key)), pack.game_type, trim(_title), trim(_prompt),
      coalesce(_payload, '{}'::jsonb), trim(coalesce(_explanation, '')), pack.genre, _difficulty,
      pack.visibility, _rights_status, nullif(trim(coalesce(_source_title, '')), ''),
      nullif(trim(coalesce(_source_url, '')), ''), trim(coalesce(_verification_notes, '')),
      nullif(trim(coalesce(_discovery_url, '')), ''), actor_id, actor_id
    ) RETURNING * INTO saved;
  ELSE
    UPDATE public.play_content_items SET
      game_pack_id = pack.id, position = _position, content_key = lower(trim(_content_key)),
      experience_type = pack.game_type, title = trim(_title), prompt = trim(_prompt),
      payload = coalesce(_payload, '{}'::jsonb), explanation = trim(coalesce(_explanation, '')),
      genre = pack.genre, difficulty = _difficulty, visibility = pack.visibility,
      rights_status = _rights_status, source_title = nullif(trim(coalesce(_source_title, '')), ''),
      source_url = nullif(trim(coalesce(_source_url, '')), ''),
      verification_notes = trim(coalesce(_verification_notes, '')),
      discovery_url = nullif(trim(coalesce(_discovery_url, '')), '')
    WHERE id = _id RETURNING * INTO saved;
    IF saved.id IS NULL THEN RAISE EXCEPTION 'Play pack item was not found'; END IF;
  END IF;
  RETURN saved;
END;
$$;

REVOKE ALL ON FUNCTION public.save_play_game_pack_v24_33(uuid, text, text, text, text, text, text, timestamptz, timestamptz) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.set_play_game_pack_status_v24_33(uuid, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.save_play_pack_item_v24_33(uuid, uuid, integer, text, text, text, jsonb, text, text, text, text, text, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.save_play_game_pack_v24_33(uuid, text, text, text, text, text, text, timestamptz, timestamptz) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_play_game_pack_status_v24_33(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_play_pack_item_v24_33(uuid, uuid, integer, text, text, text, jsonb, text, text, text, text, text, text, text) TO authenticated;
