-- V24.71A Writers & Poets Works, Media & Collections Foundation
create table if not exists public.creator_written_projects(id uuid primary key default gen_random_uuid(),creator_id uuid not null references auth.users(id) on delete cascade,title text not null check(length(btrim(title)) between 1 and 180),project_type text not null default 'book',description text not null default '',cover_path text,external_url text,status text not null default 'active' check(status in('active','archived')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.creator_written_works(id uuid primary key default gen_random_uuid(),creator_id uuid not null references auth.users(id) on delete cascade,project_id uuid references public.creator_written_projects(id) on delete set null,slug text not null unique,title text not null check(length(btrim(title)) between 1 and 180),work_type text not null check(work_type in('poem','short_story','essay_article','excerpt_chapter','creator_note')),excerpt text not null default '',body text not null default '',cover_path text,status text not null default 'draft' check(status in('draft','published','archived')),visibility text not null default 'private' check(visibility in('public','unlisted','private')),show_on_public_profile boolean not null default true,profile_display_order integer not null default 100,rights_confirmed boolean not null default false,published_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists creator_written_works_creator_idx on public.creator_written_works(creator_id,status,updated_at desc);create index if not exists creator_written_works_public_idx on public.creator_written_works(status,visibility,published_at desc);
create table if not exists public.creator_written_work_media(id uuid primary key default gen_random_uuid(),work_id uuid not null references public.creator_written_works(id) on delete cascade,creator_id uuid not null references auth.users(id) on delete cascade,media_type text not null check(media_type in('audio','video','external')),audio_path text,video_id uuid references public.creator_videos(id) on delete set null,external_url text,title text not null default '',caption text not null default '',sort_order integer not null default 100,created_at timestamptz not null default now(),check((media_type='audio' and audio_path is not null and video_id is null and external_url is null) or(media_type='video' and video_id is not null and audio_path is null and external_url is null) or(media_type='external' and external_url is not null and audio_path is null and video_id is null)));
create table if not exists public.creator_written_collections(id uuid primary key default gen_random_uuid(),creator_id uuid not null references auth.users(id) on delete cascade,slug text not null unique,title text not null check(length(btrim(title)) between 1 and 180),description text not null default '',cover_path text,status text not null default 'draft' check(status in('draft','published')),visibility text not null default 'private' check(visibility in('public','unlisted','private')),show_on_public_profile boolean not null default true,profile_display_order integer not null default 100,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.creator_written_collection_items(id uuid primary key default gen_random_uuid(),collection_id uuid not null references public.creator_written_collections(id) on delete cascade,work_id uuid not null references public.creator_written_works(id) on delete cascade,media_id uuid references public.creator_written_work_media(id) on delete set null,position integer not null check(position>0),created_at timestamptz not null default now(),unique(collection_id,position),unique(collection_id,work_id));
-- Ownership integrity prevents cross-creator project/media relationships.
create or replace function public.vybe_validate_written_ownership() returns trigger language plpgsql set search_path=public as $$ begin if new.project_id is not null and not exists(select 1 from public.creator_written_projects p where p.id=new.project_id and p.creator_id=new.creator_id) then raise exception 'Written project must belong to the same creator';end if;return new;end;$$;
drop trigger if exists validate_written_work_ownership on public.creator_written_works;create trigger validate_written_work_ownership before insert or update on public.creator_written_works for each row execute function public.vybe_validate_written_ownership();
create or replace function public.vybe_validate_written_media() returns trigger language plpgsql set search_path=public as $$ begin if not exists(select 1 from public.creator_written_works w where w.id=new.work_id and w.creator_id=new.creator_id) then raise exception 'Written media must belong to the work creator';end if;if new.video_id is not null and not exists(select 1 from public.creator_videos v where v.id=new.video_id and v.creator_id=new.creator_id) then raise exception 'Attached video must belong to the same creator';end if;return new;end;$$;
drop trigger if exists validate_written_media on public.creator_written_work_media;create trigger validate_written_media before insert or update on public.creator_written_work_media for each row execute function public.vybe_validate_written_media();
create or replace function public.vybe_validate_written_collection_item() returns trigger language plpgsql set search_path=public as $$ declare c_creator uuid;w_creator uuid;m_work uuid;begin select creator_id into c_creator from public.creator_written_collections where id=new.collection_id;select creator_id into w_creator from public.creator_written_works where id=new.work_id;if c_creator is null or w_creator is null or c_creator<>w_creator then raise exception 'Collection and work must belong to the same creator';end if;if new.media_id is not null then select work_id into m_work from public.creator_written_work_media where id=new.media_id;if m_work is null or m_work<>new.work_id then raise exception 'Collection media must belong to the selected work';end if;end if;return new;end;$$;
drop trigger if exists validate_written_collection_item on public.creator_written_collection_items;create trigger validate_written_collection_item before insert or update on public.creator_written_collection_items for each row execute function public.vybe_validate_written_collection_item();
-- Enforce existing membership written_post_limit at the database boundary.
create or replace function public.vybe_enforce_written_work_limit() returns trigger language plpgsql security definer set search_path=public as $$ declare lim integer;used integer;plan text;begin select coalesce(a.plan_code,'creator_free') into plan from public.account_entitlements a where a.user_id=new.creator_id limit 1;plan:=coalesce(plan,'creator_free');select written_post_limit into lim from public.creator_plan_definitions where plan_code=plan;if lim is null then lim:=0;end if;select count(*) into used from public.creator_written_works where creator_id=new.creator_id and status<>'archived';if used>=lim then raise exception 'Written work limit reached for current creator membership';end if;return new;end;$$;
drop trigger if exists enforce_written_work_limit on public.creator_written_works;create trigger enforce_written_work_limit before insert on public.creator_written_works for each row execute function public.vybe_enforce_written_work_limit();
-- RLS
alter table public.creator_written_projects enable row level security;alter table public.creator_written_works enable row level security;alter table public.creator_written_work_media enable row level security;alter table public.creator_written_collections enable row level security;alter table public.creator_written_collection_items enable row level security;
create policy written_projects_owner on public.creator_written_projects for all to authenticated using(creator_id=auth.uid()) with check(creator_id=auth.uid());
create policy written_works_owner on public.creator_written_works for all to authenticated using(creator_id=auth.uid()) with check(creator_id=auth.uid());create policy written_works_public_read on public.creator_written_works for select to anon,authenticated using(status='published' and visibility in('public','unlisted'));
create policy written_media_owner on public.creator_written_work_media for all to authenticated using(creator_id=auth.uid()) with check(creator_id=auth.uid());create policy written_media_public_read on public.creator_written_work_media for select to anon,authenticated using(exists(select 1 from public.creator_written_works w where w.id=work_id and w.status='published' and w.visibility in('public','unlisted')));
create policy written_collections_owner on public.creator_written_collections for all to authenticated using(creator_id=auth.uid()) with check(creator_id=auth.uid());create policy written_collections_public_read on public.creator_written_collections for select to anon,authenticated using(status='published' and visibility in('public','unlisted'));
create policy written_collection_items_owner on public.creator_written_collection_items for all to authenticated using(exists(select 1 from public.creator_written_collections c where c.id=collection_id and c.creator_id=auth.uid())) with check(exists(select 1 from public.creator_written_collections c where c.id=collection_id and c.creator_id=auth.uid()));create policy written_collection_items_public_read on public.creator_written_collection_items for select to anon,authenticated using(exists(select 1 from public.creator_written_collections c where c.id=collection_id and c.status='published' and c.visibility in('public','unlisted')));
-- Private writing media buckets. Public playback uses short-lived signed URLs generated only after RLS-visible rows are resolved.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('writing-audio','writing-audio',false,104857600,array['audio/mpeg','audio/mp4','audio/wav','audio/x-wav','audio/ogg','audio/webm']),('writing-covers','writing-covers',false,5242880,array['image/jpeg','image/png','image/webp']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy writing_audio_owner_select on storage.objects for select to authenticated using(bucket_id='writing-audio' and (storage.foldername(name))[1]=auth.uid()::text);create policy writing_audio_owner_insert on storage.objects for insert to authenticated with check(bucket_id='writing-audio' and (storage.foldername(name))[1]=auth.uid()::text);create policy writing_audio_owner_update on storage.objects for update to authenticated using(bucket_id='writing-audio' and (storage.foldername(name))[1]=auth.uid()::text) with check(bucket_id='writing-audio' and (storage.foldername(name))[1]=auth.uid()::text);create policy writing_audio_owner_delete on storage.objects for delete to authenticated using(bucket_id='writing-audio' and (storage.foldername(name))[1]=auth.uid()::text);
create policy writing_covers_owner_select on storage.objects for select to authenticated using(bucket_id='writing-covers' and (storage.foldername(name))[1]=auth.uid()::text);create policy writing_covers_owner_insert on storage.objects for insert to authenticated with check(bucket_id='writing-covers' and (storage.foldername(name))[1]=auth.uid()::text);create policy writing_covers_owner_update on storage.objects for update to authenticated using(bucket_id='writing-covers' and (storage.foldername(name))[1]=auth.uid()::text) with check(bucket_id='writing-covers' and (storage.foldername(name))[1]=auth.uid()::text);create policy writing_covers_owner_delete on storage.objects for delete to authenticated using(bucket_id='writing-covers' and (storage.foldername(name))[1]=auth.uid()::text);
-- Published media may be signed by public readers only when its work is currently published and public/unlisted.
create policy writing_audio_published_select on storage.objects for select to anon,authenticated using(bucket_id='writing-audio' and exists(select 1 from public.creator_written_work_media m join public.creator_written_works w on w.id=m.work_id where m.audio_path=name and w.status='published' and w.visibility in('public','unlisted')));
create policy writing_covers_published_select on storage.objects for select to anon,authenticated using(bucket_id='writing-covers' and exists(select 1 from public.creator_written_works w where w.cover_path=name and w.status='published' and w.visibility in('public','unlisted')));
-- Focus readiness: foundation exists; Admin can advance to available after runtime verification.
update public.creator_focus_readiness set readiness_status='foundation',public_message='Writing Studio foundation is installed for controlled verification.',updated_at=now() where focus_code='writing';
